CREATE TABLE [dbo].[ANNUAL_HOLIDAYS] (
    [ANN_HOLI_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [ANN_HOLI_HD_ID]  NUMERIC (18)   NULL,
    [ANN_HOLI_BR_ID]  NUMERIC (18)   NULL,
    [ANN_HOLI_NAME]   NVARCHAR (200) NULL,
    [ANN_HOLI_DATE]   DATE           NULL,
    [ANN_HOLI_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_ANN_HOLI] PRIMARY KEY CLUSTERED ([ANN_HOLI_ID] ASC),
    CONSTRAINT [FK_ANNUAL_HOLIDAYS_BR_ADMIN] FOREIGN KEY ([ANN_HOLI_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_ANNUAL_HOLIDAYS_MAIN_HD_INFO] FOREIGN KEY ([ANN_HOLI_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

