CREATE TABLE [dbo].[AREA_INFO] (
    [AREA_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [AREA_HD_ID]  NUMERIC (18)   NOT NULL,
    [AREA_BR_ID]  NUMERIC (18)   NULL,
    [AREA_NAME]   NVARCHAR (50)  NULL,
    [AREA_DESC]   NVARCHAR (500) NULL,
    [AREA_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_AREA] PRIMARY KEY CLUSTERED ([AREA_ID] ASC),
    CONSTRAINT [FK_AREA_INFO_BR_ADMIN] FOREIGN KEY ([AREA_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_AREA_INFO_MAIN_HD_INFO] FOREIGN KEY ([AREA_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

