CREATE TABLE [dbo].[ATTENDANCE_STAFF] (
    [ATTENDANCE_STAFF_ID]               NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [ATTENDANCE_STAFF_HD_ID]            NUMERIC (18)  NULL,
    [ATTENDANCE_STAFF_BR_ID]            NUMERIC (18)  NULL,
    [ATTENDANCE_STAFF_TYPE]             NVARCHAR (50) NULL,
    [ATTENDANCE_STAFF_TYPE_ID]          NUMERIC (18)  NULL,
    [ATTENDANCE_STAFF_DATE]             DATE          NULL,
    [ATTENDANCE_STAFF_TIME_IN]          NVARCHAR (50) NULL,
    [ATTENDANCE_STAFF_TIME_OUT]         NVARCHAR (50) NULL,
    [ATTENDANCE_STAFF_CURRENT_TIME_IN]  NVARCHAR (50) NULL,
    [ATTENDANCE_STAFF_CURRENT_TIME_OUT] NVARCHAR (50) NULL,
    [ATTENDANCE_STAFF_ENTER_DATE]       DATETIME      NULL,
    [ATTENDANCE_STAFF_REMARKS]          NVARCHAR (50) NULL,
    [ATTENDANCE_STAFF_STATUS]           NVARCHAR (10) NULL,
    [ATTENDANCE_STAFF_PC_NAME]          NVARCHAR (50) NULL,
    [ATTENDANCE_STAFF_MACHINE_NO]       NVARCHAR (50) NULL,
    CONSTRAINT [PK_ATTENDANCE_STAFF] PRIMARY KEY CLUSTERED ([ATTENDANCE_STAFF_ID] ASC),
    CONSTRAINT [FK_ATTENDANCE_STAFF_BR_ADMIN] FOREIGN KEY ([ATTENDANCE_STAFF_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_ATTENDANCE_STAFF_MAIN_HD_INFO] FOREIGN KEY ([ATTENDANCE_STAFF_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_ATTENDANCE_STAFF_TEACHER_INFO] FOREIGN KEY ([ATTENDANCE_STAFF_TYPE_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

