CREATE TABLE [dbo].[AUTO_SCHEDULE] (
    [SCHEDULE_ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [SCHEDULE_HD_ID]             NUMERIC (18)  NULL,
    [SCHEDULE_BR_ID]             NUMERIC (18)  NULL,
    [SCHEDULE_TYPE]              NVARCHAR (50) NULL,
    [SCHEDULE_TIME]              NVARCHAR (20) NULL,
    [SCHEDULE_DAY]               NVARCHAR (20) NULL,
    [SCHEDULE_DATE]              NVARCHAR (50) NULL,
    [SCHEDULE_STUDENT]           BIT           NULL,
    [SCHEDULE_PARENT]            BIT           NULL,
    [SCHEDULE_STATUS]            BIT           NULL,
    [SCHEDULE_NOTIFICATION_TYPE] NVARCHAR (50) NULL,
    CONSTRAINT [PK_AUTO_SCHEDULE] PRIMARY KEY CLUSTERED ([SCHEDULE_ID] ASC),
    CONSTRAINT [FK_AUTO_SCHEDULE_BR_ADMIN] FOREIGN KEY ([SCHEDULE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_AUTO_SCHEDULE_MAIN_HD_INFO] FOREIGN KEY ([SCHEDULE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

