CREATE TABLE [dbo].[BANK_INFO] (
    [BANK_ID]      NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [BANK_HD_ID]   NUMERIC (18)   NOT NULL,
    [BANK_BR_ID]   NUMERIC (18)   NULL,
    [BANK_NAME]    NVARCHAR (50)  NULL,
    [BANK_ADDRESS] NVARCHAR (200) NULL,
    [BANK_DESC]    NVARCHAR (500) NULL,
    [BANK_STATUS]  CHAR (2)       NULL,
    CONSTRAINT [PK_BANK] PRIMARY KEY CLUSTERED ([BANK_ID] ASC),
    CONSTRAINT [FK_BANK_INFO_BR_ADMIN] FOREIGN KEY ([BANK_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_BANK_INFO_MAIN_HD_INFO] FOREIGN KEY ([BANK_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

