CREATE TABLE [dbo].[BOOKS_ISSUE] (
    [BOOKS_ISSUE_ID]            NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [BOOKS_ISSUE_HD_ID]         NUMERIC (18)   NULL,
    [BOOKS_ISSUE_BR_ID]         NUMERIC (18)   NULL,
    [BOOKS_ISSUE_BOOK_INFO_ID]  NUMERIC (18)   NULL,
    [BOOKS_ISSUE_BORROWER_TYPE] NVARCHAR (50)  NULL,
    [BOOKS_ISSUE_BORROWER_ID]   NUMERIC (18)   NULL,
    [BOOKS_ISSUE_DATE_BORROWED] DATE           NULL,
    [BOOKS_ISSUE_DUE_DATE]      DATE           NULL,
    [BOOKS_ISSUE_DATE_RETURNED] DATE           NULL,
    [BOOKS_ISSUE_FINE_PER_DAY]  INT            NULL,
    [BOOKS_ISSUE_NOTES]         NVARCHAR (200) NULL,
    [BOOKS_ISSUE_STATUS]        NVARCHAR (50)  NULL,
    CONSTRAINT [PK_BOOKS_ISSUE] PRIMARY KEY CLUSTERED ([BOOKS_ISSUE_ID] ASC),
    CONSTRAINT [FK_BOOKS_ISSUE_BOOKS_INFO] FOREIGN KEY ([BOOKS_ISSUE_BOOK_INFO_ID]) REFERENCES [dbo].[BOOKS_INFO] ([BOOKS_INFO_ID]),
    CONSTRAINT [FK_BOOKS_ISSUE_BR_ADMIN] FOREIGN KEY ([BOOKS_ISSUE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_BOOKS_ISSUE_MAIN_HD_INFO] FOREIGN KEY ([BOOKS_ISSUE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

