CREATE TABLE [dbo].[BOOKS_CATEGORIES] (
    [BOOK_CAT_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [BOOK_CAT_HD_ID]       NUMERIC (18)   NULL,
    [BOOK_CAT_BR_ID]       NUMERIC (18)   NULL,
    [BOOK_CAT_NAME]        NVARCHAR (100) NULL,
    [BOOK_CAT_DESCRIPTION] NVARCHAR (500) NULL,
    [BOOK_CAT_STATUS]      CHAR (1)       NULL,
    CONSTRAINT [PK_BOOKS_CATEGORIES] PRIMARY KEY CLUSTERED ([BOOK_CAT_ID] ASC),
    CONSTRAINT [FK_BOOKS_CATEGORIES_BR_ADMIN] FOREIGN KEY ([BOOK_CAT_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_BOOKS_CATEGORIES_MAIN_HD_INFO] FOREIGN KEY ([BOOK_CAT_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

