CREATE TABLE [dbo].[BR_ADMIN] (
    [BR_ADM_ID]                                        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [BR_ADM_HD_ID]                                     NUMERIC (18)   NOT NULL,
    [BR_ADM_NAME]                                      NVARCHAR (50)  NULL,
    [BR_ADM_ADDRESS]                                   NVARCHAR (100) NULL,
    [BR_ADM_PHONE]                                     NVARCHAR (50)  NULL,
    [BR_ADM_EMAIL]                                     NVARCHAR (50)  NULL,
    [BR_ADM_MOBILE]                                    NVARCHAR (50)  NULL,
    [BR_ADM_FAX]                                       NVARCHAR (50)  NULL,
    [BR_ADM_STATUS]                                    CHAR (2)       NULL,
    [BR_ADM_CITY]                                      NVARCHAR (50)  NULL,
    [BR_ADM_COUNTRY]                                   NUMERIC (18)   NULL,
    [BR_ADM_ACCT_START_DATE]                           DATE           NULL,
    [BR_ADM_ACCT_END_DATE]                             DATE           NULL,
    [BR_ADM_WEBSITE]                                   NVARCHAR (50)  NULL,
    [BR_ADM_BANK_NAME]                                 NVARCHAR (100) NULL,
    [BR_ADM_ACCT_TITLE]                                NVARCHAR (50)  NULL,
    [BR_ADM_ACCT_NO]                                   NVARCHAR (50)  NULL,
    [BR_ADM_USER_ROLE]                                 NVARCHAR (100) NULL,
    [BR_ADM_STAFF_CENT_BR_ID]                          INT            NULL,
    [BR_ADM_PARENT_CENT_BR_ID]                         INT            NULL,
    [BR_ADM_ASSEMENT_TYPE]                             NVARCHAR (50)  NULL,
    [BR_ADM_SMS_API_ID]                                NUMERIC (18)   NULL,
    [BR_ADM_PAYROLL_MINUTES_IN_HOUR]                   INT            NULL,
    [BR_ADM_PAYROLL_HOURS_IN_DAY]                      INT            NULL,
    [BR_ADM_PAYROLL_IS_OVERTIME_MONTHLY_SLIP_GENERATE] CHAR (1)       NULL,
    [BR_ADM_PAYROLL_LATE_MINUTES]                      INT            NULL,
    [BR_ADM_PAYROLL_COMMSSION_FORMULA]                 NVARCHAR (200) NULL,
    [BR_ADM_OVERTIME_AFTER_TIMEOUT]                    CHAR (1)       NULL,
    [BR_ADM_OVERTIME_CALCULATION_TYPE]                 NVARCHAR (50)  NULL,
    [BR_ADM_IS_ADVANCE_ACCOUNTING]                     BIT            NULL,
    [BR_ADM_IS_ADVANCE_CLASS_PLAN]                     BIT            NULL,
    [BR_ADM_IS_FEES_WITH_ACCOUNTS]                     BIT            NULL,
    [BR_ADM_FEES_PER_MONTHS]                           FLOAT (53)     NULL,
    [BR_ADM_IS_CLASS_PLAN_ALLOWED]                     BIT            NULL,
    [BR_ADM_IS_BAR_CODE_READER_ALLOW]                  BIT            NULL,
    [BR_ADM_IS_ENTER_MARKS]                            BIT            NULL,
    [BR_ADM_STUDENT_LATE_MINUTES]                      INT            NULL,
    [BR_ADM_SESSION]                                   NUMERIC (18)   NULL,
    [BR_ADM_EARLY_MINUTES_ALLOWED]                     INT            NULL,
    [BR_ADM_HALF_DAY_MINUTES]                          INT            NULL,
    [BR_ADM_ROYALTY_TO_BRANCH]                         INT            NULL,
    [BR_ADM_BOOK_FINE_PER_DAY]                         INT            NULL,
    [BR_ADM_FREE_DAYS]                                 INT            NULL,
    [BR_ADM_LOGO]                                      NVARCHAR (100) NULL,
    [BR_ADM_REPORTS_LOGO]                              NVARCHAR (100) NULL,
    [BR_ADM_IS_DIFFERENT_LOGOS]                        BIT            NULL,
    [BR_ADM_FONTS]                                     NVARCHAR (50)  NULL,
    CONSTRAINT [PK_BR_ADMIN] PRIMARY KEY CLUSTERED ([BR_ADM_ID] ASC),
    CONSTRAINT [FK_BR_ADMIN_MAIN_HD_INFO] FOREIGN KEY ([BR_ADM_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_BR_ADMIN_SESSION_INFO] FOREIGN KEY ([BR_ADM_SESSION]) REFERENCES [dbo].[SESSION_INFO] ([SESSION_ID]),
    CONSTRAINT [UQ__BR_ADMIN__7B0B26142136E270] UNIQUE NONCLUSTERED ([BR_ADM_EMAIL] ASC)
);

