CREATE TABLE [dbo].[BRANCH_LEVEL] (
    [BRANCH_LEVEL_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [BRANCH_LEVEL_HD_ID]       NUMERIC (18)   NULL,
    [BRANCH_LEVEL_BR_ID]       NUMERIC (18)   NULL,
    [BRANCH_LEVEL_LEVEL_ID]    NUMERIC (18)   NULL,
    [BRANCH_LEVEL_LOGO]        NVARCHAR (MAX) NULL,
    [BRANCH_LEVEL_FONTS]       NVARCHAR (50)  NULL,
    [BRANCH_LEVEL_SCHOOL_NAME] NVARCHAR (50)  NULL,
    CONSTRAINT [PK_BRANCH_LEVEL] PRIMARY KEY CLUSTERED ([BRANCH_LEVEL_ID] ASC),
    CONSTRAINT [FK_BRANCH_LEVEL_BR_ADMIN] FOREIGN KEY ([BRANCH_LEVEL_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_BRANCH_LEVEL_LEVELS] FOREIGN KEY ([BRANCH_LEVEL_LEVEL_ID]) REFERENCES [dbo].[LEVELS] ([LEVEL_ID]),
    CONSTRAINT [FK_BRANCH_LEVEL_MAIN_HD_INFO] FOREIGN KEY ([BRANCH_LEVEL_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

