CREATE TABLE [dbo].[CHART_SETTING] (
    [CHART_ID]       NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [CHART_NAME]     NVARCHAR (100) NULL,
    [CHART_WIDTH]    NUMERIC (18)   NULL,
    [CHART_HEIGHT]   NUMERIC (18)   NULL,
    [CHART_LOGIN_ID] NUMERIC (18)   NULL,
    [CHART_STATUS]   CHAR (2)       NULL,
    CONSTRAINT [PK_CHART_SETTING] PRIMARY KEY CLUSTERED ([CHART_ID] ASC)
);

