CREATE TABLE [dbo].[CHEQUE_INFO] (
    [CHEQ_ID]             NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [CHEQ_HD_ID]          NUMERIC (18)    NULL,
    [CHEQ_BR_ID]          NUMERIC (18)    NULL,
    [CHEQ_CHEQUE_NO]      NVARCHAR (50)   NULL,
    [CHEQ_AMOUNT]         FLOAT (53)      NULL,
    [CHEQ_DATE]           DATE            NULL,
    [CHEQ_BANK_NAME]      NVARCHAR (100)  NULL,
    [CHEQ_CLEARANCE_DATE] DATE            NULL,
    [CHEQ_ENTERED_DATE]   DATETIME        NULL,
    [CHEQ_IS_CLEARED]     BIT             NULL,
    [CHEQ_COA_ACCOUNT]    NVARCHAR (50)   NULL,
    [CHEQ_REMARKS]        NVARCHAR (1000) NULL,
    [CHEQ_IS_DISHONORED]  BIT             NULL,
    CONSTRAINT [PK_CHEQUE_INFO] PRIMARY KEY CLUSTERED ([CHEQ_ID] ASC),
    CONSTRAINT [FK_CHEQUE_INFO_BR_ADMIN] FOREIGN KEY ([CHEQ_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_CHEQUE_INFO_MAIN_HD_INFO] FOREIGN KEY ([CHEQ_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

