CREATE TABLE [dbo].[CHEQ_FEE_SUMMARY] (
    [CHEQ_FEE_SUM_ID]         NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [CHEQ_FEE_SUM_CHEQUE_IDS] NVARCHAR (2000) NULL,
    [CHEQ_FEE_SUM_FEE_IDS]    NVARCHAR (2000) NULL,
    CONSTRAINT [PK_CHEQ_FEE_SUMMARY] PRIMARY KEY CLUSTERED ([CHEQ_FEE_SUM_ID] ASC)
);

