CREATE TABLE [dbo].[CLASS_INFO] (
    [CLASS_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [CLASS_HD_ID]  NUMERIC (18)   NOT NULL,
    [CLASS_BR_ID]  NUMERIC (18)   NULL,
    [CLASS_NAME]   NVARCHAR (50)  NULL,
    [CLASS_DESC]   NVARCHAR (500) NULL,
    [CLASS_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_CLASS] PRIMARY KEY CLUSTERED ([CLASS_ID] ASC),
    CONSTRAINT [FK_CLASS_INFO_BR_ADMIN] FOREIGN KEY ([CLASS_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_CLASS_INFO_MAIN_HD_INFO] FOREIGN KEY ([CLASS_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

