CREATE TABLE [dbo].[COA] (
    [COA_ID]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [COA_HD_ID]     NUMERIC (18)   NULL,
    [COA_BR_ID]     NUMERIC (18)   NULL,
    [COA_NAME]      NVARCHAR (200) NULL,
    [COA_TYPE]      CHAR (1)       NULL,
    [COA_PARENT_ID] NUMERIC (18)   NULL,
    [COA_STATUS]    CHAR (2)       NULL,
    CONSTRAINT [PK_COA_ID] PRIMARY KEY CLUSTERED ([COA_ID] ASC),
    CONSTRAINT [FK_COA_BR_ADMIN] FOREIGN KEY ([COA_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_COA_MAIN_HD_INFO] FOREIGN KEY ([COA_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

