CREATE TABLE [dbo].[COA_TRANS] (
    [COA_TRANS_ID]         NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [COA_TRANS_HD_ID]      NUMERIC (18)    NULL,
    [COA_TRANS_BR_ID]      NUMERIC (18)    NULL,
    [COA_TRANS_NAME]       NVARCHAR (4000) NULL,
    [COA_TRANS_QTY]        NUMERIC (18)    NULL,
    [COA_TRANS_VALUE]      FLOAT (53)      NULL,
    [COA_TRANS_CID]        NUMERIC (18)    NULL,
    [COA_TRANS_DATE]       DATE            NULL,
    [COA_TRANS_ENTER_DATE] DATETIME        NULL,
    [COA_TRANS_STATUS]     CHAR (2)        NULL,
    CONSTRAINT [PK_COA_TRANS] PRIMARY KEY CLUSTERED ([COA_TRANS_ID] ASC),
    CONSTRAINT [FK_COA_TRANS_BR_ADMIN] FOREIGN KEY ([COA_TRANS_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_COA_TRANS_MAIN_HD_INFO] FOREIGN KEY ([COA_TRANS_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

