CREATE TABLE [dbo].[COLLEGE_PLAN] (
    [CLG_ID]              NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [CLG_HD_ID]           NUMERIC (18)  NOT NULL,
    [CLG_DPRMNT]          NVARCHAR (50) NULL,
    [CLG_CLASS]           NVARCHAR (50) NULL,
    [CLG_DEGREE]          NVARCHAR (50) NULL,
    [CLG_SECTION]         NVARCHAR (50) NULL,
    [CLG_SHIFT]           NVARCHAR (50) NULL,
    [CLG_SUBJECT]         NVARCHAR (50) NULL,
    [CLG_SEQ_NO]          INT           NULL,
    [CLG_PRICE]           FLOAT (53)    NULL,
    [CLG_VARIATION_PRCNT] FLOAT (53)    NULL,
    [CLG_STATUS]          CHAR (2)      NULL,
    CONSTRAINT [PK_COLLEGE_PLAN] PRIMARY KEY CLUSTERED ([CLG_ID] ASC),
    CONSTRAINT [FK_COLLEGE_PLAN_MAIN_HD_INFO] FOREIGN KEY ([CLG_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

