CREATE TABLE [dbo].[COMBINE_BRANCHES] (
    [ID]                  NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [FROM_BRANCH_ID]      NUMERIC (18) NULL,
    [COMBINE_BRANCHES_ID] NUMERIC (18) NULL,
    CONSTRAINT [PK_COMBINE_BRANCHES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COMBINE_BRANCHES_BR_ADMIN_COMBINE_BRANCHES] FOREIGN KEY ([COMBINE_BRANCHES_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_COMBINE_BRANCHES_BR_ADMIN_FROM_BRANCH] FOREIGN KEY ([FROM_BRANCH_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID])
);

