CREATE TABLE [dbo].[CONDUCT_INFO] (
    [CONDUCT_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [CONDUCT_HD_ID]  NUMERIC (18)   NOT NULL,
    [CONDUCT_BR_ID]  NUMERIC (18)   NULL,
    [CONDUCT_NAME]   NVARCHAR (50)  NULL,
    [CONDUCT_DESC]   NVARCHAR (500) NULL,
    [CONDUCT_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_CONDUCT] PRIMARY KEY CLUSTERED ([CONDUCT_ID] ASC),
    CONSTRAINT [FK_CONDUCT_INFO_BR_ADMIN] FOREIGN KEY ([CONDUCT_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_CONDUCT_INFO_MAIN_HD_INFO] FOREIGN KEY ([CONDUCT_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

