CREATE TABLE [dbo].[DASHBOARD_SETTING] (
    [DASHBOARD_ID]       NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [DASHBOARD_DOCKZONE] NVARCHAR (100) NULL,
    [DASHBOARD_WIDTH]    NUMERIC (18)   NULL,
    [DASHBOARD_LOGIN_ID] NUMERIC (18)   NULL,
    [DASHBOARD_STATUS]   CHAR (2)       NULL,
    CONSTRAINT [PK_DASHBOARD_SETTING] PRIMARY KEY CLUSTERED ([DASHBOARD_ID] ASC)
);

