CREATE TABLE [dbo].[DATE_INFO] (
    [DATE_ID]     NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [DATE_HD_ID]  NUMERIC (18)  NOT NULL,
    [DATE_BR_ID]  NUMERIC (18)  NULL,
    [DATE_NAME]   NVARCHAR (50) NULL,
    [DATE_FORMAT] NVARCHAR (50) NULL,
    [DATE_STATUS] CHAR (2)      NULL,
    CONSTRAINT [PK_DATE_INFORMATION] PRIMARY KEY CLUSTERED ([DATE_ID] ASC),
    CONSTRAINT [FK_DATE_INFO_BR_ADMIN] FOREIGN KEY ([DATE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_DATE_INFO_MAIN_HD_INFO] FOREIGN KEY ([DATE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

