CREATE TABLE [dbo].[DEDUCTION] (
    [DEDUCTION_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [DEDUCTION_HD_ID]       NUMERIC (18)   NULL,
    [DEDUCTION_BR_ID]       NUMERIC (18)   NULL,
    [DEDUCTION_NAME]        NVARCHAR (200) NULL,
    [DEDUCTION_DESCRIPTION] NVARCHAR (200) NULL,
    [DEDUCTION_DATE]        DATETIME       NULL,
    [DEDUCTION_STATUS]      CHAR (2)       NULL,
    CONSTRAINT [PK_DEDUCTION] PRIMARY KEY CLUSTERED ([DEDUCTION_ID] ASC),
    CONSTRAINT [FK_DEDUCTION_BR_ADMIN] FOREIGN KEY ([DEDUCTION_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_DEDUCTION_MAIN_HD_INFO] FOREIGN KEY ([DEDUCTION_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

