CREATE TABLE [dbo].[DEFAULT_VALUES] (
    [ID]         NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [HD_ID]      NUMERIC (18)   NULL,
    [BR_ID]      NUMERIC (18)   NULL,
    [PAGE_NAME]  NVARCHAR (50)  NULL,
    [VALUE_NAME] NVARCHAR (100) NULL,
    [VALUE]      NVARCHAR (500) NULL,
    CONSTRAINT [PK_DEFAULT_VALUES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEFAULT_VALUES_BR_ADMIN] FOREIGN KEY ([BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_DEFAULT_VALUES_MAIN_HD_INFO] FOREIGN KEY ([HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

