CREATE TABLE [dbo].[DEPARTMENT_INFO] (
    [DEP_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [DEP_HD_ID]  NUMERIC (18)   NOT NULL,
    [DEP_BR_ID]  NUMERIC (18)   NULL,
    [DEP_NAME]   NVARCHAR (50)  NULL,
    [DEP_DESC]   NVARCHAR (500) NULL,
    [DEP_STATUS] CHAR (2)       NULL,
    [DEP_RANK]   INT            NULL,
    CONSTRAINT [PK_DEPARTMENT] PRIMARY KEY CLUSTERED ([DEP_ID] ASC),
    CONSTRAINT [FK_DEPARTMENT_INFO_BR_ADMIN] FOREIGN KEY ([DEP_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_DEPARTMENT_INFO_MAIN_HD_INFO] FOREIGN KEY ([DEP_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

