CREATE TABLE [dbo].[DEPERCIATION] (
    [DEP_ID]       NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [DEP_HD_ID]    NUMERIC (18) NULL,
    [DEP_BR_ID]    NUMERIC (18) NULL,
    [DEP_COA_ID]   NUMERIC (18) NULL,
    [DEP_YEAR]     INT          NULL,
    [DEP_ADDITION] DECIMAL (18) NULL,
    [DEP_RATE]     DECIMAL (18) NULL,
    [DEP_COST]     DECIMAL (18) NULL,
    [DEP_TOTAL]    DECIMAL (18) NULL,
    CONSTRAINT [PK_DEPERCIATION] PRIMARY KEY CLUSTERED ([DEP_ID] ASC),
    CONSTRAINT [FK_DEPERCIATION_BR_ADMIN] FOREIGN KEY ([DEP_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_DEPERCIATION_MAIN_HD_INFO] FOREIGN KEY ([DEP_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

