CREATE TABLE [dbo].[DISCOUNT_RULES_DEF] (
    [DIS_RUL_DEF_ID]       NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [DIS_RUL_DEF_PID]      NUMERIC (18) NULL,
    [DIS_RUL_DEF_FEE_ID]   NUMERIC (18) NULL,
    [DIS_RUL_DEF_DISCOUNT] FLOAT (53)   NULL,
    [DIS_RUL_DEF_STATUS]   CHAR (2)     NULL,
    CONSTRAINT [PK_DISCOUNT_RULES_DEF] PRIMARY KEY CLUSTERED ([DIS_RUL_DEF_ID] ASC),
    CONSTRAINT [FK_DISCOUNT_RULES_DEF_DISCOUNT_RULES] FOREIGN KEY ([DIS_RUL_DEF_PID]) REFERENCES [dbo].[DISCOUNT_RULES] ([DIS_RUL_ID]),
    CONSTRAINT [FK_DISCOUNT_RULES_DEF_FEE_INFO] FOREIGN KEY ([DIS_RUL_DEF_FEE_ID]) REFERENCES [dbo].[FEE_INFO] ([FEE_ID])
);

