CREATE TABLE [dbo].[DOC_NAME_INFO] (
    [DOC_NAME_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [DOC_NAME_HD_ID]  NUMERIC (18)   NOT NULL,
    [DOC_NAME_BR_ID]  NUMERIC (18)   NULL,
    [DOC_NAME_NAME]   NVARCHAR (50)  NULL,
    [DOC_NAME_DESC]   NVARCHAR (500) NULL,
    [DOC_NAME_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_DOC_NAME] PRIMARY KEY CLUSTERED ([DOC_NAME_ID] ASC),
    CONSTRAINT [FK_DOC_NAME_INFO_BR_ADMIN] FOREIGN KEY ([DOC_NAME_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_DOC_NAME_INFO_MAIN_HD_INFO] FOREIGN KEY ([DOC_NAME_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

