CREATE TABLE [dbo].[DOC_CUSTODIAN_INFO] (
    [DOC_CUSTODIAN_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [DOC_CUSTODIAN_HD_ID]  NUMERIC (18)   NOT NULL,
    [DOC_CUSTODIAN_BR_ID]  NUMERIC (18)   NULL,
    [DOC_CUSTODIAN_NAME]   NVARCHAR (50)  NULL,
    [DOC_CUSTODIAN_DESC]   NVARCHAR (500) NULL,
    [DOC_CUSTODIAN_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_DOC_CUSTODIAN] PRIMARY KEY CLUSTERED ([DOC_CUSTODIAN_ID] ASC),
    CONSTRAINT [FK_DOC_CUSTODIAN_INFO_BR_ADMIN] FOREIGN KEY ([DOC_CUSTODIAN_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_DOC_CUSTODIAN_INFO_MAIN_HD_INFO] FOREIGN KEY ([DOC_CUSTODIAN_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

