CREATE TABLE [dbo].[DOC_INFO] (
    [DOC_INFO_ID]       NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [DOC_INFO_ACT_ID]   NUMERIC (18)   NULL,
    [DOC_INFO_ACT_TYPE] NVARCHAR (20)  NULL,
    [DOC_INFO_NAME]     NVARCHAR (500) NULL,
    [DOC_INFO_CUSTODAN] NVARCHAR (500) NULL,
    [DOC_INFO_TEXT]     NVARCHAR (500) NULL,
    [DOC_INFO_PATH]     NVARCHAR (MAX) NULL,
    [DOC_INFO_STATUS]   CHAR (2)       NULL,
    CONSTRAINT [PK_DOC_INFO] PRIMARY KEY CLUSTERED ([DOC_INFO_ID] ASC)
);

