CREATE TABLE [dbo].[dt_parent] (
    [Session]            NVARCHAR (100) NULL,
    [Class]              NVARCHAR (100) NULL,
    [Term]               NVARCHAR (100) NULL,
    [Term Duration]      NVARCHAR (100) NULL,
    [Std ID]             INT            NULL,
    [Std Name]           NVARCHAR (100) NULL,
    [Std Roll#]          INT            NULL,
    [Total Marks]        FLOAT (53)     NULL,
    [Grand Total]        FLOAT (53)     NULL,
    [Percent]            FLOAT (53)     NULL,
    [No of Std]          INT            NULL,
    [Position]           INT            NULL,
    [Grade]              NVARCHAR (100) NULL,
    [Total Days]         INT            NULL,
    [Total Working Days] INT            NULL,
    [Present]            INT            NULL,
    [Absent]             INT            NULL,
    [Leave]              INT            NULL,
    [Late]               INT            NULL,
    [Max Marks]          FLOAT (53)     NULL,
    [term_id]            INT            NULL,
    [class_id]           INT            NULL,
    [Section]            NVARCHAR (100) NULL,
    [Shift]              NVARCHAR (100) NULL,
    [Total Pass Marks]   FLOAT (53)     NULL,
    [Remarks]            NVARCHAR (100) NULL,
    [Total Positions]    INT            NULL,
    [Parent ID]          INT            NULL,
    [HD ID]              INT            NULL,
    [BR ID]              INT            NULL,
    [Std Image]          NVARCHAR (MAX) NULL
);

