CREATE TABLE [dbo].[ELECTIVE_SUBJECT_DEF] (
    [ELE_SUB_DEF_ID]     NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [ELE_SUB_DEF_PID]    NUMERIC (18) NULL,
    [ELE_SUB_DEF_SUB_ID] NUMERIC (18) NULL,
    [ELE_SUB_DEF_STATUS] CHAR (2)     NULL,
    CONSTRAINT [PK_ELECTIVE_SUBJECT_DEF] PRIMARY KEY CLUSTERED ([ELE_SUB_DEF_ID] ASC),
    CONSTRAINT [FK_ELECTIVE_SUBJECT_DEF_ELECTIVE_SUBJECT] FOREIGN KEY ([ELE_SUB_DEF_PID]) REFERENCES [dbo].[ELECTIVE_SUBJECT] ([ELE_SUB_ID]),
    CONSTRAINT [FK_ELECTIVE_SUBJECT_DEF_SUBJECT_INFO] FOREIGN KEY ([ELE_SUB_DEF_SUB_ID]) REFERENCES [dbo].[SUBJECT_INFO] ([SUB_ID])
);

