CREATE TABLE [dbo].[ELECTIVE_SUBJECT] (
    [ELE_SUB_ID]       NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [ELE_SUB_HD_ID]    NUMERIC (18)  NULL,
    [ELE_SUB_BR_ID]    NUMERIC (18)  NULL,
    [ELE_SUB_NAME]     NVARCHAR (50) NULL,
    [ELE_SUB_CLASS_ID] NUMERIC (18)  NULL,
    [ELE_SUB_STATUS]   CHAR (2)      NULL,
    [ELE_SUB_DATETIME] DATETIME      NULL,
    [ELE_SUB_USER]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_ELECTIVE_SUBJECT] PRIMARY KEY CLUSTERED ([ELE_SUB_ID] ASC),
    CONSTRAINT [FK_ELECTIVE_SUBJECT_BR_ADMIN] FOREIGN KEY ([ELE_SUB_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_ELECTIVE_SUBJECT_MAIN_HD_INFO] FOREIGN KEY ([ELE_SUB_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_ELECTIVE_SUBJECT_SCHOOL_PLANE] FOREIGN KEY ([ELE_SUB_CLASS_ID]) REFERENCES [dbo].[SCHOOL_PLANE] ([CLASS_ID])
);

