CREATE TABLE [dbo].[EVENT_INFO] (
    [ENT_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [ENT_HD_ID]  NUMERIC (18)   NOT NULL,
    [ENT_BR_ID]  NUMERIC (18)   NULL,
    [ENT_NAME]   NVARCHAR (50)  NULL,
    [ENT_DESC]   NVARCHAR (500) NULL,
    [ENT_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_EVENT_INFO] PRIMARY KEY CLUSTERED ([ENT_ID] ASC),
    CONSTRAINT [FK_EVENT_INFO_BR_ADMIN] FOREIGN KEY ([ENT_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_EVENT_INFO_MAIN_HD_INFO] FOREIGN KEY ([ENT_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

