CREATE TABLE [dbo].[EXAM_APPROVAL_STATUS] (
    [EXAM_APPROVAL_ID]              INT            IDENTITY (1, 1) NOT NULL,
    [EXAM_APPROVAL_PLAN_EXAM_ID]    INT            NULL,
    [EXAM_APPROVAL_RANKWISE_STATUS] NVARCHAR (100) NOT NULL
);

