CREATE TABLE [dbo].[EXAM] (
    [EXAM_ID]                   NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [EXAM_HD_ID]                NUMERIC (18)  NULL,
    [EXAM_BR_ID]                NUMERIC (18)  NULL,
    [EXAM_CLASS_PLAN_ID]        NUMERIC (18)  NULL,
    [EXAM_NAME]                 NVARCHAR (50) NULL,
    [EXAM_TOTAL_TYPE]           NVARCHAR (50) NULL,
    [EXAM_STATUS]               CHAR (2)      NULL,
    [EXAM_SESSION_START_DATE]   DATE          NULL,
    [EXAM_SESSION_END_DATE]     DATE          NULL,
    [EXAM_FAIL_LIMIT]           INT           NULL,
    [EXAM_FAIL_AND_GRACE_LIMIT] INT           NULL,
    CONSTRAINT [PK_EXAM] PRIMARY KEY CLUSTERED ([EXAM_ID] ASC),
    CONSTRAINT [FK_EXAM_BR_ADMIN] FOREIGN KEY ([EXAM_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_EXAM_MAIN_HD_INFO] FOREIGN KEY ([EXAM_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_EXAM_SCHOOL_PLANE] FOREIGN KEY ([EXAM_CLASS_PLAN_ID]) REFERENCES [dbo].[SCHOOL_PLANE] ([CLASS_ID])
);

