CREATE TABLE [dbo].[EXAM_APPROVAL_SETTINGS] (
    [APPROVAL_ID]          NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [APPROVAL_HD_ID]       NUMERIC (18)  NULL,
    [APPROVAL_BR_ID]       NUMERIC (18)  NULL,
    [APPROVAL_STAFF_ID]    NUMERIC (18)  NULL,
    [APPROVAL_DESIGNATION] NVARCHAR (50) NULL,
    [APPROVAL_RANK]        INT           NULL,
    [APPROVAL_STATUS]      CHAR (2)      NULL,
    CONSTRAINT [FK_EXAM_APPROVAL_SETTINGS_BR_ADMIN] FOREIGN KEY ([APPROVAL_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_EXAM_APPROVAL_SETTINGS_MAIN_HD_INFO] FOREIGN KEY ([APPROVAL_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_EXAM_APPROVAL_SETTINGS_TEACHER_INFO] FOREIGN KEY ([APPROVAL_STAFF_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

