CREATE TABLE [dbo].[EXAM_ENTRY] (
    [EXAM_ENTRY_ID]                 NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [EXAM_ENTRY_PLAN_EXAM_ID]       NUMERIC (18)  NULL,
    [EXAM_ENTRY_EXAM_TYPE]          NVARCHAR (50) NULL,
    [EXAM_ENTRY_STUDENT_ID]         NUMERIC (18)  NULL,
    [EXAM_ENTRY_OBTAIN_MARKS]       FLOAT (53)    NULL,
    [EXAM_ENTRY_ENTER_DATE]         DATETIME      NULL,
    [EXAM_ENTRY_STATUS]             CHAR (2)      NULL,
    [EXAM_ENTRY_OBTAINED_MARKS_LOG] NVARCHAR (50) NULL,
    [CREATED_BY]                    NUMERIC (18)  NULL,
    [UPDATED_DATE]                  DATETIME      NULL,
    [UPDATED_BY]                    NUMERIC (18)  NULL,
    CONSTRAINT [PK_EXAM_ENTRY] PRIMARY KEY CLUSTERED ([EXAM_ENTRY_ID] ASC),
    CONSTRAINT [FK_EXAM_ENTRY_EXAM_DEF] FOREIGN KEY ([EXAM_ENTRY_PLAN_EXAM_ID]) REFERENCES [dbo].[EXAM_DEF] ([EXAM_DEF_ID]),
    CONSTRAINT [FK_EXAM_ENTRY_STUDENT_INFO] FOREIGN KEY ([EXAM_ENTRY_STUDENT_ID]) REFERENCES [dbo].[STUDENT_INFO] ([STDNT_ID])
);

