CREATE TABLE [dbo].[EXAM_CRITERIA_KEY_Parent] (
    [Id]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [HdId]        NUMERIC (18)   NULL,
    [BrId]        NUMERIC (18)   NULL,
    [Title]       NVARCHAR (500) NULL,
    [SessionId]   NUMERIC (18)   NULL,
    [CreatedBy]   NUMERIC (18)   NULL,
    [CreatedDate] DATETIME       NULL,
    [UpdatedBy]   NUMERIC (18)   NULL,
    [UpdatedDate] DATETIME       NULL,
    CONSTRAINT [PK_EXAM_CRITERIA_KEY_Parent] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_Parent_BR_ADMIN] FOREIGN KEY ([BrId]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_Parent_MAIN_HD_INFO] FOREIGN KEY ([HdId]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_Parent_SESSION_INFO] FOREIGN KEY ([SessionId]) REFERENCES [dbo].[SESSION_INFO] ([SESSION_ID]),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_Parent_USER_INFO] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[USER_INFO] ([USER_ID])
);

