CREATE TABLE [dbo].[EXAM_TEST] (
    [EXAM_TEST_ID]            NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [EXAM_TEST_HD_ID]         NUMERIC (18)   NULL,
    [EXAM_TEST_BR_ID]         NUMERIC (18)   NULL,
    [EXAM_TEST_CLASS_ID]      NUMERIC (18)   NULL,
    [EXAM_TEST_INFO_ID]       NUMERIC (18)   NULL,
    [EXAM_TEST_TERM_ID]       NUMERIC (18)   NULL,
    [EXAM_TEST_SUBJECT_ID]    NUMERIC (18)   NULL,
    [EXAM_TEST_NAME]          NVARCHAR (200) NULL,
    [EXAM_TEST_TOTAL_MARKS]   FLOAT (53)     NULL,
    [EXAM_TEST_PASS_%AGE]     FLOAT (53)     NULL,
    [EXAM_TEST_PLAN_GRADE_ID] NUMERIC (18)   NULL,
    [EXAM_TEST_ENTER_DATE]    DATE           NULL,
    [EXAM_TEST_STATUS]        CHAR (2)       NULL,
    [EXAM_TEST_TYPE]          NVARCHAR (50)  NULL,
    CONSTRAINT [PK_EXAM_TEST] PRIMARY KEY CLUSTERED ([EXAM_TEST_ID] ASC),
    CONSTRAINT [FK_EXAM_TEST_BR_ADMIN] FOREIGN KEY ([EXAM_TEST_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_EXAM_TEST_MAIN_HD_INFO] FOREIGN KEY ([EXAM_TEST_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_EXAM_TEST_SCHOOL_PLANE] FOREIGN KEY ([EXAM_TEST_CLASS_ID]) REFERENCES [dbo].[SCHOOL_PLANE] ([CLASS_ID]),
    CONSTRAINT [FK_EXAM_TEST_SUBJECT_INFO] FOREIGN KEY ([EXAM_TEST_SUBJECT_ID]) REFERENCES [dbo].[SUBJECT_INFO] ([SUB_ID]),
    CONSTRAINT [FK_EXAM_TEST_TERM_INFO] FOREIGN KEY ([EXAM_TEST_TERM_ID]) REFERENCES [dbo].[TERM_INFO] ([TERM_ID])
);

