CREATE TABLE [dbo].[EXAM_CATEGORY_CRITERIA] (
    [CAT_CRITERIA_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [CAT_CRITERIA_HD_ID]       NUMERIC (18)   NULL,
    [CAT_CRITERIA_BR_ID]       NUMERIC (18)   NULL,
    [CAT_CRITERIA_EXAM_CAT_ID] NUMERIC (18)   NULL,
    [CAT_CRITERIA_NAME]        NVARCHAR (300) NULL,
    [CAT_CRITERIA_STATUS]      CHAR (2)       NULL,
    CONSTRAINT [PK_EXAM_CATEGORY_CRITERIA] PRIMARY KEY CLUSTERED ([CAT_CRITERIA_ID] ASC),
    CONSTRAINT [FK_EXAM_CATEGORY_CRITERIA_BR_ADMIN] FOREIGN KEY ([CAT_CRITERIA_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_EXAM_CATEGORY_CRITERIA_EXAM_ASSESS_CATEGORY_INFO] FOREIGN KEY ([CAT_CRITERIA_EXAM_CAT_ID]) REFERENCES [dbo].[EXAM_ASSESS_CATEGORY_INFO] ([EXAM_CAT_ID]),
    CONSTRAINT [FK_EXAM_CATEGORY_CRITERIA_MAIN_HD_INFO] FOREIGN KEY ([CAT_CRITERIA_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

