CREATE TABLE [dbo].[EXAM_CRITERIA_KEY] (
    [CRITERIA_KEY_ID]              NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [CRITERIA_KEY_STD_ID]          NUMERIC (18)  NULL,
    [CRITERIA_KEY_CAT_CRITERIA_ID] NUMERIC (18)  NULL,
    [CRITERIA_KEY]                 NVARCHAR (15) NULL,
    [CRITERIA_KEY_PRINCIPAL]       NVARCHAR (15) NULL,
    [CRITERIA_KEY_TERM_ID]         NUMERIC (18)  NULL,
    [CRITERIA_KEY_CLASS_ID]        NUMERIC (18)  NULL,
    [CRITERIA_KEY_PID]             NUMERIC (18)  NULL,
    CONSTRAINT [PK_EXAM_CRITERIA_KEY] PRIMARY KEY CLUSTERED ([CRITERIA_KEY_ID] ASC),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_EXAM_CATEGORY_CRITERIA] FOREIGN KEY ([CRITERIA_KEY_CAT_CRITERIA_ID]) REFERENCES [dbo].[EXAM_CATEGORY_CRITERIA] ([CAT_CRITERIA_ID]),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_EXAM_CRITERIA_KEY_Parent] FOREIGN KEY ([CRITERIA_KEY_PID]) REFERENCES [dbo].[EXAM_CRITERIA_KEY_Parent] ([Id]),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_SCHOOL_PLANE] FOREIGN KEY ([CRITERIA_KEY_CLASS_ID]) REFERENCES [dbo].[SCHOOL_PLANE] ([CLASS_ID]),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_STUDENT_INFO] FOREIGN KEY ([CRITERIA_KEY_STD_ID]) REFERENCES [dbo].[STUDENT_INFO] ([STDNT_ID]),
    CONSTRAINT [FK_EXAM_CRITERIA_KEY_TERM_ASSESSMENT_INFO] FOREIGN KEY ([CRITERIA_KEY_TERM_ID]) REFERENCES [dbo].[TERM_ASSESSMENT_INFO] ([TERM_ASSESS_ID])
);

