CREATE TABLE [dbo].[EXAM_STD_ATTENDANCE_INFO] (
    [EXAM_STD_ATT_ID]           NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [EXAM_STD_ATT_STD_ID]       NUMERIC (18) NULL,
    [EXAM_STD_ATT_CLASS_ID]     NUMERIC (18) NULL,
    [EXAM_STD_ATT_SUB_ID]       NUMERIC (18) NULL,
    [EXAM_STD_ATT_TERM_ID]      NUMERIC (18) NULL,
    [EXAM_STD_ATT_TOTAL_DAYS]   INT          NULL,
    [EXAM_STD_ATT_PRESENT_DAYS] INT          NULL,
    CONSTRAINT [PK_EXAM_STD_ATTENDANCE_INFO] PRIMARY KEY CLUSTERED ([EXAM_STD_ATT_ID] ASC),
    CONSTRAINT [FK_EXAM_STD_ATTENDANCE_INFO_SCHOOL_PLANE] FOREIGN KEY ([EXAM_STD_ATT_CLASS_ID]) REFERENCES [dbo].[SCHOOL_PLANE] ([CLASS_ID]),
    CONSTRAINT [FK_EXAM_STD_ATTENDANCE_INFO_STUDENT_INFO] FOREIGN KEY ([EXAM_STD_ATT_STD_ID]) REFERENCES [dbo].[STUDENT_INFO] ([STDNT_ID]),
    CONSTRAINT [FK_EXAM_STD_ATTENDANCE_INFO_TERM_INFO] FOREIGN KEY ([EXAM_STD_ATT_TERM_ID]) REFERENCES [dbo].[TERM_INFO] ([TERM_ID])
);

