CREATE TABLE [dbo].[EXTRA_HOLIDAYS] (
    [ID]                  NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [STAFF_ID]            NUMERIC (18)  NULL,
    [PID]                 NUMERIC (18)  NULL,
    [DATE]                DATE          NULL,
    [TIME_IN]             NVARCHAR (50) NULL,
    [TIME_OUT]            NVARCHAR (50) NULL,
    [IS_SALARY_GENERATED] BIT           NULL,
    CONSTRAINT [PK_EXTRA_HOLIDAYS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EXTRA_HOLIDAYS_EXTRA_HOLIDAYS_PARENT] FOREIGN KEY ([PID]) REFERENCES [dbo].[EXTRA_HOLIDAYS_PARENT] ([ID]),
    CONSTRAINT [FK_EXTRA_HOLIDAYS_TEACHER_INFO] FOREIGN KEY ([STAFF_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

