CREATE TABLE [dbo].[FEE_MULTIPLE_RECEIVED_AMOUNT] (
    [MULTI_RECEIVE_ID]           NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [MULTI_RECEIVE_HD_ID]        NUMERIC (18)    NULL,
    [MULTI_RECEIVE_BR_ID]        NUMERIC (18)    NULL,
    [MULTI_RECEIVE_DATE_RECEIVE] DATE            NULL,
    [MULTI_RECEIVE_COA_ACCOUNT]  NVARCHAR (50)   NULL,
    [MULTI_RECEIVE_AMOUNT]       FLOAT (53)      NULL,
    [MULTI_RECEIVE_INVOICE_ID]   NUMERIC (18)    NULL,
    [MULTI_RECEIVE_VCH_MAIN_ID]  NVARCHAR (50)   NULL,
    [MULTI_RECEIVE_COMMENTS]     NVARCHAR (1000) NULL,
    CONSTRAINT [PK_FEE_MULTIPLE_RECEIVED_AMOUNT] PRIMARY KEY CLUSTERED ([MULTI_RECEIVE_ID] ASC),
    CONSTRAINT [FK_FEE_MULTIPLE_RECEIVED_AMOUNT_BR_ADMIN] FOREIGN KEY ([MULTI_RECEIVE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_FEE_MULTIPLE_RECEIVED_AMOUNT_FEE_COLLECT] FOREIGN KEY ([MULTI_RECEIVE_INVOICE_ID]) REFERENCES [dbo].[FEE_COLLECT] ([FEE_COLLECT_ID]),
    CONSTRAINT [FK_FEE_MULTIPLE_RECEIVED_AMOUNT_MAIN_HD_INFO] FOREIGN KEY ([MULTI_RECEIVE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);



