CREATE TABLE [dbo].[FEE_COLLECT_DEF] (
    [FEE_COLLECT_DEF_ID]               NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [FEE_COLLECT_DEF_PID]              NUMERIC (18)    NULL,
    [FEE_COLLECT_DEF_FEE_NAME]         NUMERIC (18)    NULL,
    [FEE_COLLECT_DEF_FEE]              FLOAT (53)      NULL,
    [FEE_COLLECT_DEF_FEE_PAID]         FLOAT (53)      NULL,
    [FEE_COLLECT_DEF_MIN]              FLOAT (53)      NULL,
    [FEE_COLLECT_DEF_MAX]              FLOAT (53)      NULL,
    [FEE_COLLECT_DEF_STATUS]           CHAR (2)        NULL,
    [FEE_COLLECT_DEF_OPERATION]        CHAR (1)        NULL,
    [FEE_COLLECT_DEF_ARREARS]          FLOAT (53)      NULL,
    [FEE_COLLECT_DEF_ARREARS_RECEIVED] FLOAT (53)      NULL,
    [FEE_COLLECT_DEF_TOTAL]            FLOAT (53)      NULL,
    [FEE_COLLECT_DEF_ROYALTY]          NUMERIC (18, 2) NULL,
    [FEE_COLLECT_DEF_ROYALTY_PAID]     NUMERIC (18, 2) NULL,
    [FEE_COLLECT_DEF_ROYALTY_PERCENT]  FLOAT (53)      NULL,
    [FEE_COLLECT_DEF_MONTHLY_FEE]      FLOAT (53)      NULL,
    CONSTRAINT [PK_FEE_COLLECT_DEF] PRIMARY KEY CLUSTERED ([FEE_COLLECT_DEF_ID] ASC),
    CONSTRAINT [FK_FEE_COLLECT_DEF_FEE_COLLECT] FOREIGN KEY ([FEE_COLLECT_DEF_PID]) REFERENCES [dbo].[FEE_COLLECT] ([FEE_COLLECT_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_FEE_COLLECT_DEF_FEE_INFO] FOREIGN KEY ([FEE_COLLECT_DEF_FEE_NAME]) REFERENCES [dbo].[FEE_INFO] ([FEE_ID])
);





