CREATE TABLE [dbo].[FEE_ADVANCE] (
    [ADV_FEE_ID]                      NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [ADV_FEE_STD_ID]                  NUMERIC (18)   NULL,
    [ADV_FEE_FROM_DATE]               DATE           NULL,
    [ADV_FEE_TO_DATE]                 DATE           NULL,
    [ADV_FEE_AMOUNT]                  FLOAT (53)     NULL,
    [ADV_FEE_AMOUNT_ADJUST]           FLOAT (53)     NULL,
    [ADV_FEE_BANK_AMOUNT_NOT_CLEARED] FLOAT (53)     NULL,
    [ADV_FEE_COLLECT_ID]              NUMERIC (18)   NULL,
    [ADV_FEE_DESCRIPTION]             NVARCHAR (100) NULL,
    [ADV_FEE_DATE]                    DATE           NULL,
    [ADV_FEE_STATUS]                  CHAR (2)       NULL,
    CONSTRAINT [PK_ADVANCE_FEE] PRIMARY KEY CLUSTERED ([ADV_FEE_ID] ASC),
    CONSTRAINT [FK_FEE_ADVANCE_FEE_COLLECT] FOREIGN KEY ([ADV_FEE_COLLECT_ID]) REFERENCES [dbo].[FEE_COLLECT] ([FEE_COLLECT_ID]),
    CONSTRAINT [FK_FEE_ADVANCE_STUDENT_INFO] FOREIGN KEY ([ADV_FEE_STD_ID]) REFERENCES [dbo].[STUDENT_INFO] ([STDNT_ID])
);

