CREATE TABLE [dbo].[FEE_REMARKS_FAMILY_HISTORY] (
    [FEE_REMARKS_ID]         NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [FEE_REMARKS_STD_ID]     NUMERIC (18)   NULL,
    [FEE_REMARKS_SESSION_ID] NUMERIC (18)   NULL,
    [FEE_REMARKS]            NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_FEE_REMARKS_FAMILY_HISTORY] PRIMARY KEY CLUSTERED ([FEE_REMARKS_ID] ASC)
);

