CREATE TABLE [dbo].[FEE_SETTING] (
    [FEE_SETTING_ID]                    NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [FEE_SETTING_HD_ID]                 NUMERIC (18)   NULL,
    [FEE_SETTING_BR_ID]                 NUMERIC (18)   NULL,
    [FEE_SETTING_FINE]                  INT            NULL,
    [FEE_SETTING_REPRINT_CHARGES]       FLOAT (53)     NULL,
    [FEE_SETTING_FEE_CRITERIA]          INT            NULL,
    [BR_ADM_FEE_HISTORY]                BIT            NULL,
    [FEE_SETTING_REPRINT_HISTORY]       BIT            NULL,
    [FEE_SETTING_ARREARS_WITH_DUE_DATE] BIT            NULL,
    [FEE_SETTING_INVOICE_MOBILE_NO]     NVARCHAR (100) NULL,
    CONSTRAINT [FK_FEE_SETTING_BR_ADMIN] FOREIGN KEY ([FEE_SETTING_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_FEE_SETTING_MAIN_HD_INFO] FOREIGN KEY ([FEE_SETTING_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

