CREATE TABLE [dbo].[FEE_REMINDERS] (
    [FEE_REMIDNERS_ID]    NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [FEE_REMIDNERS_HD_ID] NUMERIC (18)   NULL,
    [FEE_REMIDNERS_BR_ID] NUMERIC (18)   NULL,
    [FINAL_FEE_REMINDERS] NVARCHAR (MAX) NULL,
    [FEE_REMINDERS]       NVARCHAR (MAX) NULL,
    [WITHDRAWL_NOTICE]    NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_FEE_REMINDERS] PRIMARY KEY CLUSTERED ([FEE_REMIDNERS_ID] ASC),
    CONSTRAINT [FK_FEE_REMINDERS_BR_ADMIN] FOREIGN KEY ([FEE_REMIDNERS_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_FEE_REMINDERS_MAIN_HD_INFO] FOREIGN KEY ([FEE_REMIDNERS_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

