CREATE TABLE [dbo].[GRADE_INFO] (
    [GRADE_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [GRADE_HD_ID]  NUMERIC (18)   NOT NULL,
    [GRADE_BR_ID]  NUMERIC (18)   NULL,
    [GRADE_NAME]   NVARCHAR (50)  NULL,
    [GRADE_DESC]   NVARCHAR (500) NULL,
    [GRADE_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_GRADE] PRIMARY KEY CLUSTERED ([GRADE_ID] ASC),
    CONSTRAINT [FK_GRADE_INFO_BR_ADMIN] FOREIGN KEY ([GRADE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_GRADE_INFO_MAIN_HD_INFO] FOREIGN KEY ([GRADE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

