CREATE TABLE [dbo].[HOUSES_INFO] (
    [HOUSES_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [HOUSES_HD_ID]  NUMERIC (18)   NOT NULL,
    [HOUSES_BR_ID]  NUMERIC (18)   NULL,
    [HOUSES_NAME]   NVARCHAR (50)  NULL,
    [HOUSES_DESC]   NVARCHAR (500) NULL,
    [HOUSES_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_HOUSES] PRIMARY KEY CLUSTERED ([HOUSES_ID] ASC),
    CONSTRAINT [FK_HOUSES_INFO_BR_ADMIN] FOREIGN KEY ([HOUSES_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_HOUSES_INFO_MAIN_HD_INFO] FOREIGN KEY ([HOUSES_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

