CREATE TABLE [dbo].[INSTITUTION_LEVEL_INFO] (
    [INST_LEVEL_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [INST_LEVEL_HD_ID]  NUMERIC (18)   NOT NULL,
    [INST_LEVEL_BR_ID]  NUMERIC (18)   NULL,
    [INST_LEVEL_NAME]   NVARCHAR (50)  NULL,
    [INST_LEVEL_DESC]   NVARCHAR (500) NULL,
    [INST_LEVEL_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_INSTITUTION_LEVEL_INFORMATION] PRIMARY KEY CLUSTERED ([INST_LEVEL_ID] ASC),
    CONSTRAINT [FK_INSTITUTION_LEVEL_INFO_BR_ADMIN] FOREIGN KEY ([INST_LEVEL_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_INSTITUTION_LEVEL_INFO_MAIN_HD_INFO] FOREIGN KEY ([INST_LEVEL_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

