CREATE TABLE [dbo].[LEAVES_RECORD] (
    [LEAVES_RECORD_ID]               NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [LEAVES_RECORD_HD_ID]            NUMERIC (18)   NULL,
    [LEAVES_RECORD_BR_ID]            NUMERIC (18)   NULL,
    [LEAVES_RECORD_STAFF_ID]         NUMERIC (18)   NULL,
    [LEAVES_RECORD_FROM_DATE]        DATE           NULL,
    [LEAVES_RECORD_TO_DATE]          DATE           NULL,
    [LEAVES_RECORD_IS_CAUSAL_LEAVES] BIT            NULL,
    [LEAVES_RECORD_IS_ANNUAL_LEAVES] BIT            NULL,
    [LEAVES_RECORD_REASON]           NVARCHAR (500) NULL,
    CONSTRAINT [PK_LEAVES_RECORD] PRIMARY KEY CLUSTERED ([LEAVES_RECORD_ID] ASC),
    CONSTRAINT [FK_LEAVES_RECORD_BR_ADMIN] FOREIGN KEY ([LEAVES_RECORD_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_LEAVES_RECORD_MAIN_HD_INFO] FOREIGN KEY ([LEAVES_RECORD_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

