CREATE TABLE [dbo].[LEVELS] (
    [LEVEL_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [LEVEL_NAME]        NVARCHAR (50)  NULL,
    [LEVEL_LEVEL]       INT            NULL,
    [LEVEL_DESCRIPTION] NVARCHAR (100) NULL,
    [LEVEL_STATUS]      CHAR (2)       NULL,
    CONSTRAINT [PK_LEVELS] PRIMARY KEY CLUSTERED ([LEVEL_ID] ASC)
);

