CREATE TABLE [dbo].[LOG_HISTORY] (
    [LOG_ID]         NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [LOG_HD_ID]      NUMERIC (18)   NOT NULL,
    [LOG_BR_ID]      NUMERIC (18)   NULL,
    [LOG_USER_ID]    NUMERIC (18)   NOT NULL,
    [LOG_EVENT_NAME] NVARCHAR (50)  NULL,
    [LOG_TIME]       DATETIME       NULL,
    [LOG_PAGE]       NVARCHAR (50)  NULL,
    [LOG_DESC]       NVARCHAR (500) NULL,
    [LOG_STATUS]     CHAR (2)       NULL,
    CONSTRAINT [PK_LOG_HISTORY] PRIMARY KEY CLUSTERED ([LOG_ID] ASC)
);

