CREATE TABLE [dbo].[MANUAL_SALARY] (
    [MANUAL_SALARY_ID]                 NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [MANUAL_SALARY_HD_ID]              NUMERIC (18) NULL,
    [MANUAL_SALARY_BR_ID]              NUMERIC (18) NULL,
    [MANUL_SALARY_MONTH_YEAR]          DATE         NULL,
    [MANUAL_SALARY_STAFF_ID]           NUMERIC (18) NULL,
    [MANUAL_SALARY_DEDUCT_DAYS]        FLOAT (53)   NULL,
    [MANUAL_SALARY_ACTUAL_DEDUCT_DAYS] FLOAT (53)   NULL,
    CONSTRAINT [PK_MANUAL_SALARY] PRIMARY KEY CLUSTERED ([MANUAL_SALARY_ID] ASC)
);

