CREATE TABLE [dbo].[MARKET_TRACKING_DEF] (
    [TRACK_DEF_ID]                         NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [TRACK_DEF_PID]                        NUMERIC (18)   NULL,
    [TRACK_DEF_MEETING_DATE]               DATETIME       NULL,
    [TRACK_DEF_MEETING_PERSON]             NVARCHAR (100) NULL,
    [TRACK_DEF_COMMENTS_BY_CLIENT]         NVARCHAR (300) NULL,
    [TRACK_DEF_COMMENTS_BY_MARKETIG_AGENT] NVARCHAR (300) NULL,
    [TRACK_DEF_NEXT_SCHEDULE_MEETING]      DATETIME       NULL,
    CONSTRAINT [PK_MARKET_TRACKING_DEF] PRIMARY KEY CLUSTERED ([TRACK_DEF_ID] ASC)
);

