CREATE TABLE [dbo].[MARKETING_STATUS] (
    [MARK_STATUS_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [MARK_STATUS_HD_ID]       NUMERIC (18)   NULL,
    [MARK_STATUS_BR_ID]       NUMERIC (18)   NULL,
    [MARK_STATUS_NAME]        NVARCHAR (50)  NULL,
    [MARK_STATUS_DESCRIPTION] NVARCHAR (300) NULL,
    [MARK_STATUS]             CHAR (2)       NULL,
    CONSTRAINT [PK_MARKETING_STATUS] PRIMARY KEY CLUSTERED ([MARK_STATUS_ID] ASC),
    CONSTRAINT [FK_MARKETING_STATUS_BR_ADMIN] FOREIGN KEY ([MARK_STATUS_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_MARKETING_STATUS_MAIN_HD_INFO] FOREIGN KEY ([MARK_STATUS_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

