CREATE TABLE [dbo].[MARKETING_MODE_INFO] (
    [MODE_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [MODE_HD_ID]       NUMERIC (18)   NULL,
    [MODE_BR_ID]       NUMERIC (18)   NULL,
    [MODE_NAME]        NVARCHAR (50)  NULL,
    [MODE_DESCRIPTION] NVARCHAR (200) NULL,
    [MODE_STATUS]      CHAR (2)       NULL,
    CONSTRAINT [PK_MARKETING_MODE_INFO] PRIMARY KEY CLUSTERED ([MODE_ID] ASC),
    CONSTRAINT [FK_MARKETING_MODE_INFO_BR_ADMIN] FOREIGN KEY ([MODE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_MARKETING_MODE_INFO_MAIN_HD_INFO] FOREIGN KEY ([MODE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

