CREATE TABLE [dbo].[MESSAGE_INFO] (
    [MSG_ID]       NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [MSG_HD_ID]    NUMERIC (18)   NOT NULL,
    [MSG_BR_ID]    NUMERIC (18)   NOT NULL,
    [MSG_NAME]     NVARCHAR (10)  NULL,
    [MSG_ENG_DESC] NVARCHAR (500) NULL,
    [MSG_STATUS]   CHAR (2)       NULL,
    CONSTRAINT [PK_MESSAGE_INFO] PRIMARY KEY CLUSTERED ([MSG_ID] ASC),
    CONSTRAINT [FK_MESSAGE_INFO_BR_ADMIN] FOREIGN KEY ([MSG_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_MESSAGE_INFO_MAIN_HD_INFO] FOREIGN KEY ([MSG_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

