CREATE TABLE [dbo].[MonthlyFees] (
    [Id]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [FeeId]               NUMERIC (18)   NULL,
    [StdId]               NUMERIC (18)   NULL,
    [Name]                NVARCHAR (100) NULL,
    [StdNo]               NUMERIC (18)   NULL,
    [Class]               NVARCHAR (100) NULL,
    [FromDate]            DATE           NULL,
    [ToDate]              DATE           NULL,
    [Month]               NVARCHAR (100) NULL,
    [TotalFee]            FLOAT (53)     NULL,
    [Paid]                FLOAT (53)     NULL,
    [Arrears]             FLOAT (53)     NULL,
    [ArrearsReceived]     FLOAT (53)     NULL,
    [TermFee]             FLOAT (53)     NULL,
    [TermFeePaid]         FLOAT (53)     NULL,
    [PlanFee]             FLOAT (53)     NULL,
    [TwoMonthPlanFee]     FLOAT (53)     NULL,
    [OldFeeStatus]        NVARCHAR (50)  NULL,
    [CurrentFeeStatus]    NVARCHAR (50)  NULL,
    [CurrentFeePaid]      FLOAT (53)     NULL,
    [Status]              CHAR (1)       NULL,
    [ClassOrder]          INT            NULL,
    [BrId]                NUMERIC (18)   NULL,
    [ClassId]             NUMERIC (18)   NULL,
    [DefClass]            NVARCHAR (50)  NULL,
    [DefClassId]          NUMERIC (18)   NULL,
    [PlanFeeLess]         FLOAT (53)     NULL,
    [PlanFeeLessTwoMonth] FLOAT (53)     NULL,
    [Remaining]           FLOAT (53)     NULL,
    CONSTRAINT [PK_MonthltFees] PRIMARY KEY CLUSTERED ([Id] ASC)
);

