CREATE TABLE [dbo].[OVETIME_ADVANCE] (
    [OVRTM_ADV_ID]            NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [OVRTM_ADV_HD_ID]         NUMERIC (18)  NULL,
    [OVRTM_ADV_BR_ID]         NUMERIC (18)  NULL,
    [OVRTM_ADV_STAFF_ID]      NUMERIC (18)  NULL,
    [OVRTM_ADV_AMOUNT]        FLOAT (53)    NULL,
    [OVRTM_ADV_DATE]          DATE          NULL,
    [OVRTM_ADV_ADJUST_AMOUNT] FLOAT (53)    NULL,
    [OVRTM_ADV_ADJUST_DATE]   DATE          NULL,
    [OVRTM_ADV_ENTERED_DATE]  DATETIME      NULL,
    [OVRTM_ADV_USER]          NVARCHAR (50) NULL,
    [OVRTM_ADV_STATUS]        CHAR (1)      NULL,
    CONSTRAINT [PK_OVETIME_ADVANCE] PRIMARY KEY CLUSTERED ([OVRTM_ADV_ID] ASC),
    CONSTRAINT [FK_OVETIME_ADVANCE_BR_ADMIN] FOREIGN KEY ([OVRTM_ADV_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_OVETIME_ADVANCE_MAIN_HD_INFO] FOREIGN KEY ([OVRTM_ADV_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

