CREATE TABLE [dbo].[PAGE_RANK] (
    [PG_RANK_ID]          NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [PG_RANK_HD_ID]       NUMERIC (18)  NULL,
    [PG_RANK_BR_ID]       NUMERIC (18)  NULL,
    [PG_RANK_USER_ID]     NUMERIC (18)  NULL,
    [PG_RANK_USER_TYPE]   NVARCHAR (50) NULL,
    [PG_RANK_PAGE_NAME]   NVARCHAR (50) NULL,
    [PG_RANK_PAGE_VIEWED] NUMERIC (18)  NULL,
    [PG_RANK_STATUS]      CHAR (2)      NULL,
    CONSTRAINT [PK_PAGE_RANK] PRIMARY KEY CLUSTERED ([PG_RANK_ID] ASC),
    CONSTRAINT [FK_PAGE_RANK_BR_ADMIN] FOREIGN KEY ([PG_RANK_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_PAGE_RANK_MAIN_HD_INFO] FOREIGN KEY ([PG_RANK_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

