CREATE TABLE [dbo].[PATH_INFO] (
    [PATH_ID]      INT            IDENTITY (1, 1) NOT NULL,
    [PATH_STD_IMG] NVARCHAR (200) NULL,
    [PATH_PAR_IMG] NVARCHAR (200) NULL,
    [PATH_TEC_IMG] NVARCHAR (200) NULL,
    [PATH_HD_IMG]  NVARCHAR (200) NULL,
    [PATH_SA_IMG]  NVARCHAR (200) NULL,
    [PATH_BR_IMG]  NVARCHAR (200) NULL,
    [PATH_ADM_IMG] NVARCHAR (200) NULL,
    [PATH_STD_DOC] NVARCHAR (200) NULL,
    [PATH_STATUS]  NCHAR (1)      NOT NULL,
    CONSTRAINT [PK_PATH_INFO_1] PRIMARY KEY CLUSTERED ([PATH_ID] ASC)
);

