CREATE TABLE [dbo].[PEOPLE_RELATIONS_INFO] (
    [PEOPLE_RELATIONS_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [PEOPLE_RELATIONS_HD_ID]  NUMERIC (18)   NOT NULL,
    [PEOPLE_RELATIONS_BR_ID]  NUMERIC (18)   NULL,
    [PEOPLE_RELATIONS_NAME]   NVARCHAR (50)  NULL,
    [PEOPLE_RELATIONS_DESC]   NVARCHAR (MAX) NOT NULL,
    [PEOPLE_RELATIONS_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_PEOPLE_RELATIONS] PRIMARY KEY CLUSTERED ([PEOPLE_RELATIONS_ID] ASC),
    CONSTRAINT [FK_PEOPLE_RELATIONS_INFO_BR_ADMIN] FOREIGN KEY ([PEOPLE_RELATIONS_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_PEOPLE_RELATIONS_INFO_MAIN_HD_INFO] FOREIGN KEY ([PEOPLE_RELATIONS_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

