CREATE TABLE [dbo].[PLAN_ASSESSMENT] (
    [PLAN_ASSESSMENT_ID]        NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [PLAN_ASSESSMENT_PID]       NUMERIC (18) NULL,
    [PLAN_ASSESSMENT_INFO_ID]   NUMERIC (18) NULL,
    [PLAN_ASSESSMENT_TERM_ID]   NUMERIC (18) NULL,
    [PLAN_ASSESSMENT_TOTAL]     FLOAT (53)   NULL,
    [PLAN_ASSESSMENT_PASS_%AGE] FLOAT (53)   NULL,
    [PLAN_ASSESSMENT_STATUS]    CHAR (10)    NULL,
    CONSTRAINT [PK_PLAN_ASSESSMENT] PRIMARY KEY CLUSTERED ([PLAN_ASSESSMENT_ID] ASC),
    CONSTRAINT [FK_PLAN_ASSESSMENT_ASSESSMENT_INFO] FOREIGN KEY ([PLAN_ASSESSMENT_INFO_ID]) REFERENCES [dbo].[ASSESSMENT_INFO] ([ASSESSMENT_ID]),
    CONSTRAINT [FK_PLAN_ASSESSMENT_EXAM] FOREIGN KEY ([PLAN_ASSESSMENT_PID]) REFERENCES [dbo].[EXAM] ([EXAM_ID])
);

