CREATE TABLE [dbo].[PLAN_FEE_DEF] (
    [PLAN_FEE_DEF_ID]       NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [PLAN_FEE_DEF_PLAN_ID]  NUMERIC (18) NULL,
    [PLAN_FEE_DEF_FEE_NAME] NUMERIC (18) NULL,
    [PLAN_FEE_DEF_FEE]      FLOAT (53)   NULL,
    [PLAN_FEE_DEF_FEE_MIN]  FLOAT (53)   NULL,
    [PLAN_FEE_DEF_FEE_MAX]  FLOAT (53)   NULL,
    [PLAN_FEE_DEF_STATUS]   NCHAR (2)    NULL,
    [PLAN_FEE_OPERATION]    CHAR (1)     NULL,
    [PLAN_FEE_IS_ONCE_PAID] CHAR (1)     NULL,
    CONSTRAINT [PK_PLAN_FEE_DEF] PRIMARY KEY CLUSTERED ([PLAN_FEE_DEF_ID] ASC),
    CONSTRAINT [FK_PLAN_FEE_DEF_FEE_INFO] FOREIGN KEY ([PLAN_FEE_DEF_FEE_NAME]) REFERENCES [dbo].[FEE_INFO] ([FEE_ID]),
    CONSTRAINT [FK_PLAN_FEE_DEF_PLAN_FEE] FOREIGN KEY ([PLAN_FEE_DEF_PLAN_ID]) REFERENCES [dbo].[PLAN_FEE] ([PLAN_FEE_ID])
);

