CREATE TABLE [dbo].[PLAN_FEE] (
    [PLAN_FEE_ID]               NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [PLAN_FEE_HD_ID]            NUMERIC (18)   NULL,
    [PLAN_FEE_BR_ID]            NUMERIC (18)   NULL,
    [PLAN_FEE_NAME]             NVARCHAR (50)  NULL,
    [PLAN_FEE_TOTAL_FEE]        FLOAT (53)     NULL,
    [PLAN_FEE_STATUS]           CHAR (2)       NULL,
    [PLAN_FEE_FORMULA]          FLOAT (53)     NULL,
    [PLAN_FEE_IS_FORMULA_APPLY] BIT            NULL,
    [PLAN_FEE_IS_FEE_GENERATE]  BIT            NULL,
    [PLAN_FEE_NOTES]            NVARCHAR (MAX) NULL,
    [PLAN_FEE_INSTALLMENT_ID]   NUMERIC (18)   NULL,
    [PLAN_FEE_YEARLY_PLAN_ID]   NUMERIC (18)   NULL,
    CONSTRAINT [PK_PLAN_FEE] PRIMARY KEY CLUSTERED ([PLAN_FEE_ID] ASC),
    CONSTRAINT [FK_PLAN_FEE_BR_ADMIN] FOREIGN KEY ([PLAN_FEE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_PLAN_FEE_INSTALLMENT_INFO] FOREIGN KEY ([PLAN_FEE_INSTALLMENT_ID]) REFERENCES [dbo].[INSTALLMENT_INFO] ([INSTALLMENT_ID]),
    CONSTRAINT [FK_PLAN_FEE_MAIN_HD_INFO] FOREIGN KEY ([PLAN_FEE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);



