CREATE TABLE [dbo].[PLAN_GRADE_DEF] (
    [DEF_GRADE_ID]           NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [DEF_P_ID]               NUMERIC (18)   NOT NULL,
    [DEF_GRADE_MIN_LIMIT]    FLOAT (53)     NULL,
    [DEF_GRADE_MIN_OPERATOR] NVARCHAR (50)  NULL,
    [DEF_GRADE_MAX_LIMIT]    FLOAT (53)     NULL,
    [DEF_GRADE_MAX_OPERATOR] NVARCHAR (50)  NULL,
    [DEF_GRADE_INFO_ID]      NUMERIC (18)   NULL,
    [DEF_GRADE_DESCRIPTION]  NVARCHAR (300) NULL,
    [DEF_GRADE_STATUS]       CHAR (2)       NULL,
    [DEF_GRADE_POINTS]       FLOAT (53)     NULL,
    CONSTRAINT [PK_PLAN_GRADE] PRIMARY KEY CLUSTERED ([DEF_GRADE_ID] ASC),
    CONSTRAINT [FK_PLAN_GRADE_DEF_GRADE_INFO] FOREIGN KEY ([DEF_GRADE_INFO_ID]) REFERENCES [dbo].[GRADE_INFO] ([GRADE_ID]),
    CONSTRAINT [FK_PLAN_GRADE_DEF_PLAN_GRADE] FOREIGN KEY ([DEF_P_ID]) REFERENCES [dbo].[PLAN_GRADE] ([P_GRADE_ID])
);

