CREATE TABLE [dbo].[PLAN_GRADE] (
    [P_GRADE_ID]                   NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [P_GRADE_HD_ID]                NUMERIC (18)  NOT NULL,
    [P_GRADE_BR_ID]                NUMERIC (18)  NOT NULL,
    [P_GRADE_PLAN_NAME]            NVARCHAR (50) NULL,
    [P_GRADE_STATUS]               CHAR (2)      NULL,
    [P_GRADE_SESSION_START_DATE]   DATE          NULL,
    [P_GRADE_SESSION_END_DATE]     DATE          NULL,
    [P_GRADE_SUBJECT_AWRADS_MARKS] FLOAT (53)    NULL,
    CONSTRAINT [PK_PLAN_GRADE_1] PRIMARY KEY CLUSTERED ([P_GRADE_ID] ASC),
    CONSTRAINT [FK_PLAN_GRADE_BR_ADMIN] FOREIGN KEY ([P_GRADE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_PLAN_GRADE_MAIN_HD_INFO] FOREIGN KEY ([P_GRADE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

