CREATE TABLE [dbo].[RELIGION_INFO] (
    [RELIGION_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [RELIGION_HD_ID]  NUMERIC (18)   NOT NULL,
    [RELIGION_BR_ID]  NUMERIC (18)   NULL,
    [RELIGION_NAME]   NVARCHAR (50)  NULL,
    [RELIGION_DESC]   NVARCHAR (500) NULL,
    [RELIGION_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_RELIGION] PRIMARY KEY CLUSTERED ([RELIGION_ID] ASC),
    CONSTRAINT [FK_RELIGION_INFO_BR_ADMIN] FOREIGN KEY ([RELIGION_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_RELIGION_INFO_MAIN_HD_INFO] FOREIGN KEY ([RELIGION_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

