CREATE TABLE [dbo].[REPORT_SETTING] (
    [REPORT_SETTING_ID]           NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [REPORT_SETTING_HD_ID]        NUMERIC (18)  NULL,
    [REPORT_SETTING_BR_ID]        NUMERIC (18)  NULL,
    [REPORT_SETTING_REPORT_NAME]  NVARCHAR (50) NULL,
    [REPORT_SETTING_REPORT_VALUE] NVARCHAR (50) NULL,
    [REPORT_SETTING_STATUS]       CHAR (2)      NULL,
    CONSTRAINT [PK_REPORT_SETTING] PRIMARY KEY CLUSTERED ([REPORT_SETTING_ID] ASC),
    CONSTRAINT [FK_REPORT_SETTING_BR_ADMIN] FOREIGN KEY ([REPORT_SETTING_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_REPORT_SETTING_MAIN_HD_INFO] FOREIGN KEY ([REPORT_SETTING_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

