CREATE TABLE [dbo].[RIGHTS_PACKAGES_PARENT] (
    [PACKAGES_ID]    NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [PACKAGES_HD_ID] NUMERIC (18)   NULL,
    [PACKAGES_BR_ID] NUMERIC (18)   NULL,
    [PACKAGES_NAME]  NVARCHAR (100) NULL,
    [PACKAGES_TYPE]  NUMERIC (18)   NULL,
    CONSTRAINT [PK_RIGHTS_PACKAGES] PRIMARY KEY CLUSTERED ([PACKAGES_ID] ASC),
    CONSTRAINT [FK_RIGHTS_PACKAGES_PARENT_BR_ADMIN] FOREIGN KEY ([PACKAGES_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_RIGHTS_PACKAGES_PARENT_MAIN_HD_INFO] FOREIGN KEY ([PACKAGES_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

