CREATE TABLE [dbo].[RIGHTS_PAGES] (
    [RIGHTS_PAGES_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [RIGHTS_PAGES_NAME]        NVARCHAR (150) NULL,
    [RIGHTS_PAGES_TEXT]        NVARCHAR (150) NULL,
    [RIGHTS_PAGES_PARENT_CODE] NVARCHAR (150) NULL,
    [RIGHTS_PAGES_CHILD_CODE]  NVARCHAR (150) NULL,
    [RIGHTS_PAGES_URL]         NVARCHAR (250) NULL,
    [RIGHTS_PAGES_COLOR]       NVARCHAR (50)  NULL,
    [RIGHTS_PAGES_ICON]        NVARCHAR (50)  NULL,
    CONSTRAINT [PK_RIGHTS_PAGES] PRIMARY KEY CLUSTERED ([RIGHTS_PAGES_ID] ASC)
);

