CREATE TABLE [dbo].[RIGHTS_ALLOCATION] (
    [ALLOCATION_ID]         NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [ALLOCATION_PACKAGE_ID] NUMERIC (18) NULL,
    [ALLOCATION_LOGIN_ID]   NUMERIC (18) NULL,
    CONSTRAINT [PK_RIGHTS_ALLOCATION] PRIMARY KEY CLUSTERED ([ALLOCATION_ID] ASC),
    CONSTRAINT [FK_RIGHTS_ALLOCATION_RIGHTS_PACKAGES_PARENT] FOREIGN KEY ([ALLOCATION_PACKAGE_ID]) REFERENCES [dbo].[RIGHTS_PACKAGES_PARENT] ([PACKAGES_ID]),
    CONSTRAINT [FK_RIGHTS_ALLOCATION_USER_INFO] FOREIGN KEY ([ALLOCATION_LOGIN_ID]) REFERENCES [dbo].[USER_INFO] ([USER_ID])
);

