CREATE TABLE [dbo].[ROYALTY_TRANSACTION] (
    [ROYALTY_TRAN_ID]         NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [ROYALTY_TRAN_BR_ID]      NUMERIC (18)    NULL,
    [ROYALTY_TRAN_AMOUNT]     FLOAT (53)      NULL,
    [ROYALTY_TRAN_FROM_DATE]  DATE            NULL,
    [ROYALTY_TRAN_TO_DATE]    DATE            NULL,
    [ROYALTY_TRAN_BANK_NAME]  NVARCHAR (100)  NULL,
    [ROYALTY_TRAN_CHEQUE_NO]  NVARCHAR (100)  NULL,
    [ROYALTY_TRAN_COMMENTS]   NVARCHAR (1000) NULL,
    [ROYALTY_TRAN_CREATED_BY] NVARCHAR (50)   NULL,
    [ROYALTY_TRAN_DATETIME]   DATETIME        NULL,
    CONSTRAINT [PK_ROYALTY_TRANSACTION] PRIMARY KEY CLUSTERED ([ROYALTY_TRAN_ID] ASC),
    CONSTRAINT [FK_ROYALTY_TRANSACTION_BR_ADMIN] FOREIGN KEY ([ROYALTY_TRAN_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID])
);

