CREATE TABLE [dbo].[SALARY_HOLD] (
    [ID]           NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [HD_ID]        NUMERIC (18)   NULL,
    [BR_ID]        NUMERIC (18)   NULL,
    [DATE]         DATE           NULL,
    [EMPLOYEE_IDS] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_SALARY_HOLD] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SALARY_HOLD_BR_ADMIN] FOREIGN KEY ([BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SALARY_HOLD_MAIN_HD_INFO] FOREIGN KEY ([HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

