CREATE TABLE [dbo].[SALES_REPRESENTATIVE_INFO] (
    [SALES_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SALES_HD_ID]       NUMERIC (18)   NULL,
    [SALES_BR_ID]       NUMERIC (18)   NULL,
    [SALES_NAME]        NVARCHAR (50)  NULL,
    [SALES_DESCRIPTION] NVARCHAR (200) NULL,
    [SALES_STATUS]      CHAR (2)       NULL,
    CONSTRAINT [PK_SALES_REPRESENTATIVE_INFO] PRIMARY KEY CLUSTERED ([SALES_ID] ASC),
    CONSTRAINT [FK_SALES_REPRESENTATIVE_INFO_BR_ADMIN] FOREIGN KEY ([SALES_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SALES_REPRESENTATIVE_INFO_MAIN_HD_INFO] FOREIGN KEY ([SALES_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

