CREATE TABLE [dbo].[SCHOLARSHIP_WITHDRAWL_DEF] (
    [SCH_DRAW_DEF_ID]       NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [SCH_DRAW_DEF_PID]      NUMERIC (18) NULL,
    [SCH_DRAW_DEF_FROM_GPA] FLOAT (53)   NULL,
    [SCH_DRAW_DEF_TO_GPA]   FLOAT (53)   NULL,
    [SCH_DRAW_DEF_PERCENT]  FLOAT (53)   NULL,
    CONSTRAINT [PK_SCHOLARSHIP_WITHDRAWL_DEF] PRIMARY KEY CLUSTERED ([SCH_DRAW_DEF_ID] ASC),
    CONSTRAINT [FK_SCHOLARSHIP_WITHDRAWL_DEF_SCHOLARSHIP_WITHDRAWL] FOREIGN KEY ([SCH_DRAW_DEF_PID]) REFERENCES [dbo].[SCHOLARSHIP_WITHDRAWL] ([SCH_DRAW_ID])
);

