CREATE TABLE [dbo].[SCHOLARSHIP_WITHDRAWL] (
    [SCH_DRAW_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SCH_DRAW_HD_ID]  NUMERIC (18)   NULL,
    [SCH_DRAW_BR_ID]  NUMERIC (18)   NULL,
    [SCH_DRAW_NAME]   NVARCHAR (100) NULL,
    [SCH_DRAW_STATUS] CHAR (1)       NULL,
    CONSTRAINT [PK_SCHOLARSHIP_WITHDRAWL] PRIMARY KEY CLUSTERED ([SCH_DRAW_ID] ASC),
    CONSTRAINT [FK_SCHOLARSHIP_WITHDRAWL_BR_ADMIN] FOREIGN KEY ([SCH_DRAW_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SCHOLARSHIP_WITHDRAWL_MAIN_HD_INFO] FOREIGN KEY ([SCH_DRAW_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

