CREATE TABLE [dbo].[SCHOOL_PLANE_DEFINITION] (
    [DEF_ID]            NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [DEF_CLASS_ID]      NUMERIC (18)  NULL,
    [DEF_SUBJECT]       NUMERIC (18)  NULL,
    [DEF_TEACHER]       NUMERIC (18)  NULL,
    [DEF_TERM]          NUMERIC (18)  NULL,
    [DEF_START_TIME]    NVARCHAR (50) NULL,
    [DEF_END_TIME]      NVARCHAR (50) NULL,
    [DEF_STATUS]        CHAR (2)      NULL,
    [DEF_IS_COMPULSORY] BIT           NULL,
    CONSTRAINT [PK_SCHOOL_PLANE_DEFINITION] PRIMARY KEY CLUSTERED ([DEF_ID] ASC),
    CONSTRAINT [FK_SCHOOL_PLANE_DEFINITION_SCHOOL_PLANE] FOREIGN KEY ([DEF_CLASS_ID]) REFERENCES [dbo].[SCHOOL_PLANE] ([CLASS_ID]),
    CONSTRAINT [FK_SCHOOL_PLANE_DEFINITION_SUBJECT_INFO] FOREIGN KEY ([DEF_SUBJECT]) REFERENCES [dbo].[SUBJECT_INFO] ([SUB_ID]),
    CONSTRAINT [FK_SCHOOL_PLANE_DEFINITION_TEACHER_INFO] FOREIGN KEY ([DEF_TEACHER]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID]),
    CONSTRAINT [FK_SCHOOL_PLANE_DEFINITION_TERM_INFO] FOREIGN KEY ([DEF_TERM]) REFERENCES [dbo].[TERM_INFO] ([TERM_ID])
);

