CREATE TABLE [dbo].[SECTION_INFO] (
    [SECT_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SECT_HD_ID]  NUMERIC (18)   NOT NULL,
    [SECT_BR_ID]  NUMERIC (18)   NULL,
    [SECT_NAME]   NVARCHAR (50)  NULL,
    [SECT_DESC]   NVARCHAR (500) NULL,
    [SECT_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_SECTION_INFO] PRIMARY KEY CLUSTERED ([SECT_ID] ASC),
    CONSTRAINT [FK_SECTION_INFO_BR_ADMIN] FOREIGN KEY ([SECT_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SECTION_INFO_MAIN_HD_INFO] FOREIGN KEY ([SECT_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

