CREATE TABLE [dbo].[SETTINGS] (
    [ID]    NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [HD_ID] NUMERIC (18)   NULL,
    [BR_ID] NUMERIC (18)   NULL,
    [Name]  NVARCHAR (100) NULL,
    [Value] NVARCHAR (500) NULL,
    CONSTRAINT [PK_SETTINGS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SETTINGS_BR_ADMIN] FOREIGN KEY ([BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SETTINGS_MAIN_HD_INFO] FOREIGN KEY ([HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

