CREATE TABLE [dbo].[SHIFT_INFO] (
    [SHFT_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SHFT_HD_ID]  NUMERIC (18)   NOT NULL,
    [SHFT_BR_ID]  NUMERIC (18)   NULL,
    [SHFT_NAME]   NVARCHAR (50)  NULL,
    [SHFT_DESC]   NVARCHAR (500) NULL,
    [SHFT_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_SHIFT_INFO] PRIMARY KEY CLUSTERED ([SHFT_ID] ASC),
    CONSTRAINT [FK_SHIFT_INFO_BR_ADMIN] FOREIGN KEY ([SHFT_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SHIFT_INFO_MAIN_HD_INFO] FOREIGN KEY ([SHFT_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

