CREATE TABLE [dbo].[SHORT_LEAVE] (
    [SHORT_LEAVE_ID]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SHORT_LEAVE_HD_ID]     NUMERIC (18)   NULL,
    [SHORT_LEAVE_BR_ID]     NUMERIC (18)   NULL,
    [SHORT_LEAVE_STAFF_ID]  NUMERIC (18)   NULL,
    [SHORT_LEAVE_DATE]      DATE           NULL,
    [SHORT_LEAVE_FROM_TIME] NVARCHAR (100) NULL,
    [SHORT_LEAVE_TO_TIME]   NVARCHAR (100) NULL,
    [SHORT_LEAVE_REASON]    NVARCHAR (100) NULL,
    [SHORT_LEAVE_STATUS]    CHAR (2)       NULL,
    [SHORT_LEAVE_IS_ANNUAL] BIT            NULL,
    CONSTRAINT [PK_SHORT_LEAVE] PRIMARY KEY CLUSTERED ([SHORT_LEAVE_ID] ASC),
    CONSTRAINT [FK_SHORT_LEAVE_BR_ADMIN] FOREIGN KEY ([SHORT_LEAVE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SHORT_LEAVE_MAIN_HD_INFO] FOREIGN KEY ([SHORT_LEAVE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_SHORT_LEAVE_TEACHER_INFO] FOREIGN KEY ([SHORT_LEAVE_STAFF_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

