CREATE TABLE [dbo].[SMS_SCREEN] (
    [SMS_SCREEN_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SMS_SCREEN_HD_ID]       NUMERIC (18)   NULL,
    [SMS_SCREEN_BR_ID]       NUMERIC (18)   NULL,
    [SMS_SCREEN_NAME]        NVARCHAR (100) NULL,
    [SMS_SCREEN_INSERT]      CHAR (2)       NULL,
    [SMS_SCREEN_UPDATE]      CHAR (2)       NULL,
    [SMS_SCREEN_DELETE]      CHAR (2)       NULL,
    [SMS_SCREEN_OPEN]        CHAR (2)       NULL,
    [SMS_SCREEN_STUDENT]     CHAR (2)       NULL,
    [SMS_SCREEN_PARENTS]     CHAR (2)       NULL,
    [SMS_SCREEN_ADMIN]       CHAR (2)       NULL,
    [SMS_SCREEN_SUPER_ADMIN] CHAR (2)       NULL,
    [SMS_SCREEN_STAFF]       CHAR (2)       NULL,
    [SMS_SCREEN_DATE_TIME]   DATETIME       NULL,
    [SMS_SCREEN_STATUS]      CHAR (2)       NULL,
    [RIGHTS_PAGE_NAME]       NVARCHAR (50)  NULL,
    CONSTRAINT [PK_SMS_SCREEN] PRIMARY KEY CLUSTERED ([SMS_SCREEN_ID] ASC),
    CONSTRAINT [FK_SMS_SCREEN_BR_ADMIN] FOREIGN KEY ([SMS_SCREEN_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SMS_SCREEN_MAIN_HD_INFO] FOREIGN KEY ([SMS_SCREEN_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

