CREATE TABLE [dbo].[SMS_VARIABLES] (
    [SMS_VARIABLES_ID]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SMS_VARIABLES_HD_ID]     NUMERIC (18)   NULL,
    [SMS_VARIABLES_BR_ID]     NUMERIC (18)   NULL,
    [SMS_VARIABLES_NAME]      NVARCHAR (100) NULL,
    [SMS_VARIABLES_DATE_TIME] DATETIME       NULL,
    [SMS_VARIABLES_STATUS]    CHAR (2)       NULL,
    CONSTRAINT [PK_SMS_VARIABLES] PRIMARY KEY CLUSTERED ([SMS_VARIABLES_ID] ASC),
    CONSTRAINT [FK_SMS_VARIABLES_BR_ADMIN] FOREIGN KEY ([SMS_VARIABLES_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SMS_VARIABLES_MAIN_HD_INFO] FOREIGN KEY ([SMS_VARIABLES_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

