CREATE TABLE [dbo].[SMS_API] (
    [SMS_API_ID]         NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SMS_API_NAME]       NVARCHAR (200) NULL,
    [SMS_API_BRAND_NAME] NVARCHAR (100) NULL,
    [SMS_API_USERNAME]   NVARCHAR (100) NULL,
    [SMS_API_PASSWORD]   NVARCHAR (100) NULL,
    [SMS_API_SIGNATURE]  NVARCHAR (200) NULL,
    CONSTRAINT [PK_SMS_API] PRIMARY KEY CLUSTERED ([SMS_API_ID] ASC)
);

