CREATE TABLE [dbo].[SMS_SENT_HISTORY] (
    [SMS_SENT_HISTORY_ID]           NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SMS_SENT_HISTORY_HD_ID]        NUMERIC (18)   NULL,
    [SMS_SENT_HISTORY_BR_ID]        NUMERIC (18)   NULL,
    [SMS_SENT_HISTORY_MOBILE_NO]    NVARCHAR (100) NULL,
    [SMS_SENT_HISTORY_MESSAGE]      NVARCHAR (200) NULL,
    [SMS_SENT_HISTORY_SCREEN_ID]    NUMERIC (18)   NULL,
    [SMS_SENT_HISTORY_USER_ID]      NVARCHAR (100) NULL,
    [SMS_SENT_HISTORY_DATE_TIME]    DATETIME       NULL,
    [SMS_SENT_HISTORY_STATUS]       NVARCHAR (10)  NULL,
    [SMS_SENT_HISTORY_CLIENT_PC_ID] NUMERIC (18)   NULL,
    CONSTRAINT [PK_SMS_SENT_HISTORY] PRIMARY KEY CLUSTERED ([SMS_SENT_HISTORY_ID] ASC),
    CONSTRAINT [FK_SMS_SENT_HISTORY_BR_ADMIN] FOREIGN KEY ([SMS_SENT_HISTORY_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SMS_SENT_HISTORY_MAIN_HD_INFO] FOREIGN KEY ([SMS_SENT_HISTORY_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

