CREATE TABLE [dbo].[SMS_CONFIG] (
    [SMS_CONFIG_ID]            NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [SMS_CONFIG_HD_ID]         NUMERIC (18)  NULL,
    [SMS_CONFIG_BR_ID]         NUMERIC (18)  NULL,
    [SMS_CONFIG_AVAILABLE_SMS] NUMERIC (18)  NULL,
    [SMS_CONFIG_USER]          NVARCHAR (50) NULL,
    [SMS_CONFIG_PASSWORD]      NVARCHAR (50) NULL,
    [SMS_CONFIG_SENT_HISTORY]  CHAR (2)      NULL,
    CONSTRAINT [PK_SMS_CONFIG] PRIMARY KEY CLUSTERED ([SMS_CONFIG_ID] ASC),
    CONSTRAINT [FK_SMS_CONFIG_BR_ADMIN] FOREIGN KEY ([SMS_CONFIG_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SMS_CONFIG_MAIN_HD_INFO] FOREIGN KEY ([SMS_CONFIG_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

