CREATE TABLE [dbo].[SMS_TEMPLATE] (
    [SMS_TEMPLATE_ID]            NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SMS_TEMPLATE_HD_ID]         NUMERIC (18)   NULL,
    [SMS_TEMPLATE_BR_ID]         NUMERIC (18)   NULL,
    [SMS_TEMPLATE_SCREEN_ID]     NUMERIC (18)   NULL,
    [SMS_TEMPLATE_INSERT_MSG]    NVARCHAR (500) NULL,
    [SMS_TEMPLATE_INSERT_VAR_ID] NVARCHAR (100) NULL,
    [SMS_TEMPLATE_UPDATE_MSG]    NVARCHAR (500) NULL,
    [SMS_TEMPLATE_UPDATE_VAR_ID] NVARCHAR (100) NULL,
    [SMS_TEMPLATE_DELETE_MSG]    NVARCHAR (500) NULL,
    [SMS_TEMPLATE_DELETE_VAR_ID] NVARCHAR (100) NULL,
    [SMS_TEMPLATE_OPEN_MSG]      NVARCHAR (500) NULL,
    [SMS_TEMPLATE_OPEN_VAR_ID]   NVARCHAR (100) NULL,
    [SMS_TEMPLATE_USER]          NVARCHAR (100) NULL,
    [SMS_TEMPLATE_DATE_TIME]     DATETIME       NULL,
    [SMS_TEMPLATE_STATUS]        CHAR (2)       NULL,
    CONSTRAINT [PK_SMS_TEMPLATE] PRIMARY KEY CLUSTERED ([SMS_TEMPLATE_ID] ASC),
    CONSTRAINT [FK_SMS_TEMPLATE_BR_ADMIN] FOREIGN KEY ([SMS_TEMPLATE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SMS_TEMPLATE_MAIN_HD_INFO] FOREIGN KEY ([SMS_TEMPLATE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

