CREATE TABLE [dbo].[STAFF_LATE_TIME_DEDUCTION] (
    [DEDUCTION_ID]             NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [DEDUCTION_STAFF_ID]       NUMERIC (18)  NULL,
    [DEDUCTION_FROM_TIME]      NVARCHAR (50) NULL,
    [DEDUCTION_TO_TIME]        NVARCHAR (50) NULL,
    [DEDUCTION_PERCENT_SALARY] FLOAT (53)    NULL,
    CONSTRAINT [PK_STAFF_LATE_TIME_DEDUCTION] PRIMARY KEY CLUSTERED ([DEDUCTION_ID] ASC),
    CONSTRAINT [FK_STAFF_LATE_TIME_DEDUCTION_TEACHER_INFO] FOREIGN KEY ([DEDUCTION_STAFF_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

