CREATE TABLE [dbo].[STAFF_DEDUCTION] (
    [STAFF_DEDUCTION_ID]         NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [STAFF_DEDUCTION_HD_ID]      NUMERIC (18)   NULL,
    [STAFF_DEDUCTION_BR_ID]      NUMERIC (18)   NULL,
    [STAFF_DEDUCTION_DED_ID]     NUMERIC (18)   NULL,
    [STAFF_DEDUCTION_VAL_TYPE]   NVARCHAR (100) NULL,
    [STAFF_DEDUCTION_TYPE]       NVARCHAR (100) NULL,
    [STAFF_DEDUCTION_MONTHS]     NVARCHAR (100) NULL,
    [STAFF_DEDUCTION_PRCNT_BS]   FLOAT (53)     NULL,
    [STAFF_DEDUCTION_PRCNT_SS]   FLOAT (53)     NULL,
    [STAFF_DEDUCTION_STAFF_ID]   NUMERIC (18)   NULL,
    [STAFF_DEDUCTION_REFUNDABLE] CHAR (2)       NULL,
    [STAFF_DEDUCTION_DATE]       DATETIME       NULL,
    [STAFF_DEDUCTION_STATUS]     CHAR (2)       NULL,
    CONSTRAINT [PK_STAFF_DEDUCTION] PRIMARY KEY CLUSTERED ([STAFF_DEDUCTION_ID] ASC),
    CONSTRAINT [FK_STAFF_DEDUCTION_BR_ADMIN] FOREIGN KEY ([STAFF_DEDUCTION_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_STAFF_DEDUCTION_DEDUCTION] FOREIGN KEY ([STAFF_DEDUCTION_DED_ID]) REFERENCES [dbo].[DEDUCTION] ([DEDUCTION_ID]),
    CONSTRAINT [FK_STAFF_DEDUCTION_MAIN_HD_INFO] FOREIGN KEY ([STAFF_DEDUCTION_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_STAFF_DEDUCTION_TEACHER_INFO] FOREIGN KEY ([STAFF_DEDUCTION_STAFF_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

