CREATE TABLE [dbo].[STAFF_LOAN] (
    [STAFF_LOAN_ID]             NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [STAFF_LOAN_HD_ID]          NUMERIC (18)   NULL,
    [STAFF_LOAN_BR_ID]          NUMERIC (18)   NULL,
    [STAFF_LOAN_BASIC_SALARY]   FLOAT (53)     NULL,
    [STAFF_LOAN_AMOUNT_TYPE]    NVARCHAR (100) NULL,
    [STAFF_LOAN_AMOUNT]         FLOAT (53)     NULL,
    [STAFF_LOAN_DEDUCTION_TYPE] NVARCHAR (100) NULL,
    [STAFF_LOAN_STAFF_ID]       NUMERIC (18)   NULL,
    [STAFF_LOAN_DATE]           DATETIME       NULL,
    [STAFF_LOAN_STATUS]         CHAR (2)       NULL,
    [STAFF_LOAN_USER]           NVARCHAR (100) NULL,
    [STAFF_LOAN_INSTALLS]       NUMERIC (18)   NULL,
    CONSTRAINT [PK_STAFF_LOAN] PRIMARY KEY CLUSTERED ([STAFF_LOAN_ID] ASC),
    CONSTRAINT [FK_STAFF_LOAN_BR_ADMIN] FOREIGN KEY ([STAFF_LOAN_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_STAFF_LOAN_MAIN_HD_INFO] FOREIGN KEY ([STAFF_LOAN_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_STAFF_LOAN_TEACHER_INFO] FOREIGN KEY ([STAFF_LOAN_STAFF_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

