CREATE TABLE [dbo].[STAFF_ALLOWANCE] (
    [STAFF_ALLOWANCE_ID]       NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [STAFF_ALLOWANCE_HD_ID]    NUMERIC (18)   NULL,
    [STAFF_ALLOWANCE_BR_ID]    NUMERIC (18)   NULL,
    [STAFF_ALLOWANCE_ALLOW_ID] NUMERIC (18)   NULL,
    [STAFF_ALLOWANCE_VAL_TYPE] NVARCHAR (100) NULL,
    [STAFF_ALLOWANCE_TYPE]     NVARCHAR (100) NULL,
    [STAFF_ALLOWANCE_MONTHS]   NVARCHAR (100) NULL,
    [STAFF_ALLOWANCE_AMOUNT]   FLOAT (53)     NULL,
    [STAFF_ALLOWANCE_STAFF_ID] NUMERIC (18)   NULL,
    [STAFF_ALLOWANCE_DATE]     DATETIME       NULL,
    [STAFF_ALLOWANCE_STATUS]   CHAR (2)       NULL,
    CONSTRAINT [PK_STAFF_ALLOWANCE] PRIMARY KEY CLUSTERED ([STAFF_ALLOWANCE_ID] ASC),
    CONSTRAINT [FK_STAFF_ALLOWANCE_ALLOWANCE] FOREIGN KEY ([STAFF_ALLOWANCE_ALLOW_ID]) REFERENCES [dbo].[ALLOWANCE] ([ALLOWANCE_ID]),
    CONSTRAINT [FK_STAFF_ALLOWANCE_BR_ADMIN] FOREIGN KEY ([STAFF_ALLOWANCE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_STAFF_ALLOWANCE_MAIN_HD_INFO] FOREIGN KEY ([STAFF_ALLOWANCE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_STAFF_ALLOWANCE_TEACHER_INFO] FOREIGN KEY ([STAFF_ALLOWANCE_STAFF_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

