CREATE TABLE [dbo].[STAFF_TYPE_INFO] (
    [STAFF_TYPE_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [STAFF_TYPE_HD_ID]  NUMERIC (18)   NOT NULL,
    [STAFF_TYPE_BR_ID]  NUMERIC (18)   NULL,
    [STAFF_TYPE_NAME]   NVARCHAR (50)  NULL,
    [STAFF_TYPE_DESC]   NVARCHAR (500) NULL,
    [STAFF_TYPE_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_STAFF_TYPE] PRIMARY KEY CLUSTERED ([STAFF_TYPE_ID] ASC),
    CONSTRAINT [FK_STAFF_TYPE_INFO_BR_ADMIN] FOREIGN KEY ([STAFF_TYPE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_STAFF_TYPE_INFO_MAIN_HD_INFO] FOREIGN KEY ([STAFF_TYPE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

