CREATE TABLE [dbo].[STAFF_SALLERY_DEFF] (
    [STAFF_SALLERY_DEFF_ID]                  NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [STAFF_SALLERY_DEFF_PID]                 NUMERIC (18)  NULL,
    [STAFF_SALLERY_DEFF_NAME]                NVARCHAR (50) NULL,
    [STAFF_SALLERY_DEFF_AMOUNT]              FLOAT (53)    NULL,
    [STAFF_SALLERY_DEFF_AMOUNT_TYPE]         NVARCHAR (50) NULL,
    [STAFF_SALLERY_DEFF_AMOUNT_STATUS]       CHAR (10)     NULL,
    [STAFF_SALLERY_DEFF_SCHOOL_CONTRIBUTION] FLOAT (53)    NULL,
    [STAFF_SALLERY_DEFF_REFUND]              CHAR (1)      NULL,
    [STAFF_SALLERY_DEFF_REFUND_STATUS]       NVARCHAR (50) NULL,
    CONSTRAINT [PK_STAFF_SALLERY_DEFF] PRIMARY KEY CLUSTERED ([STAFF_SALLERY_DEFF_ID] ASC),
    CONSTRAINT [FK_STAFF_SALLERY_DEFF_STAFF_SALLERY] FOREIGN KEY ([STAFF_SALLERY_DEFF_PID]) REFERENCES [dbo].[STAFF_SALLERY] ([STAFF_SALLERY_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

