CREATE TABLE [dbo].[STAFF_LEAVES] (
    [STAFF_LEAVES_ID]                                             NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [STAFF_LEAVES_HD_ID]                                          NUMERIC (18)   NULL,
    [STAFF_LEAVES_BR_ID]                                          NUMERIC (18)   NULL,
    [STAFF_LEAVES_YEAR]                                           NUMERIC (18)   NULL,
    [STAFF_LEAVES_NAME]                                           NVARCHAR (200) NULL,
    [STAFF_LEAVES_MONTHLY_LIMIT]                                  NUMERIC (18)   NULL,
    [STAFF_LEAVES_TRANSFER_YEAR]                                  CHAR (2)       NULL,
    [STAFF_LEAVES_TRANSFER_MONTH]                                 CHAR (2)       NULL,
    [STAFF_LEAVES_STAFF_ID]                                       NUMERIC (18)   NULL,
    [STAFF_LEAVES_ABSENT_DEDUCTION]                               CHAR (2)       NULL,
    [STAFF_LEAVES_DATE]                                           DATETIME       NULL,
    [STAFF_LEAVES_USER]                                           NVARCHAR (200) NULL,
    [STAFF_LEAVES_STATUS]                                         CHAR (2)       NULL,
    [STAFF_LEAVES_LATE_PER_ABSENT]                                NUMERIC (18)   NULL,
    [STAFF_LEAVES_DEDUCTION_LEAVES]                               CHAR (2)       NULL,
    [STAFF_LEAVES_ADD_WEEKEND_HOLIDAYS]                           CHAR (2)       NULL,
    [STAFF_LEAVES_ADD_EXCEPTIONAL_HOLIDAYS]                       CHAR (2)       NULL,
    [STAFF_LEAVES_ADD_DEDUCTION]                                  CHAR (2)       NULL,
    [STAFF_LEAVES_ADD_ALLOWANCES]                                 CHAR (2)       NULL,
    [STAFF_LEAVES_ADD_LOAN]                                       CHAR (2)       NULL,
    [STAFF_LEAVES_DEDUCT_LEAVES_STATUS]                           CHAR (2)       NULL,
    [STAFF_LEAVES_DEDUCT_ABSENT_STATUS]                           CHAR (2)       NULL,
    [STAFF_LEAVES_CONSECUTIVE_ABSENT_STATUS]                      CHAR (2)       NULL,
    [STAFF_LEAVES_CONSECUTIVE_LEAVES_STATUS]                      CHAR (2)       NULL,
    [STAFF_LEAVES_CONSECUTIVE_BEFORE_WEEKENDS]                    INT            NULL,
    [STAFF_LEAVES_CONSECUTIVE_AFTER_WEEKENDS]                     INT            NULL,
    [STAFF_LEAVES_DEDUCT_LEAVES_COUNT]                            FLOAT (53)     NULL,
    [STAFF_LEAVES_DEDUCT_ABSENT_COUNT]                            FLOAT (53)     NULL,
    [STAFF_LEAVES_PER_DAY_SALARY_TYPE]                            NVARCHAR (50)  NULL,
    [STAFF_LEAVES_LATE_DEDUCTION_TYPE]                            NVARCHAR (50)  NULL,
    [STAFF_LEAVES_PAYROLL_MINUTES_IN_HOUR]                        INT            NULL,
    [STAFF_LEAVES_PAYROLL_HOURS_IN_DAY]                           INT            NULL,
    [STAFF_LEAVES_PAYROLL_OVERTIME_MINUTES_IN_HOUR_BEFORE_TIMEIN] INT            NULL,
    [STAFF_LEAVES_PAYROLL_EARLY_DEPARTURE_MINUTES]                INT            NULL,
    [STAFF_LEAVES_SUMMER_LEAVES]                                  INT            NULL,
    [STAFF_LEAVES_WINTER_LEAVES]                                  INT            NULL,
    [STAFF_LEAVES_EARLY_PER_ABSENT]                               NUMERIC (18)   NULL,
    CONSTRAINT [PK_STAFF_LEAVES] PRIMARY KEY CLUSTERED ([STAFF_LEAVES_ID] ASC),
    CONSTRAINT [FK_STAFF_LEAVES_BR_ADMIN] FOREIGN KEY ([STAFF_LEAVES_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_STAFF_LEAVES_MAIN_HD_INFO] FOREIGN KEY ([STAFF_LEAVES_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_STAFF_LEAVES_TEACHER_INFO] FOREIGN KEY ([STAFF_LEAVES_STAFF_ID]) REFERENCES [dbo].[TEACHER_INFO] ([TECH_ID])
);

