CREATE TABLE [dbo].[STUDENT_INFO_YEARWISE_HISTORY] (
    [ID]                         NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [STDNT_ID]                   NUMERIC (18)    NOT NULL,
    [STDNT_HD_ID]                NUMERIC (18)    NOT NULL,
    [STDNT_BR_ID]                NUMERIC (18)    NOT NULL,
    [STDNT_PARANT_ID]            NUMERIC (18)    NOT NULL,
    [STDNT_CLASS_PLANE_ID]       NUMERIC (18)    NOT NULL,
    [STDNT_CLASS_FEE_ID]         NUMERIC (18)    NOT NULL,
    [STDNT_REG_BY_ID]            NUMERIC (18)    NOT NULL,
    [STDNT_REG_BY_TYPE]          NVARCHAR (50)   NOT NULL,
    [STDNT_FIRST_NAME]           NVARCHAR (50)   NULL,
    [STDNT_LAST_NAME]            NVARCHAR (50)   NULL,
    [STDNT_GENDER]               BIT             NULL,
    [STDNT_NATIONALITY]          NVARCHAR (50)   NULL,
    [STDNT_RELIGION]             NVARCHAR (50)   NULL,
    [STDNT_DOB]                  DATE            NULL,
    [STDNT_PREVIOUS_SCHOOL]      NVARCHAR (50)   NULL,
    [STDNT_MOTHR_LANG]           NVARCHAR (50)   NULL,
    [STDNT_EMAIL]                NVARCHAR (50)   NULL,
    [STDNT_IMG]                  NVARCHAR (MAX)  NULL,
    [STDNT_EMERGENCY_CNTCT_NAME] NVARCHAR (50)   NULL,
    [STDNT_EMERGENCY_CNTCT_NO]   NVARCHAR (20)   NULL,
    [STDNT_CELL_NO]              NVARCHAR (20)   NULL,
    [STDNT_TEMP_ADDR]            NVARCHAR (MAX)  NULL,
    [STDNT_PERM_ADDR]            NVARCHAR (MAX)  NULL,
    [STDNT_TRANSPORT_MODE]       NVARCHAR (50)   NULL,
    [STDNT_REG_DATE]             DATE            NULL,
    [STDNT_CLASSES_START_DATE]   DATE            NULL,
    [STDNT_STATUS]               CHAR (2)        NULL,
    [STDNT_SCHOOL_ID]            NVARCHAR (50)   NULL,
    [STDNT_REGISTRATION_ID]      NVARCHAR (50)   NULL,
    [STDNT_SESSION_ID]           NUMERIC (18)    NULL,
    [STDNT_DESCRIPTION]          NVARCHAR (4000) NULL,
    [STDNT_DISCOUNT_RULE_ID]     NUMERIC (18)    NULL,
    [STDNT_HOUSE_ID]             NUMERIC (18)    NULL,
    [STDNT_DATE_OF_LEAVING]      DATE            NULL,
    [STDNT_WITH_DRAW_NO]         NVARCHAR (200)  NULL,
    [STDNT_CATEGORY]             NVARCHAR (50)   NULL,
    [STDNT_CONDUCT_ID]           NUMERIC (18)    NULL,
    [STDNT_REMARKS]              NVARCHAR (2000) NULL,
    [STDNT_COA_ID]               NUMERIC (18)    NULL,
    [STDNT_CITY_ID]              NUMERIC (18)    NULL,
    [STDNT_AREA_ID]              NUMERIC (18)    NULL,
    [STDNT_SCHOLARSHIP_ID]       NUMERIC (18)    NULL,
    [STDNT_LAB_TYPE]             NVARCHAR (50)   NULL,
    [STDNT_IS_REJOIN]            BIT             NULL,
    [CreatedDate]                DATETIME        NULL,
    [CreatedBy]                  NUMERIC (18)    NULL,
    [UpdatedDate]                DATETIME        NULL,
    [UpdatedBy]                  NUMERIC (18)    NULL,
    [STDNT_SHORT_NAME]           NVARCHAR (50)   NULL,
    [COPYING_DATETIME]           DATETIME        NULL,
    [Session]                    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_STUDENT_INFO_YEARWISE_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);



