CREATE TABLE [dbo].[STUDENT_FEE_NOTES] (
    [STD_FEE_NOTES_ID]          NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [STD_FEE_NOTES_HD_ID]       NUMERIC (18)    NULL,
    [STD_FEE_NOTES_BR_ID]       NUMERIC (18)    NULL,
    [STD_FEE_NOTES_CLASS_ID]    NUMERIC (18)    NULL,
    [STD_FEE_NOTES_DESCRIPTION] NVARCHAR (4000) NULL,
    [STD_FEE_NOTES_STATUS]      CHAR (2)        NULL,
    CONSTRAINT [PK_STUDENT_FEE_NOTES] PRIMARY KEY CLUSTERED ([STD_FEE_NOTES_ID] ASC),
    CONSTRAINT [FK_STUDENT_FEE_NOTES_BR_ADMIN] FOREIGN KEY ([STD_FEE_NOTES_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_STUDENT_FEE_NOTES_MAIN_HD_INFO] FOREIGN KEY ([STD_FEE_NOTES_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_STUDENT_FEE_NOTES_SCHOOL_PLANE] FOREIGN KEY ([STD_FEE_NOTES_CLASS_ID]) REFERENCES [dbo].[SCHOOL_PLANE] ([CLASS_ID])
);

