CREATE TABLE [dbo].[STUDENT_ELECTIVE_SUBJECT] (
    [STD_ELE_SUB_ID]         NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [STD_ELE_SUB_STDNT_ID]   NUMERIC (18) NULL,
    [STD_ELE_SUB_SUBJECT_ID] NUMERIC (18) NULL,
    CONSTRAINT [PK_STUDENT_ELECTIVE_SUBJECT] PRIMARY KEY CLUSTERED ([STD_ELE_SUB_ID] ASC),
    CONSTRAINT [FK_STUDENT_ELECTIVE_SUBJECT_STUDENT_INFO] FOREIGN KEY ([STD_ELE_SUB_STDNT_ID]) REFERENCES [dbo].[STUDENT_INFO] ([STDNT_ID]),
    CONSTRAINT [FK_STUDENT_ELECTIVE_SUBJECT_SUBJECT_INFO] FOREIGN KEY ([STD_ELE_SUB_SUBJECT_ID]) REFERENCES [dbo].[ELECTIVE_SUBJECT_DEF] ([ELE_SUB_DEF_ID])
);

