CREATE TABLE [dbo].[STUDY_CRITERIA_INFO] (
    [STUDY_CRITERIA_ID]     NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [STUDY_CRITERIA_HD_ID]  NUMERIC (18)  NOT NULL,
    [STUDY_CRITERIA_BR_ID]  NUMERIC (18)  NULL,
    [STUDY_CRITERIA_NAME]   NVARCHAR (50) NULL,
    [STUDY_CRITERIA_LENGTH] INT           NULL,
    [STUDY_CRITERIA_FORMAT] NVARCHAR (50) NULL,
    [STUDY_CRITERIA_STATUS] CHAR (2)      NULL,
    CONSTRAINT [PK_STUDY_CRITERIA_INFO] PRIMARY KEY CLUSTERED ([STUDY_CRITERIA_ID] ASC),
    CONSTRAINT [FK_STUDY_CRITERIA_INFO_BR_ADMIN] FOREIGN KEY ([STUDY_CRITERIA_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_STUDY_CRITERIA_INFO_MAIN_HD_INFO] FOREIGN KEY ([STUDY_CRITERIA_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

