CREATE TABLE [dbo].[STUDENT_ROLL_NUM] (
    [STUDENT_ROLL_NUM_ID]            NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [STUDENT_ROLL_NUM_HD_ID]         NUMERIC (18) NOT NULL,
    [STUDENT_ROLL_NUM_BR_ID]         NUMERIC (18) NOT NULL,
    [STUDENT_ROLL_NUM_STD_ID]        NUMERIC (18) NOT NULL,
    [STUDENT_ROLL_NUM_PLAN_ID]       NUMERIC (18) NOT NULL,
    [STUDENT_ROLL_NUM_FEE_ID]        NUMERIC (18) NULL,
    [STUDENT_ROLL_NUM_ROLL_NO]       NUMERIC (18) NULL,
    [STUDENT_ROLL_NUM_STATUS]        NCHAR (2)    NULL,
    [STUDENT_ROLL_NUM_ACTIVE_STATUS] NVARCHAR (5) NULL,
    [STUDENT_ROLL_NUM_SESSION]       DATE         NULL,
    CONSTRAINT [PK_STUDENT_ROLL_NUM] PRIMARY KEY CLUSTERED ([STUDENT_ROLL_NUM_ID] ASC),
    CONSTRAINT [FK_STUDENT_ROLL_NUM_BR_ADMIN] FOREIGN KEY ([STUDENT_ROLL_NUM_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_STUDENT_ROLL_NUM_MAIN_HD_INFO] FOREIGN KEY ([STUDENT_ROLL_NUM_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

