CREATE TABLE [dbo].[SUBJECT_GRADE_INFO] (
    [SUB_GRADE_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SUB_GRADE_HD_ID]  NUMERIC (18)   NOT NULL,
    [SUB_GRADE_BR_ID]  NUMERIC (18)   NULL,
    [SUB_GRADE_NAME]   NVARCHAR (50)  NULL,
    [SUB_GRADE_DESC]   NVARCHAR (500) NULL,
    [SUB_GRADE_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_SUBJECT_GRADE] PRIMARY KEY CLUSTERED ([SUB_GRADE_ID] ASC),
    CONSTRAINT [FK_SUBJECT_GRADE_INFO_BR_ADMIN] FOREIGN KEY ([SUB_GRADE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SUBJECT_GRADE_INFO_MAIN_HD_INFO] FOREIGN KEY ([SUB_GRADE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

