CREATE TABLE [dbo].[SUBJECT_TYPE_INFO] (
    [SUBJECT_TYPE_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SUBJECT_TYPE_HD_ID]  NUMERIC (18)   NOT NULL,
    [SUBJECT_TYPE_BR_ID]  NUMERIC (18)   NULL,
    [SUBJECT_TYPE_NAME]   NVARCHAR (50)  NULL,
    [SUBJECT_TYPE_DESC]   NVARCHAR (500) NULL,
    [SUBJECT_TYPE_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_SUBJECT_TYPE] PRIMARY KEY CLUSTERED ([SUBJECT_TYPE_ID] ASC),
    CONSTRAINT [FK_SUBJECT_TYPE_INFO_BR_ADMIN] FOREIGN KEY ([SUBJECT_TYPE_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SUBJECT_TYPE_INFO_MAIN_HD_INFO] FOREIGN KEY ([SUBJECT_TYPE_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

