CREATE TABLE [dbo].[SUMMER_WINTER_INFO] (
    [SUM_WIN_ID]                   NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [SUM_WIN_SESSION_ID]           NUMERIC (18) NULL,
    [SUM_WIN_HD_ID]                NUMERIC (18) NULL,
    [SUM_WIN_BR_ID]                NUMERIC (18) NULL,
    [SUM_WIN_SUMMER_START_DATE]    DATE         NULL,
    [SUM_WIN_SUMMER_END_DATE]      DATE         NULL,
    [SUM_WIN_WINTER_START_DATE]    DATE         NULL,
    [SUM_WIN_WINTER_END_DATE]      DATE         NULL,
    [SUM_WIN_SEMESTER1_START_DATE] DATE         NULL,
    [SUM_WIN_SEMESTER1_END_DATE]   DATE         NULL,
    [SUM_WIN_SEMESTER2_START_DATE] DATE         NULL,
    [SUM_WIN_SEMESTER2_END_DATE]   DATE         NULL,
    CONSTRAINT [PK_SUMMER_WINTER_INFO] PRIMARY KEY CLUSTERED ([SUM_WIN_ID] ASC),
    CONSTRAINT [FK_SUMMER_WINTER_INFO_BR_ADMIN] FOREIGN KEY ([SUM_WIN_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SUMMER_WINTER_INFO_MAIN_HD_INFO] FOREIGN KEY ([SUM_WIN_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

