CREATE TABLE [dbo].[SUPER_ADMIN_INFO] (
    [SUPER_ADMIN_ID]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SUPER_ADMIN_NAME]      NVARCHAR (100) NULL,
    [SUPER_ADMIN_MOBILE_NO] NVARCHAR (15)  NULL,
    [SUPER_ADMIN_STATUS]    CHAR (2)       NULL,
    CONSTRAINT [PK_SUPER_ADMIN_INFO] PRIMARY KEY CLUSTERED ([SUPER_ADMIN_ID] ASC)
);

