CREATE TABLE [dbo].[SUPLEMENTARY_PARENT] (
    [SUPL_ID]         NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [SUPL_HD_ID]      NUMERIC (18)    NULL,
    [SUPL_BR_ID]      NUMERIC (18)    NULL,
    [SUPL_NAME]       NVARCHAR (1000) NULL,
    [SUPL_MONTH_NAME] NVARCHAR (50)   NULL,
    [SUPL_NOTES1]     NVARCHAR (1000) NULL,
    [SUPL_NOTES2]     NVARCHAR (1000) NULL,
    [SUPL_DUE_DATE]   DATE            NULL,
    CONSTRAINT [PK_SUPLEMENTARY_PARENT] PRIMARY KEY CLUSTERED ([SUPL_ID] ASC),
    CONSTRAINT [FK_SUPLEMENTARY_PARENT_BR_ADMIN] FOREIGN KEY ([SUPL_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_SUPLEMENTARY_PARENT_MAIN_HD_INFO] FOREIGN KEY ([SUPL_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

