CREATE TABLE [dbo].[SUPLEMENTARY_DEF] (
    [SUPL_DEF_ID]             NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [SUPL_DEF_PID]            NUMERIC (18) NULL,
    [SUPL_DEF_STUDENT_ID]     NUMERIC (18) NULL,
    [SUPL_DEF_GPA]            FLOAT (53)   NULL,
    [SUPL_DEF_PERCENTAGE]     FLOAT (53)   NULL,
    [SUPL_DEF_FEE]            FLOAT (53)   NULL,
    [SUPL_DEF_FEE_COLLECT_ID] NUMERIC (18) NULL,
    CONSTRAINT [PK_SUPLEMENTARY_DEF] PRIMARY KEY CLUSTERED ([SUPL_DEF_ID] ASC),
    CONSTRAINT [FK_SUPLEMENTARY_DEF_FEE_COLLECT] FOREIGN KEY ([SUPL_DEF_FEE_COLLECT_ID]) REFERENCES [dbo].[FEE_COLLECT] ([FEE_COLLECT_ID]),
    CONSTRAINT [FK_SUPLEMENTARY_DEF_STUDENT_INFO] FOREIGN KEY ([SUPL_DEF_STUDENT_ID]) REFERENCES [dbo].[STUDENT_INFO] ([STDNT_ID]),
    CONSTRAINT [FK_SUPLEMENTARY_DEF_SUPLEMENTARY_PARENT] FOREIGN KEY ([SUPL_DEF_PID]) REFERENCES [dbo].[SUPLEMENTARY_PARENT] ([SUPL_ID])
);

