CREATE TABLE [dbo].[TBL_VCH_SERIES] (
    [VCH_SERIES_ID]             NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [VCH_SERIES_HD_ID]          NUMERIC (18)  NULL,
    [VCH_SERIES_BR_ID]          NUMERIC (18)  NULL,
    [VCH_SERIES_VCH_MAIN_ID]    NVARCHAR (50) NULL,
    [VCH_SERIES_VCH_PREFIX]     NVARCHAR (50) NULL,
    [VCH_SERIES_BANK_CODE]      NVARCHAR (50) NULL,
    [VCH_SERIES_DEF_COA]        NVARCHAR (50) NULL,
    [VCH_SERIES_NUMBER]         INT           NULL,
    [VCH_SERIES_VOUCHER_SERIES] NVARCHAR (50) NULL,
    [VCH_SERIES_DATE]           DATE          NULL,
    CONSTRAINT [PK_TBL_VCH_SERIES] PRIMARY KEY CLUSTERED ([VCH_SERIES_ID] ASC),
    CONSTRAINT [FK_TBL_VCH_SERIES_BR_ADMIN] FOREIGN KEY ([VCH_SERIES_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_TBL_VCH_SERIES_MAIN_HD_INFO] FOREIGN KEY ([VCH_SERIES_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

