CREATE TABLE [dbo].[TBL_ACC_PLAN_DEF] (
    [CMP_ID]                             NVARCHAR (50) NULL,
    [BRC_ID]                             NVARCHAR (50) NULL,
    [TBL_ACC_PLAN_DEF_ID]                INT           IDENTITY (1, 1) NOT NULL,
    [TBL_ACC_PLAN_MAIN_ID]               INT           NULL,
    [TBL_ACC_PLAN_DEF_levelNo]           INT           NULL,
    [TBL_ACC_PLAN_DEF_format]            NVARCHAR (50) NULL,
    [TBL_ACC_PLAN_DEF_isFixed]           BIT           NULL,
    [TBL_ACC_PLAN_DEF_fixedAcc]          NVARCHAR (50) NULL,
    [TBL_ACC_PLAN_DEF_isAutoGenerated]   BIT           NULL,
    [TBL_ACC_PLAN_DEF_accTypePlan]       INT           NULL,
    [TBL_ACC_PLAN_DEF_accValidationPlan] INT           NULL,
    [TBL_ACC_PLAN_DEF_fixedType]         INT           NULL,
    [TBL_ACC_PLAN_DEF_isTransaction]     BIT           NULL,
    [TBL_ACC_PLAN_DEF_isActive]          BIT           NULL,
    [TBL_ACC_PLAN_DEF_isDeleted]         BIT           NULL,
    CONSTRAINT [PK_TBL_ACC_PLAN_DEF] PRIMARY KEY CLUSTERED ([TBL_ACC_PLAN_DEF_ID] ASC)
);

