CREATE TABLE [dbo].[TEACHER_HISTORY] (
    [TECH_HISTORY_ID]            INT           IDENTITY (1, 1) NOT NULL,
    [TECH_HISTORY_STAFF_ID]      INT           NULL,
    [TECH_HISTORY_DEPARTMENT]    NVARCHAR (50) NULL,
    [TECH_HISTORY_DESIGNATION]   NVARCHAR (50) NULL,
    [TECH_HISTORY_QUALIFICATION] NVARCHAR (50) NULL,
    [TECH_HISTORY_SALARY]        FLOAT (53)    NULL,
    [TECH_HISTORY_DATETIME]      DATETIME      NULL,
    [TECH_HISTORY_LEFT_DATE]     DATE          NULL,
    [TECH_HISTORY_STATUS]        CHAR (2)      NULL,
    CONSTRAINT [PK_TEACHER_HISTORY] PRIMARY KEY CLUSTERED ([TECH_HISTORY_ID] ASC)
);

