CREATE TABLE [dbo].[TEACHER_INFO] (
    [TECH_ID]                           NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [TECH_HD_ID]                        NUMERIC (18)   NOT NULL,
    [TECH_BR_ID]                        NUMERIC (18)   NOT NULL,
    [TECH_REG_BY_ID]                    NUMERIC (18)   NOT NULL,
    [TECH_PARANT_ID]                    NUMERIC (18)   NULL,
    [TECH_REG_BY_TYPE]                  NVARCHAR (50)  NOT NULL,
    [TECH_FIRST_NAME]                   NVARCHAR (50)  NULL,
    [TECH_LAST_NAME]                    NVARCHAR (50)  NULL,
    [TECH_GENDER]                       BIT            NULL,
    [TECH_NATIONALITY]                  NVARCHAR (50)  NULL,
    [TECH_RELIGION]                     NVARCHAR (50)  NULL,
    [TECH_DOB]                          DATETIME       NULL,
    [TECH_CNIC]                         NVARCHAR (50)  NULL,
    [TECH_CELL_NO]                      NVARCHAR (20)  NULL,
    [TECH_RESIDENCE_NO]                 NVARCHAR (20)  NULL,
    [TECH_TEMP_ADDER]                   NVARCHAR (MAX) NULL,
    [TECH_PERM_ADDER]                   NVARCHAR (MAX) NULL,
    [TECH_MOTHR_LANG]                   NVARCHAR (50)  NULL,
    [TECH_QUALIFICATION]                NVARCHAR (50)  NULL,
    [TECH_DESIGNATION]                  NVARCHAR (50)  NULL,
    [TECH_EXPERIENCE]                   NVARCHAR (50)  NULL,
    [TECH_SALLERY]                      FLOAT (53)     NULL,
    [TECH_EMAIL]                        NVARCHAR (50)  NULL,
    [TECH_IMG]                          NVARCHAR (MAX) NULL,
    [TECH_REG_DATE]                     DATETIME       NULL,
    [TECH_STATUS]                       CHAR (2)       NULL,
    [TECH_JOINING_DATE]                 DATE           NULL,
    [TECH_USER]                         NVARCHAR (50)  NULL,
    [TECH_USER_INFO_ID]                 NUMERIC (18)   NULL,
    [TECH_LEFT_DATE]                    DATE           NULL,
    [TECH_RANKING]                      NUMERIC (18)   NULL,
    [TECH_IS_COMMISION]                 CHAR (2)       NULL,
    [TECH_IS_OVERTIME]                  CHAR (2)       NULL,
    [TECH_DEPARTMENT]                   NVARCHAR (50)  NULL,
    [TECH_EMPLOYEE_CODE]                NVARCHAR (100) NULL,
    [TECH_CONFIRMATION_DURATION_MONTHS] INT            NULL,
    [TECH_CONFIRMATION_DATE]            DATE           NULL,
    [TECH_CITY]                         NUMERIC (18)   NULL,
    [TECH_STAFF_TYPE]                   NUMERIC (18)   NULL,
    [TECH_DEDUCTION_TYPE]               NVARCHAR (50)  NULL,
    [TECH_COA_ID]                       NUMERIC (18)   NULL,
    [TECH_BANK_ACCOUNT_NO]              NVARCHAR (100) NULL,
    [TECH_BANK_ACCOUNT_TITLE]           NVARCHAR (100) NULL,
    [TECH_BANK_ID]                      NUMERIC (18)   NULL,
    [TECH_LEAVES_TYPE]                  NVARCHAR (50)  NULL,
    [TECH_IS_VACATION_ALLOWED]          BIT            NULL,
    [TECH_ID_DESIGNATION]               NVARCHAR (100) NULL,
    [TECH_ID_CARD_NAME]                 NVARCHAR (100) NULL,
    CONSTRAINT [PK_TEACHER_INFO] PRIMARY KEY CLUSTERED ([TECH_ID] ASC),
    CONSTRAINT [FK_TEACHER_INFO_BANK_INFO] FOREIGN KEY ([TECH_BANK_ID]) REFERENCES [dbo].[BANK_INFO] ([BANK_ID]),
    CONSTRAINT [FK_TEACHER_INFO_BR_ADMIN] FOREIGN KEY ([TECH_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_TEACHER_INFO_CITY_INFO] FOREIGN KEY ([TECH_CITY]) REFERENCES [dbo].[CITY_INFO] ([CITY_ID]),
    CONSTRAINT [FK_TEACHER_INFO_MAIN_HD_INFO] FOREIGN KEY ([TECH_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_TEACHER_INFO_STAFF_TYPE_INFO] FOREIGN KEY ([TECH_STAFF_TYPE]) REFERENCES [dbo].[STAFF_TYPE_INFO] ([STAFF_TYPE_ID]),
    CONSTRAINT [FK_TEACHER_INFO_USER_INFO] FOREIGN KEY ([TECH_USER_INFO_ID]) REFERENCES [dbo].[USER_INFO] ([USER_ID])
);



