CREATE TABLE [dbo].[TEACHER_VACATION] (
    [TEACHER_VACATION_ID]          NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [TEACHER_VACATION_HD_ID]       NUMERIC (18)   NULL,
    [TEACHER_VACATION_BR_ID]       NUMERIC (18)   NULL,
    [TEACHER_VACATION_FROM_DATE]   DATE           NULL,
    [TEACHER_VACATION_TO_DATE]     DATE           NULL,
    [TEACHER_VACATION_DESCRIPTION] NVARCHAR (500) NULL,
    [TEACHER_VACATION_STATUS]      CHAR (2)       NULL,
    CONSTRAINT [PK_TEACHER_VACATION] PRIMARY KEY CLUSTERED ([TEACHER_VACATION_ID] ASC)
);

