CREATE TABLE [dbo].[TEST_INFO] (
    [TEST_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [TEST_HD_ID]  NUMERIC (18)   NOT NULL,
    [TEST_BR_ID]  NUMERIC (18)   NULL,
    [TEST_NAME]   NVARCHAR (50)  NULL,
    [TEST_DESC]   NVARCHAR (500) NULL,
    [TEST_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_TEST] PRIMARY KEY CLUSTERED ([TEST_ID] ASC),
    CONSTRAINT [FK_TEST_INFO_BR_ADMIN] FOREIGN KEY ([TEST_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_TEST_INFO_MAIN_HD_INFO] FOREIGN KEY ([TEST_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

