CREATE TABLE [dbo].[TIMER_SETTING] (
    [ID]            NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [IS_TIMER_STOP] BIT          NULL,
    CONSTRAINT [PK_TIMER_SETTING] PRIMARY KEY CLUSTERED ([ID] ASC)
);

