CREATE TABLE [dbo].[TRANSPORT_INFO] (
    [TRANSPORT_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [TRANSPORT_HD_ID]  NUMERIC (18)   NOT NULL,
    [TRANSPORT_BR_ID]  NUMERIC (18)   NULL,
    [TRANSPORT_NAME]   NVARCHAR (50)  NULL,
    [TRANSPORT_DESC]   NVARCHAR (500) NULL,
    [TRANSPORT_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_TRANSPORT] PRIMARY KEY CLUSTERED ([TRANSPORT_ID] ASC),
    CONSTRAINT [FK_TRANSPORT_INFO_BR_ADMIN] FOREIGN KEY ([TRANSPORT_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_TRANSPORT_INFO_MAIN_HD_INFO] FOREIGN KEY ([TRANSPORT_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

