CREATE TABLE [dbo].[UNIVERSITY_PLAN] (
    [SMSTR_ID]              NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [SMSTR_HD_ID]           NUMERIC (18)  NOT NULL,
    [SMSTR_BR_ID]           NUMERIC (18)  NOT NULL,
    [SMSTR_DEGRE_NAME]      NUMERIC (18)  NULL,
    [SMSTR_SUBJECT]         NVARCHAR (50) NULL,
    [SMSTR_SHIFT]           NVARCHAR (50) NULL,
    [SMSTR_SECTION]         NVARCHAR (50) NULL,
    [SMSTR_DPRTMNT]         NVARCHAR (50) NULL,
    [SMSTR_NO]              INT           NULL,
    [SMSTR_SEQUANCE_NO]     INT           NULL,
    [SMSTR_CR_HRS]          FLOAT (53)    NULL,
    [SMSTR_PRICE]           FLOAT (53)    NULL,
    [SMSTR_VARIATION_PRCNT] FLOAT (53)    NULL,
    [SMSTR_STATUS]          CHAR (2)      NOT NULL,
    CONSTRAINT [PK_DEGREE_PLAN] PRIMARY KEY CLUSTERED ([SMSTR_ID] ASC),
    CONSTRAINT [FK_UNIVERSITY_PLAN_BR_ADMIN] FOREIGN KEY ([SMSTR_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_UNIVERSITY_PLAN_MAIN_HD_INFO] FOREIGN KEY ([SMSTR_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

