CREATE TABLE [dbo].[USER_INFO] (
    [USER_ID]           NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [USER_HD_ID]        NUMERIC (18)  NULL,
    [USER_BR_ID]        NUMERIC (18)  NULL,
    [USER_CODE]         NUMERIC (18)  NULL,
    [USER_NAME]         NVARCHAR (50) NULL,
    [USER_DISPLAY_NAME] NVARCHAR (50) NULL,
    [USER_TYPE]         NVARCHAR (20) NULL,
    [USER_PASSWORD]     NVARCHAR (50) NULL,
    [USER_STATUS]       CHAR (2)      NULL,
    [USER_ROLE]         NUMERIC (18)  NULL,
    CONSTRAINT [PK_USER_INFO] PRIMARY KEY CLUSTERED ([USER_ID] ASC),
    CONSTRAINT [FK_USER_INFO_BR_ADMIN] FOREIGN KEY ([USER_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_USER_INFO_MAIN_HD_INFO] FOREIGN KEY ([USER_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID]),
    CONSTRAINT [FK_USER_INFO_RIGHTS_PACKAGES_PARENT] FOREIGN KEY ([USER_ROLE]) REFERENCES [dbo].[RIGHTS_PACKAGES_PARENT] ([PACKAGES_ID])
);

