CREATE TABLE [dbo].[WORKING_HOURS_PACKAGES_DEF] (
    [WORK_PACK_DEF_ID]         NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [WORK_PACK_DEF_PID]        NUMERIC (18)  NULL,
    [WORK_PACK_DEF_DAY_NAME]   NVARCHAR (50) NULL,
    [WORK_PACK_DEF_DAY_STATUS] CHAR (1)      NULL,
    [WORK_PACK_DEF_TIME_IN]    NVARCHAR (50) NULL,
    [WORK_PACK_DEF_TIME_OUT]   NVARCHAR (50) NULL,
    CONSTRAINT [PK_WORKING_PACKAGES_DEF] PRIMARY KEY CLUSTERED ([WORK_PACK_DEF_ID] ASC),
    CONSTRAINT [FK_WORKING_HOURS_PACKAGES_DEF_WORKING_HOURS_PACKAGES] FOREIGN KEY ([WORK_PACK_DEF_PID]) REFERENCES [dbo].[WORKING_HOURS_PACKAGES] ([HOURS_PACK_ID])
);

