CREATE TABLE [dbo].[WORKING_DAYS] (
    [WORKING_DAYS_ID]         NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [WORKING_DAYS_HD_ID]      NUMERIC (18)  NULL,
    [WORKING_DAYS_BR_ID]      NUMERIC (18)  NULL,
    [WORKING_DAYS_NAME]       NVARCHAR (50) NULL,
    [WORKING_DAYS_VALUE]      BIT           NULL,
    [WORKING_DAYS_STATUS]     CHAR (2)      NULL,
    [WORKING_DAYS_DEPENDENCE] CHAR (2)      NULL,
    CONSTRAINT [PK_WORKING_DAYS] PRIMARY KEY CLUSTERED ([WORKING_DAYS_ID] ASC),
    CONSTRAINT [FK_WORKING_DAYS_BR_ADMIN] FOREIGN KEY ([WORKING_DAYS_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_WORKING_DAYS_MAIN_HD_INFO] FOREIGN KEY ([WORKING_DAYS_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

