CREATE TABLE [dbo].[WORKING_HOURS] (
    [WORKING_HOURS_ID]       NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [WORKING_HOURS_HD_ID]    NUMERIC (18)  NULL,
    [WORKING_HOURS_BR_ID]    NUMERIC (18)  NULL,
    [WORKING_HOURS_TIME_IN]  NVARCHAR (50) NULL,
    [WORKING_HOURS_TIME_OUT] NVARCHAR (50) NULL,
    [WORKING_HOURS_STATUS]   CHAR (2)      NULL,
    CONSTRAINT [PK_WORKING_HOURS] PRIMARY KEY CLUSTERED ([WORKING_HOURS_ID] ASC),
    CONSTRAINT [FK_WORKING_HOURS_BR_ADMIN] FOREIGN KEY ([WORKING_HOURS_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_WORKING_HOURS_MAIN_HD_INFO] FOREIGN KEY ([WORKING_HOURS_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

