CREATE TABLE [dbo].[YEAR_INFO] (
    [YEAR_ID]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [YEAR_HD_ID]  NUMERIC (18)   NOT NULL,
    [YEAR_BR_ID]  NUMERIC (18)   NULL,
    [YEAR_NAME]   NVARCHAR (50)  NULL,
    [YEAR_DESC]   NVARCHAR (500) NULL,
    [YEAR_STATUS] CHAR (2)       NULL,
    CONSTRAINT [PK_YEAR] PRIMARY KEY CLUSTERED ([YEAR_ID] ASC),
    CONSTRAINT [FK_YEAR_INFO_BR_ADMIN] FOREIGN KEY ([YEAR_BR_ID]) REFERENCES [dbo].[BR_ADMIN] ([BR_ADM_ID]),
    CONSTRAINT [FK_YEAR_INFO_MAIN_HD_INFO] FOREIGN KEY ([YEAR_HD_ID]) REFERENCES [dbo].[MAIN_HD_INFO] ([MAIN_INFO_ID])
);

