CREATE FUNCTION [dbo].[GET_TEACHER_VACATION_DATES] (@HD_ID numeric, @BR_ID numeric, @DATE date)

returns @tbl table (From_Date date, To_Date date)

as begin


insert into @tbl

select CASE WHEN NOT (DATEPART(MM, TEACHER_VACATION_FROM_DATE) = DATEPART(MM, @DATE) and DATEPART(YYYY, TEACHER_VACATION_FROM_DATE) = DATEPART(YYYY, @DATE)) THEN DATEADD(m, DATEDIFF(m, 0, @DATE), 0) ELSE TEACHER_VACATION_FROM_DATE END TEACHER_VACATION_FROM_DATE ,
CASE WHEN NOT (DATEPART(MM, TEACHER_VACATION_TO_DATE) = DATEPART(MM, @DATE) and DATEPART(YYYY, TEACHER_VACATION_TO_DATE) = DATEPART(YYYY, @DATE)) THEN dateadd(s,-1,dateadd(mm,datediff(m,0,@DATE)+1,0)) ELSE TEACHER_VACATION_TO_DATE END TEACHER_VACATION_TO_DATE from TEACHER_VACATION where TEACHER_VACATION_HD_ID = @HD_ID and TEACHER_VACATION_BR_ID = @BR_ID and  ((DATEPART(MM, TEACHER_VACATION_FROM_DATE) = DATEPART(MM, @DATE) and DATEPART(YYYY, TEACHER_VACATION_FROM_DATE) = DATEPART(YYYY, @DATE)) OR (DATEPART(MM, TEACHER_VACATION_TO_DATE) = DATEPART(MM, @DATE) and DATEPART(YYYY, TEACHER_VACATION_TO_DATE) = DATEPART(YYYY, @DATE)))

return
END