CREATE FUNCTION sf_GET_LEAVES_RECORD (@STAFF_SALLERY_DATE date, @STAFF_SALLERY_STAFF_ID numeric)
returns @tbl table (sr int ,Leaves int, FromDate date,ToDate date,[Is Causal Leaves] bit, [Is Annual Leaves] bit)

AS 
BEGIN

insert into @tbl
select ROW_NUMBER() over(order by (select LEAVES_RECORD_FROM_DATE)) ,DATEDIFF(D,LEAVES_RECORD_FROM_DATE,LEAVES_RECORD_TO_DATE) + 1 ,LEAVES_RECORD_FROM_DATE, LEAVES_RECORD_TO_DATE,LEAVES_RECORD_IS_CAUSAL_LEAVES,LEAVES_RECORD_IS_ANNUAL_LEAVES from

								(
								select CASE WHEN NOT (DATEPART(MM, LEAVES_RECORD_FROM_DATE) = DATEPART(MM, @STAFF_SALLERY_DATE) and DATEPART(YYYY, LEAVES_RECORD_FROM_DATE) = DATEPART(YYYY, @STAFF_SALLERY_DATE)) THEN DATEADD(m, DATEDIFF(m, 0, @STAFF_SALLERY_DATE), 0) ELSE LEAVES_RECORD_FROM_DATE END LEAVES_RECORD_FROM_DATE ,

								CASE WHEN NOT (DATEPART(MM, LEAVES_RECORD_TO_DATE) = DATEPART(MM, @STAFF_SALLERY_DATE) and DATEPART(YYYY, LEAVES_RECORD_TO_DATE) = DATEPART(YYYY, @STAFF_SALLERY_DATE)) THEN dateadd(s,-1,dateadd(mm,datediff(m,0,@STAFF_SALLERY_DATE)+1,0)) ELSE LEAVES_RECORD_TO_DATE END LEAVES_RECORD_TO_DATE,LEAVES_RECORD_IS_CAUSAL_LEAVES,LEAVES_RECORD_IS_ANNUAL_LEAVES from LEAVES_RECORD where LEAVES_RECORD_STAFF_ID = @STAFF_SALLERY_STAFF_ID and ((DATEPART(MM, LEAVES_RECORD_FROM_DATE) = DATEPART(MM, @STAFF_SALLERY_DATE) and DATEPART(YYYY, LEAVES_RECORD_FROM_DATE) = DATEPART(YYYY, @STAFF_SALLERY_DATE)) OR 
								(DATEPART(MM, LEAVES_RECORD_TO_DATE) = DATEPART(MM, @STAFF_SALLERY_DATE) and DATEPART(YYYY, LEAVES_RECORD_TO_DATE) = DATEPART(YYYY, @STAFF_SALLERY_DATE)) )
								)A

return

END