


CREATE VIEW [dbo].aaa
AS
SELECT        dbo.FEE_COLLECT.FEE_COLLECT_ID AS ID, dbo.FEE_COLLECT.FEE_COLLECT_HD_ID AS [Institute ID], dbo.FEE_COLLECT.FEE_COLLECT_BR_ID AS [Branch ID], 
                         dbo.STUDENT_INFO.STDNT_FIRST_NAME AS [First Name], dbo.STUDENT_INFO.STDNT_LAST_NAME AS [Last Name], dbo.SCHOOL_PLANE.CLASS_Name AS Class, dbo.SECTION_INFO.SECT_NAME AS Section, 
                         dbo.STUDENT_INFO.STDNT_ID AS [Std ID], dbo.FEE_COLLECT.FEE_COLLECT_DATE_FEE_GENERATED AS Date, dbo.get_month_name(dbo.FEE_COLLECT.FEE_COLLECT_FEE_FROM_DATE, 
                         dbo.FEE_COLLECT.FEE_COLLECT_FEE_TO_DATE) AS Month, dbo.FEE_COLLECT.FEE_COLLECT_ARREARS AS Arrears, dbo.STUDENT_FEE_NOTES.STD_FEE_NOTES_DESCRIPTION AS Notes, 
                         dbo.STUDENT_FEE_NOTES.STD_FEE_NOTES_STATUS, dbo.FEE_COLLECT.FEE_COLLECT_FEE_STATUS AS Status, dbo.PARENT_INFO.PARNT_FIRST_NAME AS [Father Name], 
                         dbo.FEE_COLLECT.FEE_COLLECT_PLAN_ID AS [Class ID], dbo.BR_ADMIN.BR_ADM_BANK_NAME AS [Bank Name], dbo.BR_ADMIN.BR_ADM_ACCT_TITLE AS [Bank Acct Title], 
                         dbo.BR_ADMIN.BR_ADM_ACCT_NO AS [Bank Acct no], LEFT(DATENAME(MONTH, dbo.FEE_COLLECT.FEE_COLLECT_DUE_DAY), 3) + '.  ' + CAST(DATEPART(DAY, dbo.FEE_COLLECT.FEE_COLLECT_DUE_DAY) 
                         AS nvarchar(50)) + ', ' + CAST(DATEPART(YEAR, dbo.FEE_COLLECT.FEE_COLLECT_DUE_DAY) AS nvarchar(50)) AS [Due Date], dbo.FEE_COLLECT.FEE_COLLECT_FEE_FROM_DATE AS [Start Date], 
                         dbo.FEE_COLLECT.FEE_COLLECT_FEE_TO_DATE AS [End Date], dbo.STUDENT_INFO.STDNT_SCHOOL_ID AS [School ID], dbo.PARENT_INFO.PARNT_CELL_NO AS [Parent Cell], 
                         dbo.STUDENT_INFO.STDNT_CELL_NO AS [Student Cell], dbo.FEE_COLLECT.FEE_COLLECT_ATTENDANCE_FROM_DATE AS [Attendance From Date], 
                         dbo.FEE_COLLECT.FEE_COLLECT_ATTENDANCE_TO_DATE AS [Attendance To Date], 
                         dbo.PARENT_INFO.PARNT_TEMP_ADDR AS [Parent Address], 
						 dbo.AREA_INFO.AREA_NAME area ,dbo.PARENT_INFO.PARNT_FAMILY_CODE AS [Family Code], 
                         dbo.FEE_SETTING.FEE_SETTING_FINE AS [Late Fee Fine], dbo.FEE_SETTING.FEE_SETTING_REPRINT_CHARGES AS [Reprinting Charges], dbo.STUDENT_INFO.STDNT_PARANT_ID AS [Parent ID], 
                         dbo.FEE_COLLECT.FEE_COLLECT_INSTALLMENT_NAME AS [Installment Name], dbo.BR_ADMIN.BR_ADM_NAME AS [Branch Name], dbo.MAIN_HD_INFO.MAIN_INFO_LOGO_REPORTS AS [Logo Reports]
FROM            dbo.FEE_COLLECT INNER JOIN
                         dbo.STUDENT_INFO ON dbo.FEE_COLLECT.FEE_COLLECT_STD_ID = dbo.STUDENT_INFO.STDNT_ID INNER JOIN
                         dbo.SCHOOL_PLANE ON dbo.FEE_COLLECT.FEE_COLLECT_PLAN_ID = dbo.SCHOOL_PLANE.CLASS_ID INNER JOIN
                         dbo.STUDENT_FEE_NOTES ON dbo.FEE_COLLECT.FEE_COLLECT_HD_ID = dbo.STUDENT_FEE_NOTES.STD_FEE_NOTES_HD_ID AND 
                         dbo.FEE_COLLECT.FEE_COLLECT_BR_ID = dbo.STUDENT_FEE_NOTES.STD_FEE_NOTES_BR_ID AND dbo.SCHOOL_PLANE.CLASS_ID = dbo.STUDENT_FEE_NOTES.STD_FEE_NOTES_CLASS_ID INNER JOIN
                         dbo.PARENT_INFO ON dbo.STUDENT_INFO.STDNT_PARANT_ID = dbo.PARENT_INFO.PARNT_ID LEFT OUTER JOIN
                         dbo.BR_ADMIN ON dbo.STUDENT_INFO.STDNT_BR_ID = dbo.BR_ADMIN.BR_ADM_ID INNER JOIN
                         dbo.CLASS_INFO ON dbo.SCHOOL_PLANE.CLASS_CLASS = dbo.CLASS_INFO.CLASS_ID INNER JOIN
                         dbo.SECTION_INFO ON dbo.SCHOOL_PLANE.CLASS_SECTION = dbo.SECTION_INFO.SECT_ID INNER JOIN
                         dbo.AREA_INFO ON dbo.PARENT_INFO.PARNT_AREA = dbo.AREA_INFO.AREA_ID INNER JOIN
                         dbo.CITY_INFO ON dbo.PARENT_INFO.PARNT_CITY = dbo.CITY_INFO.CITY_ID INNER JOIN
                         dbo.MAIN_HD_INFO ON dbo.FEE_COLLECT.FEE_COLLECT_HD_ID = dbo.MAIN_HD_INFO.MAIN_INFO_ID LEFT OUTER JOIN
                         dbo.FEE_SETTING ON dbo.FEE_SETTING.FEE_SETTING_BR_ID = dbo.BR_ADMIN.BR_ADM_ID
WHERE        (dbo.STUDENT_FEE_NOTES.STD_FEE_NOTES_STATUS = 'T')