CREATE VIEW [dbo].[rpt_V_TEACHER_TIME_TABLE]
AS
SELECT     TOP (100) PERCENT SUM(dbo.SCHOOL_PLANE.CLASS_ID) AS ID, dbo.SCHOOL_PLANE.CLASS_HD_ID AS [Institute ID], dbo.SCHOOL_PLANE.CLASS_BR_ID AS Branch, 
                      dbo.SCHOOL_PLANE.CLASS_Name AS [Plan Name], dbo.SCHOOL_PLANE.CLASS_CLASS AS Class, dbo.SCHOOL_PLANE.CLASS_SHIFT AS Shift, 
                      dbo.SCHOOL_PLANE.CLASS_SECTION AS Section, dbo.SCHOOL_PLANE.CLASS_DPRTMNT AS Department, 
                      dbo.SCHOOL_PLANE_DEFINITION.DEF_TEACHER AS Teacher, dbo.SCHOOL_PLANE_DEFINITION.DEF_SUBJECT AS Subject, 
                      dbo.SCHOOL_PLANE_DEFINITION.DEF_TERM AS Term, dbo.SCHOOL_PLANE_DEFINITION.DEF_START_TIME AS [Start Time], 
                      dbo.SCHOOL_PLANE_DEFINITION.DEF_END_TIME AS [End Time], dbo.SCHOOL_PLANE_DEFINITION.DEF_STATUS AS Status
FROM         dbo.SCHOOL_PLANE INNER JOIN
                      dbo.SCHOOL_PLANE_DEFINITION ON dbo.SCHOOL_PLANE.CLASS_ID = dbo.SCHOOL_PLANE_DEFINITION.DEF_CLASS_ID
GROUP BY dbo.SCHOOL_PLANE.CLASS_HD_ID, dbo.SCHOOL_PLANE.CLASS_BR_ID, dbo.SCHOOL_PLANE.CLASS_Name, dbo.SCHOOL_PLANE.CLASS_CLASS, 
                      dbo.SCHOOL_PLANE.CLASS_SHIFT, dbo.SCHOOL_PLANE.CLASS_SECTION, dbo.SCHOOL_PLANE.CLASS_DPRTMNT, 
                      dbo.SCHOOL_PLANE_DEFINITION.DEF_TEACHER, dbo.SCHOOL_PLANE_DEFINITION.DEF_SUBJECT, dbo.SCHOOL_PLANE_DEFINITION.DEF_TERM, 
                      dbo.SCHOOL_PLANE_DEFINITION.DEF_START_TIME, dbo.SCHOOL_PLANE_DEFINITION.DEF_END_TIME, dbo.SCHOOL_PLANE_DEFINITION.DEF_STATUS
ORDER BY ID