CREATE VIEW [dbo].[V_GRADE_PLAN_SCHOOL]
AS
SELECT     dbo.GRADE_MAPPING.GRADE_MAP_ID AS ID, dbo.SCHOOL_PLANE.CLASS_Name AS [Class Name], dbo.PLAN_GRADE.P_GRADE_PLAN_NAME AS [Grade Plan], 
                      dbo.GRADE_MAPPING.GRADE_MAP_STATUS AS Status, dbo.GRADE_MAPPING.GRADE_MAP_HD_ID AS [Institute ID], 
                      dbo.GRADE_MAPPING.GRADE_MAP_BR_ID AS [Branch ID], dbo.GRADE_MAPPING.GRADE_MAP_GRADE_PLAN_ID AS [Grade Plan ID]
FROM         dbo.GRADE_MAPPING INNER JOIN
                      dbo.SCHOOL_PLANE ON dbo.GRADE_MAPPING.GRADE_MAP_CLASS_ID = dbo.SCHOOL_PLANE.CLASS_ID INNER JOIN
                      dbo.PLAN_GRADE ON dbo.GRADE_MAPPING.GRADE_MAP_GRADE_PLAN_ID = dbo.PLAN_GRADE.P_GRADE_ID