CREATE VIEW [dbo].[V_MAIN_HD_LOAD]
AS
SELECT     dbo.MAIN_HD_INFO.MAIN_INFO_ID + 1 AS HD, dbo.MAIN_HD_INFO.MAIN_INFO_DATE_FORMAT AS [DATE ID], dbo.DATE_INFO.DATE_NAME AS [DATE NAME], 
                      dbo.MAIN_HD_INFO.MAIN_INFO_INSTITUTION_LEVEL AS [INST  ID], dbo.INSTITUTION_LEVEL_INFO.INST_LEVEL_NAME AS [INST LEVEL]
FROM         dbo.MAIN_HD_INFO INNER JOIN
                      dbo.DATE_INFO ON dbo.MAIN_HD_INFO.MAIN_INFO_DATE_FORMAT = dbo.DATE_INFO.DATE_ID INNER JOIN
                      dbo.INSTITUTION_LEVEL_INFO ON dbo.MAIN_HD_INFO.MAIN_INFO_INSTITUTION_LEVEL = dbo.INSTITUTION_LEVEL_INFO.INST_LEVEL_ID