CREATE VIEW [dbo].[VASSESSMENT_INFO]
AS
SELECT     ASSESSMENT_ID AS ID, ASSESSMENT_HD_ID AS [Institute ID], ASSESSMENT_BR_ID AS [Branch ID], ASSESSMENT_NAME AS Name, 
                      ASSESSMENT_DESC AS Description, ASSESSMENT_STATUS AS Status
FROM         dbo.ASSESSMENT_INFO