CREATE VIEW [dbo].[VAUTO_SCHEDULE]
AS
SELECT        SCHEDULE_ID AS ID, SCHEDULE_HD_ID AS [HD ID], SCHEDULE_BR_ID AS [BR ID], SCHEDULE_TYPE AS Type, SCHEDULE_TIME AS Time, 
                         SCHEDULE_DAY AS Day, SCHEDULE_DATE AS Date, SCHEDULE_STUDENT AS [Send Student], SCHEDULE_PARENT AS [Send Parent], 
                         SCHEDULE_STATUS AS [Send Status], SCHEDULE_NOTIFICATION_TYPE AS [Notification Type]
FROM            dbo.AUTO_SCHEDULE