CREATE VIEW [dbo].[VCLASS_INFO]
AS
SELECT     CLASS_ID AS ID, CLASS_HD_ID AS [Institute ID], CLASS_BR_ID AS [Branch ID], CLASS_NAME AS Name, CLASS_DESC AS Description, CLASS_STATUS AS Status
FROM         dbo.CLASS_INFO