CREATE VIEW [dbo].[VDAILY_FEE]
AS
SELECT     dbo.FEE_HISTORY_DEF.FEE_HISTORY_DEF_ID AS [His Def ID], dbo.FEE_HISTORY.FEE_HISTORY_ID AS [His ID], 
                      dbo.FEE_HISTORY.FEE_HISTORY_PID AS [His PID], dbo.FEE_HISTORY_DEF.FEE_HISTORY_DEF_PID AS [His Def PID], 
                      dbo.FEE_HISTORY_DEF.FEE_HISTORY_DEF_NAME AS [His Def Fee ID], dbo.FEE_HISTORY_DEF.FEE_HISTORY_DEF_PAID AS [His Def Fee Received], 
                      dbo.FEE_HISTORY_DEF.FEE_HISTORY_DEF_ARREARS_RECEIVED AS [His Def Arrears Received], dbo.FEE_HISTORY.FEE_HISTORY_PAID AS [His Fee Received], 
                      dbo.FEE_HISTORY.FEE_HISTORY_DATE AS [His Date], dbo.FEE_HISTORY.FEE_HISTORY_ARREARS_RECEIVED AS [His Arrears Received]
FROM         dbo.FEE_HISTORY INNER JOIN
                      dbo.FEE_HISTORY_DEF ON dbo.FEE_HISTORY.FEE_HISTORY_ID = dbo.FEE_HISTORY_DEF.FEE_HISTORY_DEF_PID