CREATE VIEW [dbo].[VDESIGNATION_INFO]
AS
SELECT     DESIGNATION_ID AS ID, DESIGNATION_HD_ID AS [Institute ID], DESIGNATION_BR_ID AS [Branch ID], DESIGNATION_NAME AS Name, 
                      DESIGNATION_DESC AS Description, DESIGNATION_STATUS AS Status
FROM         dbo.DESIGNATION_INFO