CREATE VIEW [dbo].[VDISCOUNT_RULES_DEF]
AS
SELECT        DIS_RUL_DEF_ID AS ID, DIS_RUL_DEF_PID AS PID, DIS_RUL_DEF_FEE_ID AS [Fee ID], DIS_RUL_DEF_DISCOUNT AS Fee, DIS_RUL_DEF_STATUS AS Status
FROM            dbo.DISCOUNT_RULES_DEF