CREATE VIEW [dbo].[VDISCOUNT_RULES]
AS
SELECT        dbo.DISCOUNT_RULES.DIS_RUL_ID AS ID, dbo.DISCOUNT_RULES.DIS_RUL_HD_ID AS [Institute ID], dbo.DISCOUNT_RULES.DIS_RUL_BR_ID AS [Branch ID], 
                         dbo.DISCOUNT_RULES.DIS_RUL_NAME AS Name, dbo.DISCOUNT_RULES.DIS_RUL_STATUS AS Status, dbo.DISCOUNT_RULES.DIS_RUL_CLASS_ID AS [Class ID], 
                         dbo.SCHOOL_PLANE.CLASS_Name AS [Class Name]
FROM            dbo.DISCOUNT_RULES INNER JOIN
                         dbo.SCHOOL_PLANE ON dbo.DISCOUNT_RULES.DIS_RUL_CLASS_ID = dbo.SCHOOL_PLANE.CLASS_ID