CREATE VIEW [dbo].[VDOC_CUSTODIAN_INFO]
AS
SELECT     DOC_CUSTODIAN_ID AS ID, DOC_CUSTODIAN_HD_ID AS [Institute ID], DOC_CUSTODIAN_BR_ID AS [Branch ID], DOC_CUSTODIAN_NAME AS Name, DOC_CUSTODIAN_DESC AS Description, DOC_CUSTODIAN_STATUS AS Status
FROM         dbo.DOC_CUSTODIAN_INFO