CREATE VIEW [dbo].[VELECTIVE_SUBJECT]
AS
SELECT        dbo.ELECTIVE_SUBJECT.ELE_SUB_ID AS ID, dbo.ELECTIVE_SUBJECT.ELE_SUB_HD_ID AS [Institute ID], dbo.ELECTIVE_SUBJECT.ELE_SUB_BR_ID AS [Branch ID], 
                         dbo.ELECTIVE_SUBJECT.ELE_SUB_NAME AS [Group Name], dbo.ELECTIVE_SUBJECT.ELE_SUB_CLASS_ID AS [Class ID], 
                         dbo.SCHOOL_PLANE.CLASS_Name AS [Class Plan], dbo.ELECTIVE_SUBJECT.ELE_SUB_STATUS AS Status
FROM            dbo.ELECTIVE_SUBJECT INNER JOIN
                         dbo.SCHOOL_PLANE ON dbo.ELECTIVE_SUBJECT.ELE_SUB_CLASS_ID = dbo.SCHOOL_PLANE.CLASS_ID