CREATE VIEW [dbo].[VELECTIVE_SUBJECT_DEF]
AS
SELECT        ELE_SUB_DEF_ID AS ID, ELE_SUB_DEF_PID AS PID, ELE_SUB_DEF_SUB_ID AS Subject, ELE_SUB_DEF_STATUS AS Status
FROM            dbo.ELECTIVE_SUBJECT_DEF