CREATE VIEW [dbo].[VEXAM_CRITERIA_KEY]
AS
SELECT        CRITERIA_KEY_ID AS ID, CRITERIA_KEY_STD_ID AS [Std ID], CRITERIA_KEY_CAT_CRITERIA_ID AS [Criteria ID], CRITERIA_KEY AS [Key], 
                         CRITERIA_KEY_TERM_ID AS [Term ID], CRITERIA_KEY_CLASS_ID AS [Class ID]
FROM            dbo.EXAM_CRITERIA_KEY