CREATE VIEW [dbo].[vEXAM_APPROVAL_SETTINGS]
AS
SELECT        APPROVAL_ID AS ID, APPROVAL_HD_ID AS [HD ID], APPROVAL_BR_ID AS [BR ID], APPROVAL_STAFF_ID AS [Staff ID], APPROVAL_DESIGNATION AS Designation, 
                         APPROVAL_RANK AS Rank, APPROVAL_STATUS AS Status
FROM            dbo.EXAM_APPROVAL_SETTINGS