CREATE VIEW [dbo].[VEXAM_CATEGORY_CRITERIA]
AS
SELECT        CAT_CRITERIA_ID AS ID, CAT_CRITERIA_HD_ID AS [Institute ID], CAT_CRITERIA_BR_ID AS [Branch ID], CAT_CRITERIA_EXAM_CAT_ID AS [Category ID], 
                         CAT_CRITERIA_NAME AS Name, CAT_CRITERIA_STATUS AS Status
FROM            dbo.EXAM_CATEGORY_CRITERIA