CREATE VIEW [dbo].[VFEE_ADVANCE_DEF]
AS
SELECT     ADV_FEE_DEF_ID AS ID, ADV_FEE_DEF_FROM_DATE AS [From Date], ADV_FEE_DEF_TO_DATE AS [To Date], ADV_FEE_DEF_AMOUNT AS Amount, 
                      ADV_FEE_DEF_ADJUST_DATE AS [Adjust Date], ADV_FEE_DEF_STATUS AS Adjust, ADV_FEE_DEF_PID AS PID
FROM         dbo.FEE_ADVANCE_DEF