CREATE VIEW [dbo].[VFEE_HISTORY_DEF]
AS
SELECT     FEE_HISTORY_DEF_ID AS ID, FEE_HISTORY_DEF_NAME AS [Fee Name], FEE_HISTORY_DEF_FEE AS Fee, FEE_HISTORY_DEF_PAID AS [Fee Received], 
                      FEE_HISTORY_DEF_MIN AS [Min Fee Variation %], FEE_HISTORY_DEF_MAX AS [Max Fee Variation %], FEE_HISTORY_DEF_OPERATION AS Operation, 
                      FEE_HISTORY_DEF_ARREARS AS Arrears, FEE_HISTORY_DEF_ARREARS_RECEIVED AS [Arrears Received], FEE_HISTORY_DEF_TOTAL AS [Net Total]
FROM         dbo.FEE_HISTORY_DEF