CREATE VIEW [dbo].[VFEE_SETTING]
AS
SELECT     FEE_SETTING_ID AS ID, FEE_SETTING_HD_ID AS [Institute ID], FEE_SETTING_BR_ID AS [Branch ID], FEE_SETTING_FINE AS Fine, 
                      FEE_SETTING_FEE_CRITERIA AS [Fee Criteria], FEE_SETTING_REPRINT_CHARGES AS [Reprinting Charges]
FROM         dbo.FEE_SETTING