CREATE VIEW [dbo].[VFEE_QUERY]
AS
SELECT     TOP (100) PERCENT dbo.FEE_COLLECT.FEE_COLLECT_ID AS [Invoice ID], dbo.STUDENT_INFO.STDNT_FIRST_NAME AS Name, 
                      dbo.SCHOOL_PLANE.CLASS_Name AS [Class Plan], CASE WHEN DATEPART(MM, FEE_COLLECT_FEE_FROM_DATE) = DATEPART(MM, FEE_COLLECT_FEE_TO_DATE) 
                      THEN LEFT(DATENAME(MONTH, FEE_COLLECT_FEE_FROM_DATE), 3) ELSE LEFT(DATENAME(MONTH, FEE_COLLECT_FEE_FROM_DATE), 3) 
                      + ' ' + CONVERT(nvarchar(5), DATEPART(YYYY, FEE_COLLECT_FEE_FROM_DATE)) + ' - ' + LEFT(DATENAME(MONTH, FEE_COLLECT_FEE_TO_DATE), 3) 
                      END + ' ' + CONVERT(nvarchar(15), DATEPART(YYYY, dbo.FEE_COLLECT.FEE_COLLECT_FEE_TO_DATE)) AS [Month Year], 
                      dbo.SCHOOL_PLANE.CLASS_ID AS [Class ID], dbo.STUDENT_INFO.STDNT_ID AS [Student ID], dbo.FEE_COLLECT.FEE_COLLECT_DATE_FEE_GENERATED AS Date, 
                      dbo.FEE_COLLECT.FEE_COLLECT_HD_ID AS [Institute ID], dbo.FEE_COLLECT.FEE_COLLECT_BR_ID AS [Branch ID], 
                      dbo.STUDENT_INFO.STDNT_PARANT_ID AS [Parent ID], dbo.FEE_COLLECT.FEE_COLLECT_DATE_FEE_RECEIVED AS [Date Received], 
                      dbo.FEE_COLLECT.FEE_COLLECT_FEE_ID AS [Fee ID], CAST(CONVERT(nvarchar(5), DATEPART(YYYY, dbo.FEE_COLLECT.FEE_COLLECT_FEE_FROM_DATE)) 
                      + CONVERT(nvarchar(2), DATEPART(MM, dbo.FEE_COLLECT.FEE_COLLECT_FEE_FROM_DATE)) AS int) AS [int Month Year], 
                      dbo.FEE_COLLECT.FEE_COLLECT_FEE_STATUS AS [Fee Status]
FROM         dbo.FEE_COLLECT INNER JOIN
                      dbo.STUDENT_INFO ON dbo.FEE_COLLECT.FEE_COLLECT_STD_ID = dbo.STUDENT_INFO.STDNT_ID INNER JOIN
                      dbo.SCHOOL_PLANE ON dbo.FEE_COLLECT.FEE_COLLECT_PLAN_ID = dbo.SCHOOL_PLANE.CLASS_ID