CREATE VIEW [dbo].[VGRADE_INFO]
AS
SELECT     GRADE_ID AS ID, GRADE_HD_ID AS [Institute ID], GRADE_BR_ID AS [Branch ID], GRADE_NAME AS Name, GRADE_DESC AS Description, GRADE_STATUS AS Status
FROM         dbo.GRADE_INFO