CREATE VIEW [dbo].[VMARKET_TRACKING]
AS
SELECT        dbo.MARKET_TRACKING.TRACK_ID AS ID, dbo.MARKET_TRACKING.TRACK_HD_ID AS [HD ID], dbo.MARKET_TRACKING.TRACK_BR_ID AS [BR ID], 
                         dbo.MARKET_TRACKING.TRACK_SCHOOL_NAME AS [Company Name], dbo.MARKET_TRACKING.TRACK_SCHOOL_ADDRESS AS [Company Address], 
                         dbo.CITY_INFO.CITY_NAME AS City, dbo.AREA_INFO.AREA_NAME AS Area, dbo.SALES_REPRESENTATIVE_INFO.SALES_NAME AS [Sales Representataive], 
                         dbo.MARKETING_STATUS.MARK_STATUS_NAME AS Status, dbo.MARKET_TRACKING.TRACK_SCHOOL_MOBILE_NO1 AS [Company Mobile1], 
                         dbo.MARKET_TRACKING.TRACK_SCHOOL_MOBILE_NO2 AS [Company Mobile2], dbo.MARKET_TRACKING.TRACK_SCHOOL_LANDLINE_NO AS [Company Landline], 
                         dbo.MARKET_TRACKING.TRACK_SCHOOL_EMAIL AS [Company Email], dbo.MARKET_TRACKING.TRACK_SCHOOL_WEBSITE AS [Company Website], 
                         dbo.MARKET_TRACKING.TRACK_CONTACT_NAME AS [Contact Person Name], dbo.MARKET_TRACKING.TRACK_CONTACT_MOBILE_NO AS [Contact Mobile No], 
                         dbo.MARKET_TRACKING.TRACK_CONTACT_LANDLINE_NO AS [Contact Landline No], dbo.MARKET_TRACKING.TRACK_CONTACT_EMAIL AS [Contact Email], 
                         dbo.MARKET_TRACKING.TRACK_REFFERED_BY AS [Reffered By], dbo.MARKET_TRACKING.TRACK_SCHOOL_COUNTRY AS [Country ID], 
                         dbo.NATIONALITY_INFO.NATIONALITY_NAME AS Country, dbo.MARKET_TRACKING.TRACK_SCHOOL_CITY AS [City ID], 
                         dbo.MARKET_TRACKING.TRACK_SCHOOL_AREA AS [Area ID], dbo.MARKET_TRACKING.TRACK_CONTACT_DESIGNATION AS [Designation ID], 
                         dbo.DESIGNATION_INFO.DESIGNATION_NAME AS Designation, dbo.MARKET_TRACKING.TRACK_SALES_REPRESENTATIVE AS [Sales Representataive ID], 
                         dbo.MARKET_TRACKING.TRACK_MARKETING_MODE_ID AS [Marketing Mode ID], dbo.MARKETING_MODE_INFO.MODE_NAME AS Mode, 
                         dbo.MARKET_TRACKING.TRACK_STATUS AS [Status ID]
FROM            dbo.MARKETING_STATUS RIGHT OUTER JOIN
                         dbo.MARKETING_MODE_INFO RIGHT OUTER JOIN
                         dbo.SALES_REPRESENTATIVE_INFO RIGHT OUTER JOIN
                         dbo.AREA_INFO RIGHT OUTER JOIN
                         dbo.NATIONALITY_INFO RIGHT OUTER JOIN
                         dbo.MARKET_TRACKING ON dbo.NATIONALITY_INFO.NATIONALITY_ID = dbo.MARKET_TRACKING.TRACK_SCHOOL_COUNTRY LEFT OUTER JOIN
                         dbo.CITY_INFO ON dbo.MARKET_TRACKING.TRACK_SCHOOL_CITY = dbo.CITY_INFO.CITY_ID ON 
                         dbo.AREA_INFO.AREA_ID = dbo.MARKET_TRACKING.TRACK_SCHOOL_AREA LEFT OUTER JOIN
                         dbo.DESIGNATION_INFO ON dbo.MARKET_TRACKING.TRACK_CONTACT_DESIGNATION = dbo.DESIGNATION_INFO.DESIGNATION_ID ON 
                         dbo.SALES_REPRESENTATIVE_INFO.SALES_ID = dbo.MARKET_TRACKING.TRACK_SALES_REPRESENTATIVE ON 
                         dbo.MARKETING_MODE_INFO.MODE_ID = dbo.MARKET_TRACKING.TRACK_MARKETING_MODE_ID ON 
                         dbo.MARKETING_STATUS.MARK_STATUS_ID = dbo.MARKET_TRACKING.TRACK_STATUS