CREATE VIEW [dbo].[VMARK_STATUS]
AS
SELECT        MARK_STATUS_ID AS ID, MARK_STATUS_HD_ID AS [Institute ID], MARK_STATUS_BR_ID AS [Branch ID], MARK_STATUS_NAME AS Name, 
                         MARK_STATUS_DESCRIPTION AS Description, MARK_STATUS AS Status
FROM            dbo.MARKETING_STATUS