CREATE VIEW [dbo].[VNATIONALITY_INFO]
AS
SELECT     NATIONALITY_ID AS ID, NATIONALITY_HD_ID AS [Institute ID], NATIONALITY_BR_ID AS [Branch ID], NATIONALITY_NAME AS Name, 
                      NATIONALITY_DESC AS Description, NATIONALITY_STATUS AS Status
FROM         dbo.NATIONALITY_INFO