CREATE VIEW [dbo].[VPEOPLE_RELATIONS_INFO]
AS
SELECT     PEOPLE_RELATIONS_ID AS ID, PEOPLE_RELATIONS_HD_ID AS [Institute ID], PEOPLE_RELATIONS_BR_ID AS [Branch ID], PEOPLE_RELATIONS_NAME AS Name, PEOPLE_RELATIONS_DESC AS Description, PEOPLE_RELATIONS_STATUS AS Status
FROM         dbo.PEOPLE_RELATIONS_INFO