CREATE VIEW [dbo].[VPLAN_ASSESSMENT]
AS
SELECT dbo.PLAN_ASSESSMENT.PLAN_ASSESSMENT_ID AS ID, 
    dbo.PLAN_ASSESSMENT.PLAN_ASSESSMENT_PID AS PID, 
    dbo.ASSESSMENT_INFO.ASSESSMENT_NAME AS Name, 
    CASE WHEN PLAN_ASSESSMENT.PLAN_ASSESSMENT_TERM_ID = 0 THEN
     'Final Term' ELSE
        (SELECT TERM_NAME
      FROM TERM_INFO
      WHERE TERM_ID = PLAN_ASSESSMENT.PLAN_ASSESSMENT_TERM_ID)
     END AS Term, 
    dbo.PLAN_ASSESSMENT.PLAN_ASSESSMENT_TOTAL AS [Total Marks],
     dbo.PLAN_ASSESSMENT.[PLAN_ASSESSMENT_PASS_%AGE] AS [Pass %age],
     dbo.PLAN_ASSESSMENT.PLAN_ASSESSMENT_STATUS AS Status
FROM dbo.PLAN_ASSESSMENT INNER JOIN
    dbo.ASSESSMENT_INFO ON 
    dbo.PLAN_ASSESSMENT.PLAN_ASSESSMENT_INFO_ID = dbo.ASSESSMENT_INFO.ASSESSMENT_ID