CREATE VIEW [dbo].[VRELIGION_INFO]
AS
SELECT     RELIGION_ID AS ID, RELIGION_HD_ID AS [Institute ID], RELIGION_BR_ID AS [Branch ID], RELIGION_NAME AS Name, RELIGION_DESC AS Description, 
                      RELIGION_STATUS AS Status
FROM         dbo.RELIGION_INFO