CREATE VIEW [dbo].[VSMS_HISTORY_QUERY]
AS
SELECT        dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_ID AS [Message ID], dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_HD_ID AS HD_ID, 
                         dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_BR_ID AS BR_ID, dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_MOBILE_NO AS [Mobile No], 
                         dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_MESSAGE AS Message, dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_DATE_TIME AS Date, 
                         dbo.SMS_SCREEN.SMS_SCREEN_NAME AS [Screen Name], dbo.USER_INFO.USER_ID AS [User Login ID], 
                         dbo.SMS_CLIENT_PC_INFO.SMS_CLIENT_PC_NAME AS [Client PC Name], dbo.SMS_CLIENT_PC_INFO.SMS_CLIENT_PC_WINDOWS AS [Client PC OS]
FROM            dbo.RIGHTS_PAGES INNER JOIN
                         dbo.RIGHTS_PACKAGES_CHILD ON dbo.RIGHTS_PAGES.RIGHTS_PAGES_ID = dbo.RIGHTS_PACKAGES_CHILD.PACKAGES_DEF_RIGHTS_PAGES_ID INNER JOIN
                         dbo.USER_INFO ON dbo.RIGHTS_PACKAGES_CHILD.PACKAGES_DEF_PID = dbo.USER_INFO.USER_ROLE INNER JOIN
                         dbo.SMS_SCREEN ON dbo.RIGHTS_PAGES.RIGHTS_PAGES_NAME = dbo.SMS_SCREEN.RIGHTS_PAGE_NAME INNER JOIN
                         dbo.SMS_SENT_HISTORY ON dbo.SMS_SCREEN.SMS_SCREEN_ID = dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_SCREEN_ID INNER JOIN
                         dbo.SMS_CLIENT_PC_INFO ON dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_CLIENT_PC_ID = dbo.SMS_CLIENT_PC_INFO.SMS_CLIENT_PC_ID
WHERE        (dbo.RIGHTS_PACKAGES_CHILD.PACKAGES_DEF_STATUS = 1)