CREATE VIEW [dbo].[VSMS_HISTORY_QUERY_MGT]
AS
SELECT        dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_ID, dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_HD_ID, 
                         dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_BR_ID, dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_MOBILE_NO, 
                         dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_MESSAGE, dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_DATE_TIME, 
                         dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_CLIENT_PC_ID, dbo.SMS_SCREEN.SMS_SCREEN_NAME, dbo.USER_INFO.USER_ID
FROM            dbo.RIGHTS_PAGES INNER JOIN
                         dbo.RIGHTS_PACKAGES_CHILD ON dbo.RIGHTS_PAGES.RIGHTS_PAGES_ID = dbo.RIGHTS_PACKAGES_CHILD.PACKAGES_DEF_RIGHTS_PAGES_ID INNER JOIN
                         dbo.USER_INFO ON dbo.RIGHTS_PACKAGES_CHILD.PACKAGES_DEF_PID = dbo.USER_INFO.USER_ROLE INNER JOIN
                         dbo.SMS_SCREEN ON dbo.RIGHTS_PAGES.RIGHTS_PAGES_NAME = dbo.SMS_SCREEN.RIGHTS_PAGE_NAME INNER JOIN
                         dbo.SMS_SENT_HISTORY ON dbo.SMS_SCREEN.SMS_SCREEN_ID = dbo.SMS_SENT_HISTORY.SMS_SENT_HISTORY_SCREEN_ID
WHERE        (dbo.RIGHTS_PACKAGES_CHILD.PACKAGES_DEF_STATUS = 1)