CREATE VIEW [dbo].[VSTAFF_SALLERY_DEFF]
AS
SELECT        STAFF_SALLERY_DEFF_ID AS ID, STAFF_SALLERY_DEFF_PID AS PID, STAFF_SALLERY_DEFF_NAME AS [Deff ID], STAFF_SALLERY_DEFF_AMOUNT AS Amount, 
                         STAFF_SALLERY_DEFF_AMOUNT_TYPE AS [Amount Type], STAFF_SALLERY_DEFF_AMOUNT_STATUS AS Status
FROM            dbo.STAFF_SALLERY_DEFF