CREATE VIEW [dbo].[VSTAFF_SALLERY_INFO]
AS
SELECT     dbo.TEACHER_INFO.TECH_ID, dbo.TEACHER_INFO.TECH_SALLERY, dbo.STAFF_ALLOWANCE.STAFF_ALLOWANCE_STATUS, 
                      dbo.STAFF_LEAVES.STAFF_LEAVES_STATUS, dbo.STAFF_WORKING_DAYS.STAFF_WORKING_DAYS_STATUS, dbo.STAFF_DEDUCTION.STAFF_DEDUCTION_STATUS, 
                      dbo.STAFF_ALLOWANCE.STAFF_ALLOWANCE_AMOUNT
FROM         dbo.TEACHER_INFO INNER JOIN
                      dbo.STAFF_ALLOWANCE ON dbo.TEACHER_INFO.TECH_ID = dbo.STAFF_ALLOWANCE.STAFF_ALLOWANCE_STAFF_ID INNER JOIN
                      dbo.STAFF_DEDUCTION ON dbo.TEACHER_INFO.TECH_ID = dbo.STAFF_DEDUCTION.STAFF_DEDUCTION_STAFF_ID INNER JOIN
                      dbo.STAFF_LEAVES ON dbo.TEACHER_INFO.TECH_ID = dbo.STAFF_LEAVES.STAFF_LEAVES_STAFF_ID INNER JOIN
                      dbo.STAFF_WORKING_DAYS ON dbo.TEACHER_INFO.TECH_ID = dbo.STAFF_WORKING_DAYS.STAFF_WORKING_DAYS_STAFF_ID
WHERE     (dbo.STAFF_ALLOWANCE.STAFF_ALLOWANCE_STATUS = 'T') AND (dbo.STAFF_LEAVES.STAFF_LEAVES_STATUS = 'T') AND 
                      (dbo.STAFF_WORKING_DAYS.STAFF_WORKING_DAYS_STATUS = 'T') AND (dbo.STAFF_DEDUCTION.STAFF_DEDUCTION_STATUS = 'T')