CREATE VIEW [dbo].[VSTUDENT_FEE_NOTES]
AS
SELECT     STD_FEE_NOTES_HD_ID AS [Institute ID], STD_FEE_NOTES_BR_ID AS [Branch ID], STD_FEE_NOTES_CLASS_ID AS [Class Plane ID], 
                      STD_FEE_NOTES_DESCRIPTION AS Description, STD_FEE_NOTES_STATUS AS Status
FROM         dbo.STUDENT_FEE_NOTES