CREATE VIEW [dbo].[VSTUDENT_ROLL_NUM]
AS
SELECT     dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_STD_ID AS ID, dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_HD_ID AS [Institute ID], 
                      dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_BR_ID AS [Branch ID], dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_ROLL_NO AS [Roll NO#], 
                      dbo.STUDENT_INFO.STDNT_FIRST_NAME AS [Student Name], dbo.PARENT_INFO.PARNT_FULL_NAME AS Parent, 
                      dbo.STUDENT_INFO.STDNT_CELL_NO AS [Cell NO#], dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_PLAN_ID AS [Class ID], 
                      dbo.SCHOOL_PLANE.CLASS_Name AS [Class Name], dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_FEE_ID AS [Fee ID], 
                      dbo.PLAN_FEE.PLAN_FEE_NAME AS [Fee Name], dbo.PLAN_FEE.PLAN_FEE_TOTAL_FEE AS [Total Fee], 
                      dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_STATUS AS Status, dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_ACTIVE_STATUS AS [Active Status], 
                      dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_SESSION AS Session
FROM         dbo.PARENT_INFO INNER JOIN
                      dbo.STUDENT_INFO ON dbo.PARENT_INFO.PARNT_ID = dbo.STUDENT_INFO.STDNT_PARANT_ID INNER JOIN
                      dbo.STUDENT_ROLL_NUM INNER JOIN
                      dbo.SCHOOL_PLANE ON dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_PLAN_ID = dbo.SCHOOL_PLANE.CLASS_ID INNER JOIN
                      dbo.PLAN_FEE ON dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_FEE_ID = dbo.PLAN_FEE.PLAN_FEE_ID ON 
                      dbo.STUDENT_INFO.STDNT_ID = dbo.STUDENT_ROLL_NUM.STUDENT_ROLL_NUM_STD_ID