CREATE VIEW [dbo].[VSUBJECT_GRADE_INFO]
AS
SELECT     SUB_GRADE_ID AS ID, SUB_GRADE_HD_ID AS [Institute ID], SUB_GRADE_BR_ID AS [Branch ID], SUB_GRADE_NAME AS Name, SUB_GRADE_DESC AS Description, 
                      SUB_GRADE_STATUS AS Status
FROM         dbo.SUBJECT_GRADE_INFO