CREATE VIEW [dbo].[VTERM_ASSESSMENT_INFO]
AS
SELECT     TERM_ASSESS_ID AS ID, TERM_ASSESS_HD_ID AS [Institute ID], TERM_ASSESS_BR_ID AS [Branch ID], TERM_ASSESS_NAME AS Name, TERM_ASSESS_DESC AS Description, TERM_ASSESS_STATUS AS Status, 
                      TERM_ASSESS_START_DATE AS [Start Date], TERM_ASSESS_END_DATE AS [End Date], TERM_ASSESS_SESSION_START_DATE AS [Session Start Date], 
                      TERM_ASSESS_SESSION_END_DATE AS [Session End Date], TERM_ASSESS_RANK AS Rank
FROM         dbo.TERM_ASSESSMENT_INFO