CREATE VIEW [dbo].[VTRANSPORT_INFO]
AS
SELECT     TRANSPORT_ID AS ID, TRANSPORT_HD_ID AS [Institute ID], TRANSPORT_BR_ID AS [Branch ID], TRANSPORT_NAME AS Name, TRANSPORT_DESC AS Description, 
                      TRANSPORT_STATUS AS Status
FROM         dbo.TRANSPORT_INFO