CREATE VIEW [dbo].[VWORKING_HOURS_PACKAGES]
AS
SELECT        HOURS_PACK_ID AS ID, HOURS_PACK_HD_ID AS [Institute ID], HOURS_PACK_BR_ID AS [Branch ID], HOURS_PACK_NAME AS Name, 
                         HOURS_PACK_STATUS AS Status
FROM            dbo.WORKING_HOURS_PACKAGES