

CREATE PROC [dbo].[rpt_STAFF_LEAVES_RECORD_ACTUAL]


@START_DATE date,
@END_DATE date,
@BR_ID numeric

AS


declare @year int = 0

set @year = DATEPART(YYYY,@END_DATE)


select t.TECH_ID ID, t.TECH_EMPLOYEE_CODE COde, t.TECH_FIRST_NAME Name,d.DEP_NAME Department,CAST(d.DEP_ID as decimal) DepartmentID,l.STAFF_LEAVES_YEAR LeavesAllowed,        CASE WHEN t.TECH_LEAVES_TYPE = 'Outstation' THEN (select COUNT(*) from ANNUAL_HOLIDAYS where ANN_HOLI_BR_ID = @BR_ID and DATEPART(YYYY,ANN_HOLI_DATE) = @year and ANN_HOLI_STATUS = 'T') ELSE  (l.STAFF_LEAVES_SUMMER_LEAVES + l.STAFF_LEAVES_WINTER_LEAVES) END as AnnualLeaves ,DATEPART(MONTH,s.STAFF_SALLERY_MONTH_DATE ) MonthInt,
'M'+ CAST(DATEPART(MONTH,s.STAFF_SALLERY_MONTH_DATE )as nvarchar) as [MonthName], CASE WHEN t.TECH_LEAVES_TYPE = 'No Deduction' THEN 0 ELSE (CAST((s.STAFF_SALLERY_ABSENTS+ s.STAFF_SALLERY_LEAVES) as float) + CAST(CAST(s.STAFF_SALLERY_HALF_DAYS as float)/ 2 as float)) + c.STAFF_LEAVES_CALC_SANDWICH_DAYS END Taken, 
ISNULL(c.STAFF_LEAVES_CALC_MONTHLY_LIMIT,0) Bal,  CASE WHEN t.TECH_LEAVES_TYPE = 'No Deduction' THEN 30 ELSE (s.STAFF_SALLERY_WORKING_DAYS - s.STAFF_SALLERY_DEDUCT_DAYS) END as DayPaid, s.STAFF_SALLERY_LATE [LA], s.STAFF_SALLERY_EARLY_DEPARTURE [ED], ISNULL(c.STAFF_LEAVES_CALC_ANNUAL_LEAVES_LIMIT,0) [AnnualBalance]
from TEACHER_INFO t
join DEPARTMENT_INFO d on d.DEP_ID = CAST(t.TECH_DEPARTMENT as numeric)
join STAFF_LEAVES l on l.STAFF_LEAVES_STAFF_ID = t.TECH_ID
join STAFF_LEAVES_CALC c on c.STAFF_LEAVES_CALC_STAFF_ID = t.TECH_ID
join STAFF_SALLERY s on s.STAFF_SALLERY_STAFF_ID = t.TECH_ID and s.STAFF_SALLERY_MONTH_DATE = c.STAFF_LEAVES_CALC_DATE

where s.STAFF_SALLERY_MONTH_DATE between @START_DATE and @END_DATE and s.STAFF_SALLERY_BR_ID = @BR_ID and  t.TECH_STATUS = 'T' 
order by d.DEP_RANK, t.TECH_RANKING,CAST(t.TECH_EMPLOYEE_CODE as int), DATEPART(MONTH,s.STAFF_SALLERY_MONTH_DATE )