
CREATE procedure  [dbo].[sp_EXAM_ENTRY_updation]
                                               
                                               
          @EXAM_ENTRY_ID  numeric,
          @EXAM_ENTRY_PLAN_EXAM_ID  numeric,
          @EXAM_ENTRY_EXAM_TYPE  nvarchar(50),
          @EXAM_ENTRY_STUDENT_ID numeric,
          @EXAM_ENTRY_OBTAIN_MARKS  float,
          @EXAM_ENTRY_ENTER_DATE  datetime,
          @EXAM_ENTRY_STATUS  char(2) ,
		  @EXAM_ENTRY_OBTAINED_MARKS_LOG nvarchar(500),
		  @EXAM_APPROVAL_RANKWISE_STATUS nvarchar(100),
		  @USER_LOGIN_ID numeric
   
   
     as begin 
   
   if @EXAM_ENTRY_ID = 0
   BEGIN
		exec sp_EXAM_ENTRY_insertion @EXAM_ENTRY_PLAN_EXAM_ID,@EXAM_ENTRY_EXAM_TYPE,@EXAM_ENTRY_STUDENT_ID,@EXAM_ENTRY_OBTAIN_MARKS,@EXAM_ENTRY_ENTER_DATE, @EXAM_ENTRY_STATUS, @EXAM_ENTRY_OBTAINED_MARKS_LOG,	@EXAM_APPROVAL_RANKWISE_STATUS, @USER_LOGIN_ID
   END
   ELSE 
   BEGIN

     update EXAM_ENTRY
 
     set
          EXAM_ENTRY_PLAN_EXAM_ID =  @EXAM_ENTRY_PLAN_EXAM_ID,
          EXAM_ENTRY_EXAM_TYPE = @EXAM_ENTRY_EXAM_TYPE,
          EXAM_ENTRY_STUDENT_ID = @EXAM_ENTRY_STUDENT_ID,
          EXAM_ENTRY_OBTAIN_MARKS =  @EXAM_ENTRY_OBTAIN_MARKS,
          --EXAM_ENTRY_ENTER_DATE =  @EXAM_ENTRY_ENTER_DATE,
          EXAM_ENTRY_STATUS =  @EXAM_ENTRY_STATUS,
		  EXAM_ENTRY_OBTAINED_MARKS_LOG=@EXAM_ENTRY_OBTAINED_MARKS_LOG,
		  UPDATED_DATE = GETDATE(),
		  UPDATED_BY = @USER_LOGIN_ID
 
     where 
          EXAM_ENTRY_ID =  @EXAM_ENTRY_ID 
	END

		  if (select COUNT(*) from EXAM_APPROVAL_STATUS where EXAM_APPROVAL_PLAN_EXAM_ID = @EXAM_ENTRY_PLAN_EXAM_ID) = 0
		  BEGIN
			exec sp_EXAM_APPROVAL_STATUS_insertion @EXAM_ENTRY_PLAN_EXAM_ID, @EXAM_APPROVAL_RANKWISE_STATUS
		  END
		  ELSE
		  BEGIN
			exec sp_EXAM_APPROVAL_STATUS_updation @EXAM_ENTRY_PLAN_EXAM_ID, @EXAM_APPROVAL_RANKWISE_STATUS
		  END
 
end