
CREATE procedure  [dbo].[sp_EXAM_DEF_insertion]
                                               
                                               
          @EXAM_DEF_PID  numeric,
          @EXAM_DEF_CLASS_ID  numeric,
          @EXAM_DEF_SUBJECT_TYPE_ID numeric,
          @EXAM_DEF_TOTAL_MARKS  float,
          @EXAM_DEF_PASS_AGE  float,
          @EXAM_DEF_AGE_IN_NEXT_TERM  float,
          @EXAM_DEF_AGE_IN_FINAL  float,
          @EXAM_DEF_STATUS  char(2),
          @status char(2),
          @EXAM_DEF_ID numeric,
          @EXAM_DEF_MARKS_TYPE nvarchar(50),
          @EXAM_DEF_GRACE_NUMBERS float,
		  @EXAM_DEF_TERM_RANKS_TEST nvarchar(50),
		  @EXAM_DEF_TERM_RANKS_TEST_PERCENTAGE nvarchar(50),
		  @EXAM_DEF_TERM_RANKS_ASSIGNMENTS nvarchar(50),
		  @EXAM_DEF_TERM_RANKS_ASSIGNMENTS_PERCENTAGE nvarchar(50),
		  @EXAM_DEF_TERM_RANKS_PRESENTATIONS nvarchar(50),
		  @EXAM_DEF_TERM_RANKS_PRESENTATIONS_PERCENTAGE nvarchar(50),
		  @EXAM_DEF_TERM_RANKS_QUIZ nvarchar(50),
		  @EXAM_DEF_TERM_RANKS_QUIZ_PERCENTAGE nvarchar(50),
		  @EXAM_DEF_TERM_BEST_TESTS int

     as  begin
		
		if @status = 'I'
		begin
			set	@EXAM_DEF_PID = (select MAX(ID) from VEXAM)
			
				insert into EXAM_DEF
				 values
				 (        
					@EXAM_DEF_PID,
					@EXAM_DEF_CLASS_ID,
					@EXAM_DEF_SUBJECT_TYPE_ID,
					@EXAM_DEF_TOTAL_MARKS,
					@EXAM_DEF_PASS_AGE,
					@EXAM_DEF_AGE_IN_NEXT_TERM,
					@EXAM_DEF_AGE_IN_FINAL,
					@EXAM_DEF_STATUS,
					@EXAM_DEF_MARKS_TYPE,
					@EXAM_DEF_GRACE_NUMBERS,
			        @EXAM_DEF_TERM_RANKS_TEST,
					@EXAM_DEF_TERM_RANKS_TEST_PERCENTAGE,
					@EXAM_DEF_TERM_RANKS_ASSIGNMENTS,
					@EXAM_DEF_TERM_RANKS_ASSIGNMENTS_PERCENTAGE,
					@EXAM_DEF_TERM_RANKS_PRESENTATIONS,
					@EXAM_DEF_TERM_RANKS_PRESENTATIONS_PERCENTAGE,
					@EXAM_DEF_TERM_RANKS_QUIZ,
					@EXAM_DEF_TERM_RANKS_QUIZ_PERCENTAGE,
					@EXAM_DEF_TERM_BEST_TESTS
				 )
		end	
		

		else if @status = 'A'		
		BEGIN
			insert into EXAM_DEF
				 values
				 (        
					@EXAM_DEF_PID,
					@EXAM_DEF_CLASS_ID,
					@EXAM_DEF_SUBJECT_TYPE_ID,
					@EXAM_DEF_TOTAL_MARKS,
					@EXAM_DEF_PASS_AGE,
					@EXAM_DEF_AGE_IN_NEXT_TERM,
					@EXAM_DEF_AGE_IN_FINAL,
					@EXAM_DEF_STATUS,
					@EXAM_DEF_MARKS_TYPE,
					@EXAM_DEF_GRACE_NUMBERS,
					@EXAM_DEF_TERM_RANKS_TEST,
					@EXAM_DEF_TERM_RANKS_TEST_PERCENTAGE,
					@EXAM_DEF_TERM_RANKS_ASSIGNMENTS,
					@EXAM_DEF_TERM_RANKS_ASSIGNMENTS_PERCENTAGE,
					@EXAM_DEF_TERM_RANKS_PRESENTATIONS,
					@EXAM_DEF_TERM_RANKS_PRESENTATIONS_PERCENTAGE,
					@EXAM_DEF_TERM_RANKS_QUIZ,
					@EXAM_DEF_TERM_RANKS_QUIZ_PERCENTAGE,
					@EXAM_DEF_TERM_BEST_TESTS
				 )		
		END
     
     
     
     else if @status = 'U'
     BEGIN
		update EXAM_DEF
 
     set
          EXAM_DEF_PID =  @EXAM_DEF_PID,
          EXAM_DEF_CLASS_ID =  @EXAM_DEF_CLASS_ID,
          EXAM_DEF_SUBJECT_TYPE_ID = @EXAM_DEF_SUBJECT_TYPE_ID,
          EXAM_DEF_TOTAL_MARKS =  @EXAM_DEF_TOTAL_MARKS,
          [EXAM_DEF_PASS_%AGE] =  @EXAM_DEF_PASS_AGE,
          [EXAM_DEF_NEXT_TERM_%AGE] =  @EXAM_DEF_AGE_IN_NEXT_TERM,
          [EXAM_DEF_FINAL_%AGE] =  @EXAM_DEF_AGE_IN_FINAL,
          EXAM_DEF_STATUS =  @EXAM_DEF_STATUS,
          EXAM_DEF_MARKS_TYPE = @EXAM_DEF_MARKS_TYPE,
          EXAM_DEF_GRACE_NUMBERS = @EXAM_DEF_GRACE_NUMBERS,
		  EXAM_DEF_TERM_RANKS_TEST = @EXAM_DEF_TERM_RANKS_TEST,
		  EXAM_DEF_TERM_RANKS_TEST_PERCENTAGE = @EXAM_DEF_TERM_RANKS_TEST_PERCENTAGE,
		  EXAM_DEF_TERM_RANKS_ASSIGNMENTS = @EXAM_DEF_TERM_RANKS_ASSIGNMENTS,
		  EXAM_DEF_TERM_RANKS_ASSIGNMENTS_PERCENTAGE =		@EXAM_DEF_TERM_RANKS_ASSIGNMENTS_PERCENTAGE,
		  EXAM_DEF_TERM_RANKS_PRESENTATIONS = 	@EXAM_DEF_TERM_RANKS_PRESENTATIONS,
		  EXAM_DEF_TERM_RANKS_PRESENTATIONS_PERCENTAGE = 	@EXAM_DEF_TERM_RANKS_PRESENTATIONS_PERCENTAGE,
		  EXAM_DEF_TERM_RANKS_QUIZ = 		@EXAM_DEF_TERM_RANKS_QUIZ,
		  EXAM_DEF_TERM_RANKS_QUIZ_PERCENTAGE =		@EXAM_DEF_TERM_RANKS_QUIZ_PERCENTAGE,
		  EXAM_DEF_TERM_BEST_TESTS = @EXAM_DEF_TERM_BEST_TESTS
 
     where 
          EXAM_DEF_ID =  @EXAM_DEF_ID 
     END
     --select * from EXAM_DEF
end