
CREATE PROC [dbo].[sp_EXAM_TEST_ALL]
@CLASS_ID numeric,
@TERM_ID numeric,
@SUBJECT_ID numeric


AS

select EXAM_TEST_ID ID, EXAM_TEST_NAME [Name] from EXAM_TEST 
where EXAM_TEST_CLASS_ID = @CLASS_ID and EXAM_TEST_TERM_ID = @TERM_ID and EXAM_TEST_SUBJECT_ID = @SUBJECT_ID
and EXAM_TEST_ID in (select EXAM_ENTRY_PLAN_EXAM_ID from EXAM_ENTRY where EXAM_ENTRY_EXAM_TYPE = 'Test')

select s.STDNT_ID [Std ID],s.STDNT_SCHOOL_ID [Std #], s.STDNT_FIRST_NAME Name, et.EXAM_TEST_TOTAL_MARKS [Total Marks],e.EXAM_ENTRY_OBTAIN_MARKS [Obtain Marks],et.EXAM_TEST_ID [Test ID] from EXAM_ENTRY e 
join EXAM_TEST et  on et.EXAM_TEST_ID = e.EXAM_ENTRY_PLAN_EXAM_ID
join STUDENT_INFO s on s.STDNT_ID = e.EXAM_ENTRY_STUDENT_ID
where EXAM_ENTRY_EXAM_TYPE = 'Test' and EXAM_ENTRY_PLAN_EXAM_ID in
(select EXAM_TEST_ID ID from EXAM_TEST 
where EXAM_TEST_CLASS_ID = @CLASS_ID and EXAM_TEST_TERM_ID = @TERM_ID and EXAM_TEST_SUBJECT_ID = @SUBJECT_ID)