CREATE PROCEDURE [dbo].[sp_FEE_COLLECT_MODIFICATION_insertion]

@FEE_COLLECT_PLAN_ID NUMERIC,
@FEE_COLLECT_DEFF NVARCHAR(50),
@FEE_COLLECT_FEE FLOAT,
@FEE_COLLECT_FEE_MIN FLOAT,
@FEE_COLLECT_FEE_MAX FLOAT,
@FEE_COLLECT_OPERATE char(1)

AS BEGIN

	 
	 declare @is_once_paid char(1) = ''

	 set @is_once_paid = (select PLAN_FEE_IS_ONCE_PAID from PLAN_FEE_DEF where PLAN_FEE_DEF_STATUS = 'T' and  PLAN_FEE_DEF_FEE_NAME = @FEE_COLLECT_DEFF and 
	 PLAN_FEE_DEF_PLAN_ID in ( select STDNT_CLASS_FEE_ID from STUDENT_INFO where STDNT_CLASS_PLANE_ID = @FEE_COLLECT_PLAN_ID ) )
	 
	 delete from PLAN_FEE_DEF
	 where PLAN_FEE_DEF_FEE_NAME = @FEE_COLLECT_DEFF and 
	 PLAN_FEE_DEF_PLAN_ID in ( select STDNT_CLASS_FEE_ID from STUDENT_INFO where STDNT_CLASS_PLANE_ID = @FEE_COLLECT_PLAN_ID )

	 set @is_once_paid = ISNULL(@is_once_paid,'N')


	 

	insert into PLAN_FEE_DEF
	select STDNT_CLASS_FEE_ID,@FEE_COLLECT_DEFF,@FEE_COLLECT_FEE,@FEE_COLLECT_FEE_MIN,@FEE_COLLECT_FEE_MAX,'T',@FEE_COLLECT_OPERATE,'' from STUDENT_INFO where STDNT_CLASS_PLANE_ID = @FEE_COLLECT_PLAN_ID
						
	select 'ok'
						
END

select * from PLAN_FEE_DEF