
     CREATE procedure  [dbo].[sp_LEAVES_RECORD_selection]
                                               
                                               
     @STATUS char(10),
     @LEAVES_RECORD_ID  numeric,
     @LEAVES_RECORD_HD_ID  numeric,
     @LEAVES_RECORD_BR_ID  numeric,
	 @LEAVES_RECORD_FROM_DATE date,
	 @LEAVES_RECORD_TO_DATE date
   
   
     AS BEGIN 
   
   
   select ID,Name from VTEACHER_INFO where [Institute ID] = @LEAVES_RECORD_HD_ID and [Branch ID] = @LEAVES_RECORD_BR_ID and Status = 'T'

     select ROW_NUMBER() over(order by (select 0)) + 215 as PrimaryID,* from
	(SELECT LEAVES_RECORD_ID ID, LEAVES_RECORD_STAFF_ID [Staff ID], LEAVES_RECORD_FROM_DATE [From Date], LEAVES_RECORD_TO_DATE [To Date], '00:00' as [From Time], '00:00' as [To Time] , LEAVES_RECORD_REASON as Reason, 0 [Is Short Leave], LEAVES_RECORD_IS_CAUSAL_LEAVES [Is Causal Leaves], LEAVES_RECORD_IS_ANNUAL_LEAVES [Is Annual Leaves],(DATEDIFF(DD,LEAVES_RECORD_FROM_DATE,LEAVES_RECORD_TO_DATE) + 1) as [Total Leaves],CASE WHEN LEAVES_RECORD_IS_CAUSAL_LEAVES = 1 THEN (DATEDIFF(DD,LEAVES_RECORD_FROM_DATE,LEAVES_RECORD_TO_DATE) + 1) ELSE 0 END TC,CASE WHEN LEAVES_RECORD_IS_ANNUAL_LEAVES = 1 THEN (DATEDIFF(DD,LEAVES_RECORD_FROM_DATE,LEAVES_RECORD_TO_DATE) + 1) ELSE 0 END TA FROM LEAVES_RECORD 
	 where LEAVES_RECORD_HD_ID =  @LEAVES_RECORD_HD_ID and 
     LEAVES_RECORD_BR_ID =  @LEAVES_RECORD_BR_ID  and LEAVES_RECORD_FROM_DATE between @LEAVES_RECORD_FROM_DATE and @LEAVES_RECORD_TO_DATE
     
	 union

	 select s.SHORT_LEAVE_ID as ID, s.SHORT_LEAVE_STAFF_ID [Staff ID], s.SHORT_LEAVE_DATE [From Date], s.SHORT_LEAVE_DATE [To Date],
		SHORT_LEAVE_FROM_TIME as [From Time], SHORT_LEAVE_TO_TIME as [To Time],SHORT_LEAVE_REASON as Reason,  1 [Is Short Leave], CASE WHEN s.SHORT_LEAVE_IS_ANNUAL = 0 THEN 1 ELSE 0 END as [Is Causal Leaves], s.SHORT_LEAVE_IS_ANNUAL [Is Annual Leaves], 0.5 [Total Leaves], CASE WHEN s.SHORT_LEAVE_IS_ANNUAL = 0 THEN 0.5 ELSE 0 END TC,CASE WHEN s.SHORT_LEAVE_IS_ANNUAL = 1 THEN 0.5 ELSE 0 END TA 
		from SHORT_LEAVE s
		--join TEACHER_INFO t on t.TECH_ID = s.SHORT_LEAVE_STAFF_ID
		where s.SHORT_LEAVE_DATE between @LEAVES_RECORD_FROM_DATE and @LEAVES_RECORD_TO_DATE and s.SHORT_LEAVE_HD_ID = @LEAVES_RECORD_HD_ID and SHORT_LEAVE_BR_ID = @LEAVES_RECORD_BR_ID)A
		order by [From Date],[From Time]
	 
	 
	 END