CREATE procedure  [dbo].[sp_STAFF_LEAVES_insertion]
                                               
                                               
          @STAFF_LEAVES_HD_ID  numeric,
          @STAFF_LEAVES_BR_ID  numeric,
          @STAFF_LEAVES_YEAR  numeric,
          @STAFF_LEAVES_NAME  nvarchar(200) ,
          @STAFF_LEAVES_MONTHLY_LIMIT  numeric,
          @STAFF_LEAVES_TRANSFER_YEAR  char(2) ,
          @STAFF_LEAVES_TRANSFER_MONTH  char(2) ,
          @STAFF_LEAVES_STAFF_ID  numeric,
          @STAFF_LEAVES_ABSENT_DEDUCTION char(2),
          @STAFF_LEAVES_DATE  datetime,
          @STAFF_LEAVES_USER  nvarchar(200) ,
          @STAFF_LEAVES_STATUS  char(2),
          @STAFF_LEAVES_LATE_PER_ABSENT numeric,
          @STAFF_LEAVES_DEDUCTION_LEAVES char(2),
          @STAFF_LEAVES_ADD_WEEKEND_HOLIDAYS char(2),
		  @STAFF_LEAVES_ADD_EXCEPTIONAL_HOLIDAYS char(2),
		  @STAFF_LEAVES_ADD_DEDUCTION char(2),
		  @STAFF_LEAVES_ADD_ALLOWANCES char(2),
		  @STAFF_LEAVES_ADD_LOAN char(2),
		  @STAFF_LEAVES_DEDUCT_LEAVES_STATUS char(2),
		  @STAFF_LEAVES_DEDUCT_ABSENT_STATUS char(2),
		  @STAFF_LEAVES_CONSECUTIVE_ABSENT_STATUS char(2),
		  @STAFF_LEAVES_CONSECUTIVE_LEAVES_STATUS char(2),
		  @STAFF_LEAVES_CONSECUTIVE_BEFORE_WEEKENDS int,
		  @STAFF_LEAVES_CONSECUTIVE_AFTER_WEEKENDS int,
		  @STAFF_LEAVES_DEDUCT_LEAVES_COUNT float,
		  @STAFF_LEAVES_DEDUCT_ABSENT_COUNT float,
		  @STAFF_LEAVES_PER_DAY_SALARY_TYPE nvarchar(50),
		  @STAFF_LEAVES_LATE_DEDUCTION_TYPE nvarchar(50),
		  @STAFF_LEAVES_PAYROLL_MINUTES_IN_HOUR int,
		  @STAFF_LEAVES_PAYROLL_HOURS_IN_DAY int,
		  @STAFF_LEAVES_PAYROLL_OVERTIME_MINUTES_IN_HOUR_BEFORE_TIMEIN int,
		  @STAFF_LEAVES_PAYROLL_EARLY_DEPARTURE_MINUTES int,
		  @STAFF_LEAVES_SUMMER_LEAVES int,
		  @STAFF_LEAVES_WINTER_LEAVES int,
		  @STAFF_LEAVES_EARLY_PER_ABSENT numeric
   
   
     as  begin
   
   
     insert into STAFF_LEAVES
     values
     (
        @STAFF_LEAVES_HD_ID,
        @STAFF_LEAVES_BR_ID,
        @STAFF_LEAVES_YEAR,
        @STAFF_LEAVES_NAME,
        @STAFF_LEAVES_MONTHLY_LIMIT,
        @STAFF_LEAVES_TRANSFER_YEAR,
        @STAFF_LEAVES_TRANSFER_MONTH,
        @STAFF_LEAVES_STAFF_ID,
        @STAFF_LEAVES_ABSENT_DEDUCTION,
        @STAFF_LEAVES_DATE,
        @STAFF_LEAVES_USER,
        @STAFF_LEAVES_STATUS,
        @STAFF_LEAVES_LATE_PER_ABSENT,
        @STAFF_LEAVES_DEDUCTION_LEAVES,
        @STAFF_LEAVES_ADD_WEEKEND_HOLIDAYS,
		@STAFF_LEAVES_ADD_EXCEPTIONAL_HOLIDAYS ,
		@STAFF_LEAVES_ADD_DEDUCTION,
		@STAFF_LEAVES_ADD_ALLOWANCES,
		@STAFF_LEAVES_ADD_LOAN,
		@STAFF_LEAVES_DEDUCT_LEAVES_STATUS,
		@STAFF_LEAVES_DEDUCT_ABSENT_STATUS,
		@STAFF_LEAVES_CONSECUTIVE_ABSENT_STATUS,
		@STAFF_LEAVES_CONSECUTIVE_LEAVES_STATUS,
		@STAFF_LEAVES_CONSECUTIVE_BEFORE_WEEKENDS,
		@STAFF_LEAVES_CONSECUTIVE_AFTER_WEEKENDS,
		@STAFF_LEAVES_DEDUCT_LEAVES_COUNT,
		@STAFF_LEAVES_DEDUCT_ABSENT_COUNT,
		@STAFF_LEAVES_PER_DAY_SALARY_TYPE,
		@STAFF_LEAVES_LATE_DEDUCTION_TYPE,
		@STAFF_LEAVES_PAYROLL_MINUTES_IN_HOUR ,
		@STAFF_LEAVES_PAYROLL_HOURS_IN_DAY,
		@STAFF_LEAVES_PAYROLL_OVERTIME_MINUTES_IN_HOUR_BEFORE_TIMEIN,
		@STAFF_LEAVES_PAYROLL_EARLY_DEPARTURE_MINUTES,
		@STAFF_LEAVES_SUMMER_LEAVES ,
		@STAFF_LEAVES_WINTER_LEAVES,
		@STAFF_LEAVES_EARLY_PER_ABSENT
     
     )
     
end