

CREATE PROC [dbo].[sp_STUDENT_INFO_SINGLE_selection]

@ID numeric,
@SessionId numeric


AS



select STDNT_ID, STDNT_HD_ID, STDNT_BR_ID, STDNT_PARANT_ID,sc.ClassId STDNT_CLASS_PLANE_ID, STDNT_CLASS_FEE_ID, STDNT_REG_BY_ID, STDNT_REG_BY_TYPE, STDNT_FIRST_NAME, STDNT_LAST_NAME, STDNT_GENDER, STDNT_NATIONALITY, STDNT_RELIGION, STDNT_DOB, STDNT_PREVIOUS_SCHOOL, STDNT_MOTHR_LANG, STDNT_EMAIL, STDNT_IMG, STDNT_EMERGENCY_CNTCT_NAME, STDNT_EMERGENCY_CNTCT_NO, STDNT_CELL_NO, STDNT_TEMP_ADDR, STDNT_PERM_ADDR, STDNT_TRANSPORT_MODE, STDNT_REG_DATE, STDNT_CLASSES_START_DATE, STDNT_STATUS, STDNT_SCHOOL_ID, STDNT_REGISTRATION_ID, STDNT_SESSION_ID, STDNT_DESCRIPTION, STDNT_DISCOUNT_RULE_ID, STDNT_HOUSE_ID, STDNT_DATE_OF_LEAVING, STDNT_WITH_DRAW_NO, STDNT_CATEGORY, STDNT_CONDUCT_ID, STDNT_REMARKS, STDNT_COA_ID, STDNT_CITY_ID, STDNT_AREA_ID, STDNT_SCHOLARSHIP_ID, STDNT_LAB_TYPE, STDNT_IS_REJOIN, ISNULL(STDNT_IS_CITRIX,CAST(0 as bit)) STDNT_IS_CITRIX,STDNT_CITREX_SUBSCRIBTION_CODE,CreatedDate, CreatedBy, UpdatedDate, UpdatedBy, s.STDNT_SHORT_NAME

, u.USER_STATUS from STUDENT_INFO s 
join tblStudentClassPlan sc on sc.StudentId = s.STDNT_ID
join USER_INFO u on u.USER_CODE = s.STDNT_ID and u.USER_TYPE = 'Student'
where STDNT_ID = @ID and sc.SessionId = @SessionId