CREATE procedure  [dbo].[sp_STUDENT_ROLL_NO_updation] 


@STUDENT_ROLL_NO_STD_ID numeric,
@STUDENT_ROLL_NO_HD_ID numeric,
@STUDENT_ROLL_NO_BR_ID numeric,
@STUDENT_ROLL_NO_ROLL_NO numeric
AS
BEGIN

--declare @STUDENT_ROLL_NO_STD_ID numeric = 3
--declare @STUDENT_ROLL_NO_HD_ID numeric = 1
--declare @STUDENT_ROLL_NO_BR_ID numeric = 1
--declare @STUDENT_ROLL_NO_ROLL_NO numeric = 4

UPDATE STUDENT_ROLL_NUM set STUDENT_ROLL_NUM_ROLL_NO = @STUDENT_ROLL_NO_ROLL_NO
where STUDENT_ROLL_NUM_HD_ID = @STUDENT_ROLL_NO_HD_ID and
STUDENT_ROLL_NUM_BR_ID = @STUDENT_ROLL_NO_BR_ID and
STUDENT_ROLL_NUM_STD_ID = @STUDENT_ROLL_NO_STD_ID and 
STUDENT_ROLL_NUM_ACTIVE_STATUS in ('new', 'old') and
STUDENT_ROLL_NUM_STATUS = 'T'



END