CREATE PROC [dbo].[sp_UPDATE_ATTENDANCE_SET_TIME_POLICY]

 @STAFF_ID numeric,
@PACKAGE_ID numeric,
@USER_NAME nvarchar(50)


AS

--declare @STAFF_ID numeric
--declare @PACKAGE_ID numeric
--declare @USER_NAME nvarchar(50)


delete from STAFF_WORKING_DAYS where STAFF_WORKING_DAYS_STAFF_ID = @STAFF_ID





insert into STAFF_WORKING_DAYS
select p.HOURS_PACK_HD_ID,p.HOURS_PACK_BR_ID,w.WORK_PACK_DEF_DAY_NAME,w.WORK_PACK_DEF_DAY_STATUS,w.WORK_PACK_DEF_TIME_IN,w.WORK_PACK_DEF_TIME_OUT,@USER_NAME,@STAFF_ID,GETDATE(),@PACKAGE_ID,'T' from WORKING_HOURS_PACKAGES_DEF w
join WORKING_HOURS_PACKAGES p on p.HOURS_PACK_ID = w.WORK_PACK_DEF_PID
where WORK_PACK_DEF_PID = @PACKAGE_ID 


--delete from STAFF_WORKING_DAYS where STAFF_WORKING_DAYS_STAFF_ID = @STAFF_ID and STAFF_WORKING_DAYS_STATUS = 'D'