

CREATE procedure  [dbo].[sp_USER_INFO_selection]                                                                                             
     @STATUS char(10),
     @USER_ID  numeric,
     @USER_NAME  nvarchar(50) ,
     @USER_PASSWORD  nvarchar(50)       
     AS BEGIN       
     if @STATUS = 'A'
     BEGIN
   
			 SELECT * FROM USER_INFO
			 where USER_STATUS != 'D'
       
     END  
     
     ELSE  if @STATUS = 'B'
		 BEGIN
	  SELECT * FROM USER_INFO
		 WHERE    
		 [USER_ID] =  @USER_ID      
		 end
     
     ELSE  if @STATUS = 'L'
        BEGIN     
		 
				 declare @count int = 0
		 
				 set @count = (SELECT COUNT(*) FROM USER_INFO U 
				 inner join BR_ADMIN B on U.USER_BR_ID = B.BR_ADM_ID 
				 inner join MAIN_HD_INFO M on U.USER_HD_ID = M.MAIN_INFO_ID
				 inner join REPORT_SETTING R on B.BR_ADM_ID = R.REPORT_SETTING_BR_ID
				 LEFT join RIGHTS_PACKAGES_PARENT p on  p.PACKAGES_ID = U.USER_ROLE
				 WHERE    
					U.[USER_NAME] =  @USER_NAME
					and U.USER_PASSWORD =  @USER_PASSWORD
					and U.USER_STATUS != 'D'     
					and B.BR_ADM_STATUS = 'T'
					and M.MAIN_INFO_STATUS = 'T')


					if @count = 0
					begin
						--declare @count_user_info int = 0
						--set @count_user_info = (select COUNT(*) from user_info u where U.[USER_NAME] =  @USER_NAME and U.USER_PASSWORD =  @USER_PASSWORD
						--		and U.USER_STATUS != 'D' and USER_BR_ID = 0 )

						--if @count_user_info = 0


					SELECT U.*, p.PACKAGES_NAME as [Role], M.MAIN_INFO_INSTITUTION_SHORT_NAME as SHORT_NAME,M.MAIN_INFO_INSTITUTION_FULL_NAME +' ('+BR_ADM_NAME+')' AS [INSTITE_NAME],B.BR_ADM_ADDRESS AS [INSTITE_ADDRESS],B.BR_ADM_PHONE AS [INSTITE_PHONE],B.BR_ADM_MOBILE AS [INSTITE_MOBILE],M.MAIN_INFO_INSTITUTION_LOGO AS[INSTITE_LOGO],M.MAIN_INFO_HEAD_OFFICE,M.MAIN_INFO_LOGO_REPORTS [REPORTS_LOGO],b.BR_ADM_WEBSITE [INSTITE_WEBSITE],R.REPORT_SETTING_REPORT_VALUE [REPORT_CHALLAN],B.BR_ADM_IS_ADVANCE_ACCOUNTING [IS_ADVANCE_ACCOUNTING], B.BR_ADM_IS_ADVANCE_CLASS_PLAN [IS_ADVANCE_CLASS_PLAN],B.BR_ADM_IS_FEES_WITH_ACCOUNTS [IS_FEES_WITH_ACCOUNTS], B.BR_ADM_FEES_PER_MONTHS [FEES_PER_MONTHS],  B.BR_ADM_IS_CLASS_PLAN_ALLOWED [IS_CLASS_PLAN_ALLOWED], B.BR_ADM_IS_BAR_CODE_READER_ALLOW [IS_BAR_CODE_READER_ALLOW], M.MAIN_INFO_INSTITUTION_FULL_NAME [School Name], BR_ADM_NAME [Branch Name]  FROM USER_INFO U 
				 left join BR_ADMIN B on U.USER_BR_ID = B.BR_ADM_ID 
				 left join MAIN_HD_INFO M on U.USER_HD_ID = M.MAIN_INFO_ID
				 left join REPORT_SETTING R on B.BR_ADM_ID = R.REPORT_SETTING_BR_ID
				 LEFT join RIGHTS_PACKAGES_PARENT p on  p.PACKAGES_ID = U.USER_ROLE
				 WHERE    
					U.[USER_NAME] =  @USER_NAME
					and U.USER_PASSWORD =  @USER_PASSWORD
					and U.USER_STATUS != 'D'
					and M.MAIN_INFO_STATUS = 'T'
		
					end


					
				else
				begin
					SELECT U.*, p.PACKAGES_NAME as [Role], M.MAIN_INFO_INSTITUTION_SHORT_NAME as SHORT_NAME, M.MAIN_INFO_INSTITUTION_FULL_NAME +' ('+BR_ADM_NAME+')' AS [INSTITE_NAME],B.BR_ADM_ADDRESS AS [INSTITE_ADDRESS],B.BR_ADM_PHONE AS [INSTITE_PHONE],B.BR_ADM_MOBILE AS [INSTITE_MOBILE],M.MAIN_INFO_INSTITUTION_LOGO AS[INSTITE_LOGO],M.MAIN_INFO_HEAD_OFFICE,b.BR_ADM_WEBSITE [INSTITE_WEBSITE],R.REPORT_SETTING_REPORT_VALUE [REPORT_CHALLAN],B.BR_ADM_IS_ADVANCE_ACCOUNTING [IS_ADVANCE_ACCOUNTING], B.BR_ADM_IS_ADVANCE_CLASS_PLAN [IS_ADVANCE_CLASS_PLAN],B.BR_ADM_IS_FEES_WITH_ACCOUNTS [IS_FEES_WITH_ACCOUNTS], B.BR_ADM_FEES_PER_MONTHS [FEES_PER_MONTHS],  B.BR_ADM_IS_CLASS_PLAN_ALLOWED [IS_CLASS_PLAN_ALLOWED], B.BR_ADM_IS_BAR_CODE_READER_ALLOW [IS_BAR_CODE_READER_ALLOW], M.MAIN_INFO_INSTITUTION_FULL_NAME [School Name], BR_ADM_NAME [Branch Name],M.MAIN_INFO_LOGO_REPORTS [REPORTS_LOGO],s.SESSION_DESC [CURRENT_SESSION],BR_ADM_LOGO [Logo], BR_ADM_REPORTS_LOGO [Report Logo], BR_ADM_IS_DIFFERENT_LOGOS [Is Different Logo], BR_ADM_FONTS [Fonts],dbo.sf_GET_User_Image(u.USER_TYPE,u.USER_CODE, u.USER_ROLE) Image_Gender, s.SESSION_ID [Session ID], B.BR_ADM_PHONE BranchPhone   FROM USER_INFO U 
				 inner join BR_ADMIN B on U.USER_BR_ID = B.BR_ADM_ID 
				 inner join MAIN_HD_INFO M on U.USER_HD_ID = M.MAIN_INFO_ID
				 inner join REPORT_SETTING R on B.BR_ADM_ID = R.REPORT_SETTING_BR_ID
				 LEFT join RIGHTS_PACKAGES_PARENT p on  p.PACKAGES_ID = U.USER_ROLE
				 join SESSION_INFO s on s.SESSION_ID = b.BR_ADM_SESSION				 
				 WHERE    
					U.[USER_NAME] =  @USER_NAME
					and U.USER_PASSWORD =  @USER_PASSWORD
					and U.USER_STATUS != 'D'     
					and B.BR_ADM_STATUS = 'T'
					and M.MAIN_INFO_STATUS = 'T'
			end

			declare @br_id int = 0
			set @br_id = (select USER_BR_ID from USER_INFO where USER_NAME = @USER_NAME and USER_PASSWORD = @USER_PASSWORD)

			select * from VDEFAULT_VALUES where [BR ID] = @br_id


		select sp.CLASS_ID [Class ID], sp.CLASS_Name [Class Name], sp.CLASS_LEVEL_ID [Level ID], CASE WHEN bl.BRANCH_LEVEL_LOGO  is null THEN b.BR_ADM_REPORTS_LOGO  ELSE bl.BRANCH_LEVEL_LOGO END Logo, CASE WHEN bl.BRANCH_LEVEL_FONTS is null THEN b.BR_ADM_FONTS ELSE bl.BRANCH_LEVEL_FONTS END Fonts, CASE WHEN bl.BRANCH_LEVEL_SCHOOL_NAME is null THEN h.MAIN_INFO_INSTITUTION_FULL_NAME ELSE bl.BRANCH_LEVEL_SCHOOL_NAME END [School Name]
			from SCHOOL_PLANE sp
			left join BRANCH_LEVEL bl on bl.BRANCH_LEVEL_LEVEL_ID = sp.CLASS_LEVEL_ID  AND BL.BRANCH_LEVEL_BR_ID = SP.CLASS_BR_ID
			left join LEVELS l on l.LEVEL_ID = bl.BRANCH_LEVEL_ID
			join BR_ADMIN b on b.BR_ADM_ID = sp.CLASS_BR_ID
			join MAIN_HD_INFO h on h.MAIN_INFO_ID = b.BR_ADM_HD_ID
			
			where sp.CLASS_BR_ID in (select COMBINE_BRANCHES_ID from COMBINE_BRANCHES where FROM_BRANCH_ID =   @br_id)
			--and sp.CLASS_SESSION_ID = b.BR_ADM_SESSION


			
			
		 END
 
     END